src/libtools/examples/merging.cpp, src/libtools/include/merging/automergestrategy.hpp, src/libtools/include/merging/interactivemergestrategy.hpp, src/libtools/include/merging/metamergestrategy.hpp, src/libtools/include/merging/newkeystrategy.hpp, src/libtools/include/merging/onesidestrategy.hpp, src/libtools/include/merging/onesidevaluestrategy.hpp
I put together a small example (basically a simplified version of kdb merge) and a bit documentation around the merging framework as requested in #167. It is not much, but together with the unit tests it should provide a good idea on how the ThreeWayMerger works. If anyone (especially Raffael) has any questions concerning the merge framework, please don't hesitate to ask. I will try to clean up and simplify the framework as soon as I can.
=> Added an example and documentation on how to use the merge framework

examples/keyNew.c, src/include/kdb.h.in, src/libelektra/key.c, src/libelektra/keyhelpers.c, tests/ctest/test_key.c
Bitwise disjunction of flags, which don't require one or more values.
Recommended way to set multiple flags. Overrides previously defined flags.
=> Introduce new flag: KEY_FLAGS

src/plugins/ini/README.md, src/plugins/ini/ini.c, src/plugins/ini/ini/sectionini, src/plugins/ini/testmod_ini.c
A first proposal of how the improved ini section handling discussed in #138 could look like. The plugin behaves as follows:
* keys with a NULL value (i.e. binary keys with value 0) are treated as sections
* all other keys are treated as plain ini keys
* if the autosection option exists, the plugin will automatically create a section entry on write for keys with a level greater than 1 relative to the parent key (see the autosection testcase for a illustrative example)
If you like it this way, I will update the README accordingly. Additionally an option would be thinkable that prevents uses `keyChangeName` to directly use the names of ini keys / sections (see #138) for an example. If you have any further ideas on how to make the the use of the plugin more intuitive, please don't hesitate to …
=> Ini hierarchies

src/plugins/rename/rename.c, src/plugins/rename/testmod_rename.c
This pull request should fix #206. A test that failed before this commit is appended
=> Fixed an issue causing the rename plugin to handle the parentKey incorrectly

doc/COMPILE.md
debug flag was wrong in doc/COMPILE.md.
Cmake said:
"CMake Warning:
Manually-specified variables were not used by the project:
DEBUG_BUILD"
Changed to ELEKTRA_DEBUG_BUILD and it works.
=> DEBUG_BUILD flag corrected

src/libtools/src/helper/comparison.cpp, src/libtools/src/helper/keyhelper.cpp, src/libtools/tests/testtool_comparison.cpp, src/libtools/tests/testtool_keyhelper.cpp
This patch fixes the problem discussed in #174 as well as another issue that caused the synchronization in the qt-gui to fail. The problem discussed in #174 is not really about merging cascading keys, but about handling cascading parent keys (cascading parent keys caused the InvalidRebaseException).
More special treatment for cascading keys in the ThreeWayMerger is thinkable. For example what should happen if one of the keys in the merged keysets is a cascading key? This issue is currently not addressed, but for now I concentrated on fixing the issues affecting the qt-gui. I would suggest renaming #174 and creating another issue that is really about the treatment of cascading keys during a merge.
=> Fixed merge problems with cascading keys

src/libtools/include/helper/keyhelper.hpp, src/libtools/src/helper/keyhelper.cpp, src/libtools/tests/testtool_mergecases.cpp
Another try to fix the issue discussed in #174. When I try the qt-gui now with "/" instead of "user" the only problem left is an error to set information below the version mountpoint. However, this seems unrelated to the merging framework. When stepping through the code in the debugger, added keys are merged fine.
=> Another cascading merge fix

src/libelektra/keyhelpers.c
The type passed is actually an `int` (e.g. as combination of other `int` flags), so using `kdb_unsigned_long_long_t` could read more data from the `va_list` buffer, causing later extractions to return garbage.
=> Fix vararg type for KEY_FLAGS

cmake/Modules/COPYING-CMAKE-SCRIPTS, cmake/Modules/Copyright.txt
Some of the CMake modules shipped refer to these two files for their license, so copy them to have the proper license pointers.
=> Copy COPYING-CMAKE-SCRIPTS and Copyright.txt from CMake

src/bindings/cpp/tests/tests.hpp, tests/cframework/tests.h
`__FUNCTION__` is a non-standard extension, and GCC 5 starts warning about it in pedantic mode; instead, use `__func__` which is standard since C99.
=> Switch from __FUNCTION__ to __func__

src/bindings/swig/lua/tests/test_key.lua, src/bindings/swig/python2/tests/testpy2_key.py, src/bindings/swig/python3/kdb.i, src/bindings/swig/python3/tests/test_key.py
fixing the copy constructor doesn't hurt anyway.
this fixes #237
=> swig: fix kdb::Key(ckdb::Key) constructor

cmake/ElektraCache.cmake
Commit 4363c4d3683c7587dd3eea35875afe43d3116e80 changes it to a location within the Elektra libdir, which is not inside the own CMake modules but still used by CMake;
recent commit ad3c1169946eefbcc105284ada930472f58af9a8 changes it back with no reason (possibly a merge mistake).
Change it as commit 4363c4d3683c7587dd3eea35875afe43d3116e80 intended, so CMake modules are installed in the correct place for them.
=> cmake: change again the modules install directory

doc/tutorials/namespaces.md
I don't know how useful this is as we already have ```doc/NAMESAPCES.md```. 
Please give me feedback about how short (or long) you want the tutorial to be.
=> add short tutorial about namespaces (#280)

src/libgetenv/examples/CMakeLists.txt
This small C application just dumps the content of the environment, printing also the environment variables requested as arguments.
Since this is usually run as tool in a `elektrify-getenv` context, it will get the effects of elektragetenv, and thus linking elektra and elektratools is not needed.
=> getenv example: do not link to elektra/elektratools

src/plugins/python/CMakeLists.txt, src/plugins/python/python.cpp, src/plugins/python/testmod_python.c
after a lot of crashes I finally got subinterpreter support working. In general one shouldn't mix pythons thread state APIs with the GIL API. Thankfully a lot of them is already deprecated (haven't used them).
=> Python: subinterpreter support + some fixes

src/bindings/gi/lua/testgi_kdb.lua, src/bindings/gi/python/testgi_kdb.py, src/bindings/swig/lua/tests/test_kdb.lua, src/bindings/swig/python/tests/test_kdb.py, src/bindings/swig/python2/tests/testpy2_kdb.py
=> bindings: in tests don't check KDB_VERSION if CHECK_VERSION is set

src/libtools/include/merging/mergeresult.hpp, src/libtools/src/merging/threewaymerge.cpp, src/libtools/tests/mergetestutils.cpp, src/libtools/tests/testtool_mergecases.cpp
The commit should fix the issue discussed in #295. However, I could not test the fix with the gui. The gui eats up all my system ressources until the system grinds to a halt. When it finally starts it is so slow that I can hardly click anything. Please let me know if the issue is resolved.
=> merger sync key problem

src/plugins/augeas/augeas.c
Partly fixes the issue discussed in #206. As you have guessed, the error messages stem from Augeas. However, the augeas plugin now includes all the information available from Augeas. The message reported in #206 now looks like this:
```
The command ls failed while accessing the key database with the info:
Error (#85) occurred!
Description: an Augeas error occurred
Ingroup: plugin
Module: storage
At: /path/to/augeas.c:425
Reason: parse_failed
position: 58:0
message: Iterated lens matched less than it should
lens: /raw/tree
Mountpoint: system/limits
Configfile: /etc/security/limits.conf
=> Improved the augeas plugin error messages

src/plugins/mathcheck/mathcheck.c
fixed wrong handling of keynames with length == 1 and keys directly below the parent key.
=> fix #357: wrong handling of some keynames

src/plugins/crypto/crypto.h
I forgot to add `elektraCryptoTeardown()`'s declaration to `crypto.h`.
=> Fix issue #364 - compiler warning

cmake/Modules/LibAddPlugin.cmake, src/plugins/plugin-symbols.map
The one and only (allowed) is elektraPluginSymbol
=> Make sure plugins don't export any of their symbols

src/plugins/lua/lua.cpp, src/plugins/lua/lua/lua_filter.lua, src/plugins/lua/lua/lua_plugin.lua, src/plugins/lua/lua/lua_plugin2.lua, src/plugins/lua/lua/lua_plugin_fail.lua, src/plugins/lua/lua/lua_plugin_wrong.lua, src/plugins/python/python.cpp, src/plugins/python/python/python_configparser.py, src/plugins/python/python/python_plugin.py, src/plugins/python/python/python_plugin2.py, src/plugins/python/python/python_plugin_fail.py
As discussed in #394 this adds the config keyset (from elektraPluginGetConfig) to the open-call in both scripting plugins
=> lua+python: add config keyset to open-call

src/libs/getenv/src/getenv.cpp
On powerpc architectures `__libc_start_main` has different arguments, so fix the signature for the wrapper `__libc_start_main` and the arguments passed to the real one.
=> getenv: fix wrapping on powerpc

doc/markdownlinkconverter/markdownlinkconverter.c
The return value of `fgetc` and parameter for `isblank` is `int`, not `char`.
This fixes markdownlinkconverter on architectures where `char` is unsigned (e.g. powerpc, s390, arm).
=> markdownlinkconverter: fix char/int mismatch

src/plugins/wresolver/wresolver.c
We have the own define to use for a maximum path length, so use it to build also on platforms without `PATH_MAX`.
=> wresolver: use KDB_MAX_PATH_LENGTH instead of PATH_MAX

doc/NEWS.md, doc/VERSION.md, doc/decisions/script_testing.md, doc/help/elektra-namespaces.md, doc/help/kdb-convert.md, doc/help/kdb-info.md, doc/help/kdb-test.md, doc/tutorials/plugins.md, src/plugins/augeas/README.md, src/plugins/line/README.md
- "absolut" -> "absolute"
- "allow to" -> "allow one to"
- "compatibilty" -> "compatibility"
- "diplay" -> "display"
- "infromation" -> "information"
- "lcoated" -> "located"
- "neccessary" -> "necessary"
- "supress" -> "suppress"
=> typo fixes

doc/Doxyfile
Hi,
hope this fix is helpful. If there are any problems with the pull request, please let me know. 
One thing I noticed while I tested the changes was that `cmake` also seems to produce two (useless?) directories with the names `(` and `)` inside `libelektra/doc`. Is this intentional?
Kind regards,
René
=> Fix: Generating Doxygen documentation works if build path contains spaces

src/plugins/resolver/resolver.c
makes the definition of `elektra_resolver_mutex` dependent of `ELEKTRA_LOCK_MUTEX`. See #439 for further information.
=> resolver: fix portability issue; fixes #439

src/plugins/resolver/CMakeLists.txt, src/plugins/resolver/resolver.c
as discussed in #439 I restored the manual initialization code for the recursive mutex in the resolver. The resolver compiles now under `musl-gcc` with the `ELEKTRA_LOCK_MUTEX` compile definition set.
=> resolver: restore recursive mutex init (see #439)

doc/CMakeLists.txt
From issue #438:
> You are on the right track! It won't, however, be fixed by adding an if (folder is always set). When you read about the syntax and how the `cmake` command file works, it will immediately obvious what the problem is. I will leave it to you to find out, I think fixing this bug will be a good way to learn CMake ;)
Thank you for the useful hints. Hope the description in the commit message is correct. If not, please just comment below. This pull request (hopefully) fixes issue #438.
=> CMake: Do not create directories `(` and `)` inside `doc`

src/plugins/augeas/contract.h, src/plugins/keytometa/keytometa.c, src/plugins/keytometa/testmod_keytometa.c
This PR fixes an issue with the samelevel setting of keytometa. In addition it adds the samelevel setting to the keytometa configuration shipped with the augeas plugin. The included testcase proves that the samelevel setting was not working as intended before the patch.
=> Keytometa append to samelevel fix

src/bindings/cpp/include/key.hpp
Starting with commit 330b276f `make` was not able to build Elektra on OS X any more. This commit fixes this issue. Here is a rather long list of error messages that `make` prints on my machine if I do not remove line 1668 in `key.hpp`:
```
[ 30%] Built target elektra-static
[ 30%] Building CXX object src/libs/tools/src/CMakeFiles/elektratools.dir/backends.cpp.o
In file included from libelektra/src/libs/tools/src/backend.cpp:13:
In file included from libelektra/src/libs/tools/include/backend.hpp:14:
In file included from libelektra/src/libs/tools/include/plugin.hpp:13:
In file included from libelektra/src/bindings/cpp/include/kdb.hpp:14:
libelektra/src/bindings/cpp/include/key.hpp:1672:21: error: explicit specialization of non-template struct 'hash'
template <> struct hash<kdb::Key>
^ …
```
=> Fix OS X build

README.md
I found that the first thing I read about Elektra wasn't helping me much to understand what it can do. The current message uses a lot of buzzwords, that can mean about anything.
I tried to concretely describe a few things Elektra can help with, use repetition so someone might actually remember something after having read this, and use a language that invites the reader to continue reading (similar to advertising). (I don't claim any skills that I can actually do all that, but I tried...)
What do you think?
=> doku: change the welcome message in the top of README

doc/COMPILE.md
Added a link to ronn's install instructions so it can be easily installed.
=> doku: add ronn as dependency for building the documentation

src/libs/tools/include/merging/mergeconflictstrategy.hpp, src/libs/tools/src/merging/automergestrategy.cpp, src/libs/tools/src/merging/mergeconflictstrategy.cpp, src/libs/tools/src/merging/mergeresult.cpp, src/libs/tools/src/merging/metamergestrategy.cpp, src/libs/tools/src/merging/newkeystrategy.cpp, src/libs/tools/src/merging/onesidestrategy.cpp, src/libs/tools/src/merging/onesidevaluestrategy.cpp, src/libs/tools/tests/testtool_automergestrategy.cpp, src/libs/tools/tests/testtool_newkeystrategy.cpp, src/libs/tools/tests/testtool_onesidestrategy.cpp, tests/shell/check_merge.sh
This PR should fix the problem discussed in #484 along with unit tests that verify the changed behaviour in the strategies and an extended shell merge test that verifies the behaviour on the commandline. However, there is no specific INI test for now. This is because 1. I have no example of a failed merge 2. the problem was not really INI specifc and easy to understand.
=> merge strategies now respect binary data #484

doc/NEWS.md, src/plugins/ni/README.md
Identified broken links (via `curl -f` return code):
```
doc/NEWS.md:1786  Link:http://build.libelektra.org:8080/job/elektra-gcc-configure-mingw/ - invalid
doc/NEWS.md:1055  Link:https://github.com/ElektraInitiative/libelektra/blob/master/src/libtools/examples/merging.cpp - invalid
doc/NEWS.md:1041  Link:https://github.com/ElektraInitiative/libelektra/blob/master/doc/NAMESPACES.md - invalid
```
I assume the last one should be https://github.com/ElektraInitiative/libelektra/blob/master/doc/help/elektra-namespaces.md now - for the other ones I'm not sure.
=> fix local & broken links

src/libs/tools/src/CMakeLists.txt
this fixes #495 for me
@markus2330 is this an acceptable fix? I'm not sure if you intended not to link against elektra-kdb
=> fix linking for OS X #495

src/plugins/crypto/CMakeLists.txt, src/plugins/crypto/compile_gcrypt.c, src/plugins/crypto/compile_openssl.c, src/plugins/crypto/gcrypt_operations.c
prevents OS X from accidentally compiling the crypto plugin (see #487).
=> enable OS X compilation for crypto_plugin

src/plugins/crypto/README.md
as @sanssecours noticed I mixed up the external links to Homebrew and MacPorts in the README.md file.
Thanks again for reporting!
=> crypto-plugin: fix external links in README.md

cmake/Modules/LibAddPlugin.cmake
There might be another (and better) option to fix this problem. However, this one at least works on my machine. For reference, the command
```fish
cmake ..  -DPLUGINS='dump;resolver;sync;error;spec'; and make
```
prints the following error message before this commit on OS X:
```
Undefined symbols for architecture x86_64:
"_elektraPluginExport", referenced from:
_elektraPluginSymbol in spec.c.o
"_elektraPluginGetConfig", referenced from:
_elektraSpecGet in spec.c.o
_elektraSpecSet in spec.c.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [lib/libelektra-spec.so] Error 1
make[1]: *** [src/plugins/spec/CMakeFiles/elektra-spec.dir/all] Error 2
make: *** [all] Error 2
```
=> Fix building of certain plugins on OS X

cmake/Modules/FindIconv.cmake, src/plugins/filecheck/CMakeLists.txt, src/plugins/iconv/CMakeLists.txt
=> Fixes #488 - explicitly find library iconv for iconv and filecheck plugins

src/plugins/spec/spec.c
```
kdb set spec/test/#
kdb setmeta spec/test/# array 1
kdb set /test ""
kdb set /test/#0 ""
kdb set /test/#1 ""
```
This setup caused a segfault, by fixing I added the possibility to set the range without "-".
Removed also some ELEKTRA_UNUSED
=> Allow range without "-"

src/plugins/list/CMakeLists.txt
fixes #510, however unit tests for module `list` fail on my machine (OS X):
```
src/plugins/list/testmod_list.c:43: error in doTest: kdbget failed
src/plugins/list/testmod_list.c:45: error in doTest: key not found
src/plugins/list/testmod_list.c:47: error in doTest: meta key not found
src/plugins/list/testmod_list.c:48: error in doTest: kdbset failed
testmod_list RESULTS: 12 test(s) done. 4 error(s).
```
=> fixes #510

src/plugins/crypto/README.md
I added the "discouraged" flag to the status as for now "crypto" might suggest a false sense of security. As long as there is no key derivation interface there is no way of keeping the secret stuff (cryptographic keys) secret.
=> update status of crypto-plugin

cmake/Modules/FindSystemdJournal.cmake
This could fix the warning described in #264. However, as the warning did not occur on my development machine I am not able to test it. Note also that this change might break the build for older Debian systems (which I am also not able to test)
=> Updated FindSystemdJournal CMakeModule

src/plugins/ni/ni.c
I hope this fix has no unintended consequences. What is the reason behind the decision to cut off the first  two characters if the plugin is mounted at `/`?
=> Ni Plugin: Fix elektraKeyGetRelativeName

.gitignore
This is a rather specific change. If you do not like it, then please just close this issue.
=> Ignore `Makefile` in Project Root

src/libs/elektra/keytest.c
After we apply the fix contained in ad8016d generating the PDF manual should work again. I am not totally sure if this is the format Thomas (@tom-wa) wants. By the way, it looks like the problem was introduced in commit 52db645b.
=> Fix PDF Manual Generation

src/plugins/profile/CMakeLists.txt
Before this change the build system was not able to translate Elektra on OS X.
=> Profile Plugin: Add dependency Libease

scripts/CMakeLists.txt
Currently the elektraenv.sh was added to the /etc/profile.d/ folder
as kdb without .sh extension. Distributions like Arch Linux use *.sh
globing to source all files in the /etc/profile.d/ folder and
therefore do not read the kdb file without extension.
Adding sh when renaming the file on cmake install should fix this.
=> Fix profile.d script sourcing on some distros

tests/shell/check_plugins.sh
Before this change `ctest -R testscr_check_plugins` would fail silently
if the path of the build directory contained spaces.
=> Plugin Tests: Fix Silent Failure

src/libs/tools/tests/testtool_mergingkdb.cpp
I think the order of initialization was messed up. The KDB instances were initialized before the test backend was mounted. Should fix #624.
=> Fixed the order of initialization in the kdb sync test

doc/NEWS.md
We had problems with the character `é` (small letter e + combining acute accent — code points 101 and 769) before. LaTeX – with input encoding set to `utf8` – is not able to use this character. Because of
this problem, we could not translate the reference manual. We fix this by using `é` (small letter e with acute — code point 233) instead of `é`.
Just for reference: You can determine the code points of a string by using  the function `codepoints` in Ruby:
```ruby
pry(main)> 'éé'.codepoints
=> [101, 769, 233]
```
=> Documentation: Add Accent to Name

src/plugins/ini/CMakeLists.txt
Before this change building of the plugin would fail on OS X.
=> INI Plugin: Add Dependency Libmeta

src/libs/elektra/kdb.c, src/libs/elektra/mount.c
had a typo in PRESETSTORAGE placement + forgot to initialize the globalPugins array.
=> fix typo in hook placement + uninitialized hook placements

tests/shell/check_resolver.sh
I did **not test** this change with `dash`! However the simplified code works fine in `sh` on OS X:
```sh
> TMPPATH=`cd /tmp; pwd -P`
> echo $TMPPATH
/private/tmp
```
=> Tests: Simplify Code in Resolver Check

src/tools/qt-gui/CMakeLists.txt, src/tools/qt-gui/org.elektra.elektra-qt.desktop
This commit adds a desktop file for the elektra qt gui, install target
for it in cmake as well as install target for the icon. The desktop file
still misses i18n.
=> Add install target for *.desktop file for qt-gui

doc/CMakeLists.txt
Before this change a parallel build started multiple instances of `doxygen` concurrently. Each instance of Doxygen invokes the Markdown Link Converter as filter program. Some of the Markdown Link Converter processes accessed and wrote the same files concurrently. This would cause some of them to fail, since each Markdown Link Converter assumes, that it has exclusive access to its input file.
I tested this both with `ninja` and `make -j 9`. Everything seems to work so far. Ninja builds work without the `add_dependencies` definitions added in this commit too. However, parallel invocations of `make` [do not](https://cmake.org/Bug/view.php?id=10082).
=> Build: Only Run Doxygen Once

scripts/benchmark_libsplit.sh
Should fix #530 .
Tested on FreeBSD which is:
> close to the IEEE	Std 1003.1 (``POSIX.1'')
Prints just to stdout now, instead of creating logfiles which I have used to evaluate the results in R.
=> fix libsplit benchmark: POSIX compatibility

src/include/CMakeLists.txt, src/include/kdbconfig.h.in, src/include/kdbtypes.h, src/plugins/resolver/filename.c
If you know a better solution to fix this problem, then please let me know. Here is the warning message:
```
[126/925] Building C object src/plugins/resolver/CMakeFiles/elektra-resolver_fm_ub_x-objects.dir/filename.c.o
../src/plugins/resolver/filename.c:78:84: warning: format specifies type 'long' but the argument has type '__darwin_suseconds_t' (aka 'int') [-Wformat]
snprintf (where + len, POSTFIX_SIZE - 1, ".%d:%ld.%ld.tmp", getpid (), tv.tv_sec, tv.tv_usec);
~~~                             ^~~~~~~~~~
%d
/usr/include/secure/_stdio.h:57:62: note: expanded from macro 'snprintf'
__builtin___snprintf_chk (str, len, 0, __darwin_obsz(str), __VA_ARGS__)
^~~~~~~~~~~
1 warning generated.
```
=> Resolver Plugin: Fix Compiler Warning on OS X

src/include/kdbos.h
When trying to compile a project that includes ` kdb.hpp` in a Visual Studio 2015 the ssize_t type was missing. A typedef when Visual Studio Compiler is detected should fix this.
=> Fix typedef for header inclusion in VS2015

cmake/Modules/LibAddMacros.cmake
I found a bug in cmake when setting `BUILD_DOCUMENTATION` to `OFF`.
This PR fixes it!
=> Fix cmake configure when BUILD_DOCUMENTATION is set to OFF

src/plugins/crypto/README.md, src/plugins/crypto/crypto.c, src/plugins/crypto/crypto.h, src/plugins/crypto/openssl_operations.c, src/plugins/crypto/testmod_crypto.c
In order to prevent the qt-gui from crashing (see #675 ) we disable the crypto library teardown in kdbClose() by default. In order to enable it, the key /crypto/shutdown must be set to true within the plugin configuration.
See #675 and #731 for full discussion.
@markus2330 wrote in #731 :
> Ok, then we should not cleanup by default. (Use a plugin config as done in python plugin). In the unit tests you should use cleanup to make valgrind happy.
What do you think about this solution? At least `qt-gui` should be running now, altough the memory leaks in `testmod_crypto` still occur.
=> add shutdown option to crypto plugin config

src/bindings/gsettings/CMakeLists.txt
When build as part of Elektra only install when INSTALL_SYSTEM_FILES is
enabled.
see 866eb16
=> GSettings Backend: Only install with INSTALL_SYSTEM_FILES

doc/GIT.md
build jobs killed for obvious reasons
=> doc: Add clang-asan to Jenkins trigger phrases

.travis.yml
Tests currently fail with version 1.5 of augeas from homebrew.
Using homebrews --HEAD version works as a temporary fix so PRs do not
show up broken.
ref #812
=> CI: workaround for augeas failing on OS X with homebrew

src/libs/tools/tests/testtool_backendbuilder.cpp
Fix unused paramter warnings for testtool_backendbuilder methods with
Elektras own ELEKTRA_UNUSED macro.
=> testtool: fix unused parameters with ELEKTRA_UNUSED

benchmarks/CMakeLists.txt, cmake/Modules/LibAddLib.cmake, cmake/Modules/LibAddMacros.cmake, cmake/Modules/LibAddPlugin.cmake, cmake/Modules/LibAddTest.cmake, examples/CMakeLists.txt, src/bindings/cpp/benchmarks/CMakeLists.txt, src/bindings/cpp/examples/CMakeLists.txt, src/bindings/glib/CMakeLists.txt, src/error/CMakeLists.txt, src/libs/elektra/CMakeLists.txt, src/libs/getenv/benchmarks/CMakeLists.txt, src/libs/getenv/examples/CMakeLists.txt, src/libs/getenv/src/CMakeLists.txt, src/libs/tools/benchmarks/CMakeLists.txt, src/libs/tools/examples/CMakeLists.txt, src/libs/tools/src/CMakeLists.txt, src/tools/kdb/CMakeLists.txt, src/tools/qt-gui/CMakeLists.txt, tests/CMakeLists.txt, tests/cframework/CMakeLists.txt
This commit contains the code of my second try to address issue #674:
Before this change multiple targets would generate `kdberrors.h` in parallel. Therefore it was possible that one build process would overwrite `kdberrors.h` – with exactly the same content as before – while another process was reading the file.
By the way: I think that this solution is even worse than the [first one](https://github.com/ElektraInitiative/libelektra/pull/851) I proposed 😁.
=> Build: Only Generate `kdberrors.h` Once

tests/shell/shell_recorder/shell_recorder.sh
I can swear that I changed the shebang to the sh.
I found out that when using wildcards in testcases they get expanded.
=> Shell Recorder: use sh and disable globbing

tests/shell/shell_recorder/README.md, tests/shell/shell_recorder/db_changes.esr, tests/shell/shell_recorder/shell_recorder.sh
The shell recorder tests, after commit ab772e8c, worked only because all the test outputs do not contain the `NULL` symbol.
I documented the fact that you need to use the return symbol (`⏎`) to match a newline in Shell Recorder tests.
If someone wants to know the reason why I did not choose `NULL` instead of `⏎` : Something like
```sh
echo -e "bla\0blubb" | grep -Eq --text "bla\x00blubb"
```
reports a match with BSD-grep, but not with GNU-grep. It works in GNU-grep too, if we specify the `-P` flag, which is not available in BSD's version of grep.
=> Shell Recorder: Bugfix & Documentation Update

src/bindings/intercept/README.md, src/bindings/intercept/intercept.c
```
/preload/open/~\/.vimrc =~/.vimrc-other
/preload/open/~\/.vimrc/readonly = 1
/preload/open/~\/.vimrc/generate = /other/key
/preload/open/~\/.vimrc/generate/plugin = ini
```
@markus2330 should the generated configuration be written to ~/.vimrc-other or a temporary file ?
=> intercept: generate configuration

src/bindings/intercept/intercept.c
intercept access + xstat too (needed for intercepting readUserPrefs in firefox)
=> intercept: access + xstat(64)

src/error/CMakeLists.txt
This commit should fix issue #893: “kdberrors.h not regenerated”.
=> Add Specification as Dependency of `kdberrors.h`

src/libs/elektra/kdb.c, src/plugins/conditionals/conditionals.c, src/plugins/mathcheck/mathcheck.c
Workaround for removing spec keys from the keyset passed to global plugins while keeping cascading/default keys. spec keys have to be removed because otherwise validation plugins might try to validate them and will most likely fail. 
currently there is no way to exclude cascading/default keys when using ksCut which causes problems with default keys created by plugins like `conditionals`. this workaround moves the removed keys back to the original keyset before passing it to the global plugins.
Edited!
=> Fix global hook keyset / ksCut

tests/shell/shell_recorder/shell_recorder.sh
Before this change Shell Recorder would not print newlines after it wrote a message to the protocol file. This commit fixes this regression introduced in commit 5d2232e.
The problem was that we replaced `echo -e` with `printf` but did not consider that `printf` does not print a newline at the end of a message.
This commit addresses issue #903.
@markus2330 @tom-wa: Please review my pull request.
=> Shell Recorder: Fix Broken Protocol Files

src/plugins/conditionals/conditionals.c, src/plugins/conditionals/testmod_conditionals.c
seems like the OpenBSD (and most likely FreeBSD) posix regex implementation is completely different from the linux implementation. 
=> conditionals: fix #651 *BSD regex

src/plugins/crypto/gpg.c, src/plugins/crypto/gpg.h
If the PATH environment variable is empty we check if `/usr/bin/gpg2` or `/usr/bin/gpg` is available as a fallback.
Fixes #940.
=> crypto-plugin: add /usr/bin/gpg as second fallback

scripts/configure-firefox.in, src/bindings/intercept/README.md, src/bindings/intercept/intercept.c, src/libs/getenv/README.md, src/libs/getenv/src/getenv.cpp, src/libs/getenv/tests/test_context.cpp, src/libs/getenv/tests/test_getenv.cpp
moved `open` and `getenv` configuration to `/elektra/intercept/...` (+ keep `/env` as fallback for `getenv`)
getenv: looks up `/elektra/intercept/getenv` configs first, if not found, try `/env` configs. `/elektra/intercept/getenv` is always preferred over `/env` 
=> Rename intercept config

src/error/specification, src/plugins/README.md, src/plugins/base64/CMakeLists.txt, src/plugins/base64/README.md, src/plugins/base64/base64.c, src/plugins/base64/base64.h, src/plugins/base64/contract.h, src/plugins/base64/testmod_base64.c
The Base64 Encoding (specified in [RFC4648](https://www.ietf.org/rfc/rfc4648.txt)) is used to encode arbitrary binary data to ASCII strings.
This is useful for configuration files that must contain ASCII or Unicode strings only.
The `base64` plugin encodes all binary values before `kdb set` writes the configuration to the file.
The values are decoded back to its original value after `kdb get` has read from the configuration file.
In order to identify the base64 encoded content, the values are marked with a prefix (see `README.md`).
See #897 for discussion.
=> Base64 plugin

src/libs/elektra/keyset.c
`snprintf()` was implicitly used at line 1531. 
Fixes clang compiler warning.
=> Fix missing include in keyset.c

src/plugins/crypto/botan_operations.cpp, tests/valgrind.suppression
Guard references to `Botan::SymmetricKey` and `Botan::InitializationVector` by `unique_ptr`.
This change made two valgrind suppressions obsolete. They have been removed.
=> Improve Coding Style in crypto_botan

tests/valgrind.suppression
Fixes #984.
The memory leak is a libstdc++ specific problem or a false positive generated by valgrind.
=> crypto_botan: add valgrind suppression

src/libs/tools/include/plugindatabase.hpp, src/libs/tools/src/plugindatabase.cpp
Two new functions for lib-tools that allow to lookup a whole bunch of suitable plugins (e.g. a list/map of all storage plugins). The new functions work basically the same as `PluginDatabase::lookupProvides`, except that they return all found plugins and not only the one with highest status rating.
I refactored the code of `ModulesPluginDatabase::lookupProvides` into the new function `ModulesPluginDatabase::lookupAllProvidesWithStatus`, which is used by the old and the new function.
=> lib-tools: new functions to retrieve list/map of providers

src/plugins/xmltool/kdbtools.c
This pull request fixes a compiler warning in the XMLTool plugin.
@markus2330 Please review my pull request
=> XMLTool: Fix Compiler Warning

.travis.yml
=> travis: build qt-gui, use new travis macOS images, remove unnecessary dependencies

src/plugins/csvstorage/testmod_csvstorage.c
forgot to change the parent key value after reading the file, before calling kdbSet
=> csvstorage: fixed tests overwriting testfiles + bogus testcase

src/plugins/fcrypt/CMakeLists.txt
Fix compile error on master (see #1043 ).
Closes #1043 .
=> fcrypt: fix compile error #1043

src/plugins/fcrypt/CMakeLists.txt
Remove unnecessary sources from fcrypt plugin.
Hopefully fixes all compiler and linker warnings (see #1043 ).
Remove unnesseccary dependencies (See #1043 ).
=> fcrypt: clean up CMakeLists.txt

src/plugins/enum/README.md, src/plugins/enum/enum.c, src/plugins/enum/testmod_enum.c
multienum using the old syntax
=> enum: multienum for lists

src/plugins/resolver/filename.c
fix #959
needs lots of testing.
=> resolver: drop useless / from ~-pathnames

src/plugins/fcrypt/fcrypt.c
In order to avoid name collissions with unistd.h functions encrypt() and decrypt()  functions in fcrypt.c were renamed to fcryptEncrypt and fcryptDecrypt respectively.
Fixes #1058 .
=> fcrypt: rename internal functions

src/libs/loader/CMakeLists.txt, src/libs/loader/dl.c
don't set RTLD_NODELETE when building with ENABLE_DEBUG on OpenBSD
=> ENABLE_DEBUG: no RTLD_NODELETE for OpenBSD

src/error/specification, src/plugins/fcrypt/fcrypt.c
The resolver thinks that the files were modifed externally when fcrypt overwrites them.
So we restore the original timestamps after fcrypt modified the file.
See #1050 for further details.
=> fcrypt: save timestamps of config files

src/plugins/fcrypt/testmod_fcrypt.c
As discussed in #1113 the unit tests store their test files in the TMPDIR folder if set, otherwise the files are stored in /tmp.
Closes #1113 .
=> fcrypt: write test files to TMPDIR

src/bindings/swig/ruby/tests/CMakeLists.txt, src/bindings/swig/ruby/tests/test_helper.rb, src/bindings/swig/ruby/tests/testruby_kdb.rb, src/bindings/swig/ruby/tests/testruby_key.rb, src/bindings/swig/ruby/tests/testruby_keyset.rb
Fixes #1070 
`Test::Unit::TestCase.capture_output` was called `Test::Unit::TestCase.capture_io` for versions < Ruby 2.3.0. To stay backward compatible, add an method alias when it is necessary.
=> fix Ruby test cases for Ruby < 2.3.0

src/plugins/ini/README.md, src/plugins/ini/ini.c, src/plugins/ini/testmod_ini.c
add default character for comments
=> INI: default character for comments (fix #1091)

doc/tutorials/snippet-sharing-rest-service.md, src/tools/rest-backend/CMakeLists.txt, src/tools/rest-backend/config-specification.ini.in, src/tools/rest-backend/mount-config.sh, src/tools/rest-frontend/CMakeLists.txt, src/tools/rest-frontend/mount-config.sh
This PR solves the issues in #1160.
=> snippet-sharing: fixes + tutorial improvements

src/bindings/swig/ruby/examples/ruby_example_keys.rb, src/bindings/swig/ruby/tests/testruby_key.rb
key.del_meta was not tested by the Ruby bindings test cases
I was not really sure if this works correctly, but now it is verified.
=> Ruby: add missing key.del_meta test cases

src/tools/rest-backend/config-specification.ini.in, src/tools/rest-backend/service.hpp, src/tools/rest-backend/service_config.cpp, src/tools/rest-backend/tests/test_service_configengine.cpp
Adds type checking for configuration during transformation (i.e. `key.get<type> ()` based on meta `check/type`) and configuration specification for important and usable cppcms options.
Note: I omitted irrelevant options in the specification like session or logging, because they are not used anyway.
=> rest-backend: config typecheck + cppcms conf spec

src/plugins/augeas/augeas.c
Should fix the issue with augeas crashing as described in #1187.
=> augeas: fix crash on print error

src/plugins/python2/CMakeLists.txt
- Support old versions of CMake again
- `testtool_plugindatabase`
- `testpy2_kdb.py`
- `testpy2_key.py`
- `testpy2_keyset.py`
- `test_kdb.py`
- `test_key.py`
- `test_keyset.py`
- `testruby_kdb`
- `testruby_key`
- `testruby_keyset`
failed.
=> Build: Support Older Versions of CMake

doc/CMakeLists.txt, doc/Doxyfile
This pull request should address the problem mentioned in commit 5f62893 **properly**.
👋 @markus2330: Please review my pull request.
=> Doxygen: Properly Escape Location of Markdown Link Converter

src/plugins/ini/ini.c, src/plugins/ini/ini/testCommentMeta.ini, src/plugins/ini/ini/writeCommentMeta.ini, src/plugins/ini/testmod_ini.c
don't allocate memory for empty keysets + fixed handling of special characters (`[`) in key values
allow metakeys in comments
syntax: `#@META key = value`
dropped old meta mode
=> Ini fixes + meta in comments

src/tools/qt-gui/qml/AppearanceSettingsWindow.qml
while checking, I came across a potential spelling-based bug
- width: longestText.widht
+ width: longestText.width
(occurs multiple times - not sure if this is )
found via bot: https://github.com/ka7/misspell_fixer
=> might be a bug, typo in longestText.width

src/tools/rest-backend/crypto.cpp, src/tools/rest-backend/tests/test_utils_crypto.cpp
Fixes the issue described in #1214 and adds tests for the fixes function + the password regex.
=> rest-backend: fix sha256_encrypt in crypto + tests

.travis.yml
Enable travis-ci builds for the most recent macOS version.
=> travis: bump to most recent macOS / Xcode version

doc/markdownlinkconverter/elektraSpecialCharacters.sty
Before this commit building the PDF manual would fail, since some of the included Markdown documents contain the character `⏎`. This character was not setup for use with LaTeX. We now replace the symbol `⏎` with the similar looking leftwards arrow with hook symbol (`↩︎`).
=> Documentation: Fix PDF Manual

src/plugins/spec/spec.c
in some cases spec treated spec-keys as normal keys when globbing - fixed
=> spec: ns fix

scripts/cbmc, scripts/configure-common, scripts/configure-firefox.in, scripts/draw-all-plugins, scripts/include-common, scripts/realpath, scripts/reformat-source, scripts/untidy-source
fix the issue with reformat-source not working on macOS (#1286) by detecting clang-format via which, and by providing a common include file "include-common" which provides an adjusted readlink function, as readlink -f is not available on macOS.
On macOS it tries to use greadlink, which is the same as readlink on linux given the user installed coreutils via homebrew. Otherwise i've found a shellscript which provides the required functionality to emulate at least readlink -f (we only use that at the moment, no other arguments for readlink in our scripts anywhere, so it should be good for now and avoids enforcing brewing coreutils).
@markus2330 what do you think about this approach? It fixes the issue with the script on my mac, both with coreutils brewed and without. If its okay that way, …
=> macOS-reformat-source

doc/tutorials/application-integration.md
In the course of #1176 i've checked the text via a linter (https://github.com/btford/write-good) and saw that there is probably some room for improvement regarding words which don't really add much value to a sentence like only or using too much passive form. Therefore i reworked some parts which i think can be improved.
@markus2330 do you think this way we make the tutorials easier to read? If you do I will also try to improve the other tutorials as well.
=> tutorial-improvements

scripts/include-common, tests/shell/check_formatting.sh
fix the include-common script for dash (it used some bash specific extensions while it should use posix sh instead)
@markus2330 here is the fix for #1323 . There was already a test in tests/shell/check_formatting.sh which calls the reformat-source script and thus also checks the include-common, i only fixed it to support clang-format instead of clang-format-3.8 too.
=> macOS-reformat-source: fix include-common on dash and fix test for mac

doc/help/kdb-complete.md, src/tools/kdb/cmdline.cpp, src/tools/kdb/cmdline.hpp, src/tools/kdb/complete.cpp, src/tools/kdb/complete.hpp
This PR is intended to add smaller improvements for the kdb complete tool as requested in #1296.
@sanssecours @reox Is it more usable for your use cases now?
=> kdb-complete minor improvements

src/tools/kdb/complete.cpp
Fix the infinite loop reported in #1328 . 
@markus2330 this should fix your issue, let me know if there is still something else.
=> kdb-complete: fix infinite loop with escaped key names

src/libs/elektra/keyname.c, tests/abi/testabi_key.c
Fix the bug that setting the basename of a cascading key like /cascading to NULL will also delete the namespace, so the / that marks the key as cascading.
@markus2330 IMO this is a special case that only happens when deleting a cascading key with depth 1 (so something like /cascading) as the setBaseName method simply strips everything up to including the last / character.
For everything with a namespace this is fine (e.g. user/key gets stripped to user), but for a cascading namespace, the last / has to be preserved. This only seems to be relevant upon basename deletion, therefore i've put the appropriate adjustment in the if branch. Also added unit tests for such cases.
=> Fix kdb set base name

scripts/ffconfig/setupConfig, scripts/ffconfig/setupHomepage, scripts/ffconfig/setupProxy, scripts/ffconfig/writeConfigFiles, tests/shell/check_bashisms.sh
Add bashisms regression check test as requested in #160 
@markus2330 please review my pull request. checkbashisms will return 0 on success and 2 on a skipped file (e.g. it skips files which have a shebang pointing to awk). Therefore i handle 2 also as successful, as there is no real way to determine if skipping the file is ok (as it usually is) or not (e.g. cannot read file for whatsoever reason).
We might have to install the tool on the build server, otherwise it will skip the check.
=> bashisms-test

tests/shell/check_meta.sh
check metadata consistency (#1355)
```
% ./check_meta.sh
ELEKTRA PLUGIN METATADA CONSISTENCY CHECK
error: order should be used by augeas, but not present in augeas/README.md infos/metadata
error: Metadata assign/condition of plugin conditionals not present in METADATA.ini
error: Metadata condition/validsuffix of plugin conditionals not present in METADATA.ini
error: Metadata check/condition/# of plugin conditionals not present in METADATA.ini
error: Metadata assign/condition/# of plugin conditionals not present in METADATA.ini
error: Metadata check/date of plugin date not present in METADATA.ini
error: Metadata check/date/format of plugin date not present in METADATA.ini
error: Metadata check/enum/# of plugin enum not present in METADATA.ini
error: Metadata check/enum/multi of plugin enum …
```
=> check_meta.sh

doc/COMPILE.md, doc/news/2014-06-21_0.8.6.md, doc/old/NEWS.md, doc/tutorials/namespaces.md, src/bindings/README.md, src/bindings/swig/ruby/examples/ruby_example_application.rb, src/bindings/swig/ruby/tests/testruby_kdb.rb, src/plugins/mozprefs/README.md, src/plugins/mozprefs/autoconfig/README.md, src/plugins/ni/README.md, src/tools/rest-backend/README.md, src/tools/rest-frontend/README.md, tests/shell/check_meta.sh
This pull request should fix the false positive reported by `check_meta.sh` (see issue #1381).
=> Check Meta: Properly Match Plugin Name

src/plugins/crypto/README.md, src/plugins/crypto/gpg.c
If /gpg/key is not provided in the plugin configuration a list of available GPG key IDs is shown in the error description.
Fixes #895 .
=> crypto: Display available GPG keys if config option is missing.

doc/help/kdb-rmmeta.md, src/tools/kdb/factory.hpp, src/tools/kdb/metaremove.cpp, src/tools/kdb/metaremove.hpp
Add the missing command rmmeta to remove a metakey of a key.
I'm using this in the my puppet module for the `kdb` provider (fallback implementation if ruby bindings aren't available/usable)
=> tools kdb: add new command rmmeta

src/plugins/crypto/openssl_operations.c
Mixing `size_t` and `kdb_unsigned_long_t` resulted in corrupted header interpretations between encryption and decryption when using crypto_openssl.
Fixes #1389 .
=> crypto: fix type inconsistency in crypto_openssl

src/plugins/crypto/gpg.c, src/plugins/crypto/gpg.h, src/plugins/fcrypt/README.md, src/plugins/fcrypt/fcrypt.c
Fixes for
- #1392 display available GPG keys
- #1358 Mac OS compile error
=> Fcrypt Improvements

src/plugins/ini/ini.c
fix memleak and keep comments following the last key in the ini file
=> INI: fix handling of last comments

src/bindings/swig/ruby/CMakeLists.txt, src/bindings/swig/ruby/README.md, src/bindings/swig/ruby/examples/tools/kdb_simple.rb, src/bindings/swig/ruby/kdbtools.i, src/bindings/swig/ruby/kdbtools.rb, src/bindings/swig/ruby/tests/testruby_tools_backendbuilder.rb, src/bindings/swig/ruby/tests/testruby_tools_backendparser.rb, src/bindings/swig/ruby/tests/testruby_tools_modules.rb, src/bindings/swig/ruby/tests/testruby_tools_plugindatabase.rb, src/bindings/swig/ruby/tests/testruby_tools_pluginspec.rb, src/bindings/swig/ruby/tests/testruby_tools_specreader.rb, src/libs/tools/include/backend.hpp, src/libs/tools/include/backendbuilder.hpp, src/libs/tools/include/plugindatabase.hpp, src/libs/tools/include/pluginspec.hpp, src/libs/tools/include/toolexcept.hpp, src/libs/tools/src/backend.cpp
Ruby bindings for libtools, extends existing bindings (same src tree, same build but different Ruby module)
@markus2330 final version
=> Ruby Libtool bindings

src/bindings/swig/ruby/CMakeLists.txt, src/bindings/swig/ruby/README.md
We require at least 3.0.8 because of shared pointer feature for Ruby
bindings generator.
=> ruby bindings: check for min siwg 3.0.8 version

src/error/specification, src/plugins/simpleini/CMakeLists.txt, src/plugins/simpleini/README.md, src/plugins/simpleini/simpleini.c, src/plugins/simpleini/testmod_simpleini.c
Build a more robust scanf format specifier out of the given 'format'
config setting. This allows formats like "%=%".
Additionally, this fixes a mem corruption vulnerability, due to unsafe
scanf format pattern.
=> simpleini: make 'format' param more robust

src/plugins/crypto/compile_openssl.c, src/plugins/crypto/crypto.h, src/plugins/crypto/openssl_operations.c
crypto: fix OpenSSL compile errors for Debian Stretch
See #1437 for full discussion.
=> crypto: fix OpenSSL compile errors for Debian Stretch

scripts/CMakeLists.txt
Fixes installation directories for shell completions on macOS, similar like it was already done for the zsh completions. The /usr/share folder is protected in macOS.
=> fix-macOS-completions-installation

src/tools/web/client/src/actions/clusters.js, src/tools/web/client/src/actions/instances.js, src/tools/web/client/src/actions/kdb.js, src/tools/web/client/src/actions/router.js, src/tools/web/client/src/actions/utils.js
Fixes #1424
The problem was that the `fetch()` requests in the app did not send the `Authorization` header, thus nginx rejected the requests. This was fixed by adding `{ credentials: 'same-origin' }` to the fetch options, as suggested in: https://bugs.chromium.org/p/chromium/issues/detail?id=504344
This PR also shows invalid server responses as "Error: invalid response from server" instead of showing the JSON error.
=> fix for running elektra-web with nginx reverse proxy and PAM auth

src/plugins/xerces/serializer.cpp, src/plugins/xerces/util.hpp
Use UTF-8 instead of the system locale for the xerces plugin to avoid problems if the locale is set to POSIX or something similar when trying to parse xml files with special characters.
WIP to see if it works
=> Fix xerces plugin locale

src/tools/qt-gui/qt-gui.pro, src/tools/qt-gui/src/confignode.cpp
Fix crash in issue #234 by handling uncaught exception. Adding qt-gui.pro file to enable people building the tool with qmake/qt-creator.
=> Fix crash #234, add qt-gui.pro to build the tool with qmake

doc/CODING.md, doc/help/elektra-algorithm.md, doc/tutorials/plugins.md, src/include/kdbplugin.h, src/include/kdbprivate.h, src/libs/elektra/kdb.c, src/plugins/doc/doc.h, src/plugins/rename/README.md, src/plugins/resolver/resolver.c, src/plugins/template/template.c, src/plugins/template/testmod_template.c
This pull request adds the following macros for the return values of plugin functions:
- `ELEKTRA_PLUGIN_STATUS_ERROR`: An error occurred inside the plugin function
- `ELEKTRA_PLUGIN_STATUS_SUCCESS`: Everything went fine and the function **did not** change the given keyset
- `ELEKTRA_PLUGIN_STATUS_SUCCESS_KEYSET_MODIFIED`: Everything went fine and the function did modify the given keyset
.
=> Plugins: Add Status Values for Plugin Functions

.travis.yml
I recently noticed that Travis does not build and test experimental plugins anymore. Since (as far as I can tell) all supported experimental plugins should work on macOS, this pull request enables them again.
=> Travis: Also Test Experimental Plugins

cmake/Modules/LibAddMacros.cmake, doc/help/CMakeLists.txt
This commit should finally fix the issue mentioned in commit 214898ed:
> Before this change building the man pages would not work if the current locale only allowed ASCII characters. This commit addresses issue #1406.
. The problem with the old fix was that CMake only sets environment variables at configuration time. Now the encoding is properly set at execution time, just before `ronn` generates the man pages.
This fix will only work on Unix like systems though. We could use `cmake -E env` instead  of `export` to address this problem. However, as  far as I can tell, `cmake -E env` is [only available since CMake 3.2](http://stackoverflow.com/questions/35029277/how-to-modify-environment-variables-passed-to-custom-cmake-target#35032051).
=> Ronn: Use UTF-8 as Input Encoding

src/libs/utility/text.c
Before this change Elektra would not compile on MinGW, since `stpncpy` is not part of the ISO C standard.
=> Utility: Use Standard C String Copy Function

src/bindings/swig/ruby/kdbtools.i
To allow better plugin handling with puppet-libelektra (kdbmount), we have to check which plugins a Backend actually resolves. This PR addes a `to_add` getter method to `Kdbtools::MountBackendBuilder` to allow to query the actually used plugins by the Backend. The C++ API has iterator methods for this, but these are excluded by the Ruby bindings.
=> ruby kdbtools: MountBackendBuilder.to_add getter + missing exception

.travis.yml, doc/help/kdb-complete.md, doc/tutorials/cascading.md, src/plugins/conditionals/README.md, src/plugins/hosts/README.md, src/plugins/mini/README.md, src/plugins/template/template.c, src/plugins/xerces/README.md, tests/shell/shell_recorder/common.sh, tests/shell/shell_recorder/profiletest.esr, tests/shell/shell_recorder/tutorial_wrapper/markdown_shell_recorder.sh
This pull request fixes minor problems concerning (Markdown) Shell Recorder tests, including the issues below.
1. All Markdown Shell Recorder (MSR) tests  should now properly clean up modifications to the database.
2. The MSR now tests output following `STDOUT-REGEX:` properly.
3. Markdown Shell Recorder tests now supports whitespace after directives such as `RET:` or `STDOUT-REGEX:`.
=> (Markdown) Shell Recorder: Minor Improvements

src/plugins/crypto/botan_operations.cpp, src/plugins/crypto/botan_operations.h, src/plugins/crypto/crypto.c, src/plugins/crypto/gcrypt_operations.c, src/plugins/crypto/gcrypt_operations.h, src/plugins/crypto/openssl_operations.c, src/plugins/crypto/openssl_operations.h
Instead of reading the master password for every Key in a KeySet during en/decryption we now read and decrypt the master password once for the whole KeySet. 
See #1493 for full discussion.
=> crypto: improve plugin performance

src/plugins/spec/spec.c
let the spec plugin create default keys
=> spec: also create default keys

src/libs/tools/benchmarks/benchmark_crypto_comparison.cpp
I added a benchmark that compares the runtime of the different plugin variants.
It tunrs out that the current crypto implementation has a performance flaw. I will open a new issue for this.
=> crypto: add benchmark

src/plugins/crypto/contract.h, src/plugins/crypto/crypto.c, src/plugins/crypto/crypto.h, src/plugins/crypto/test_internals.h
- remove unsued `error()` function from plugin exports
- fix several doxygen comments
=> crypto: code cleanup and documentation fixes

LICENSE.md
Before this change [Licensee][] was unable to determine the correct license for this repository.
[Licensee]: http://ben.balter.com/licensee
=> Documentation: Fix GitHub License Detection

src/error/specification, src/plugins/fcrypt/README.md, src/plugins/fcrypt/fcrypt.c, src/plugins/fcrypt/testmod_fcrypt.c
Enable sign/verify operation for `fcrypt`.
See `README.md` to find out how it is supposed to work.
See #1009 for full discussion. Closes #1009 .
=> fcrypt: add sign/verify feature

scripts/cbmc, src/libs/ease/array.c, src/libs/ease/keyname.c, src/libs/elektra/keyvalue.c, src/plugins/ini/ini.c, src/plugins/range/range.c, src/plugins/range/testmod_range.c, src/plugins/xerces/README.md, src/plugins/xerces/serializer.cpp, tests/abi/testabi_ks.c, tests/ctest/test_keyname.c
A bunch of small quality improvements.
@markus2330 some considerations:
ASAN: I've had two places it complained about during the tests. one was in the range.c file (see changed files), but as it only gets multiplied by 1 or -1 it should not matter. i've added an assertion to guarantee that. it still complains though, doesn't seem to get the assertion
The other place it complains about is in keyvalue.c  on line 541 (`memcpy (key->data.v, newBinary, key->dataSize);`). The exact error is
```
95: ==63583==ERROR: AddressSanitizer: global-buffer-overflow on address 0x00010a8aa749 at pc 0x00010a9da1e8 bp 0x7fff553cc500 sp 0x7fff553cbcb0
95: READ of size 10 at 0x00010a8aa749 thread T0
95: …
```
=> Quality improvements

doc/TESTING.md, doc/markdownlinkconverter/markdownlinkconverter.c, src/include/kdbassert.h, src/libs/elektra/internal.c, src/libs/elektra/keyset.c, src/libs/elektra/keytest.c, src/libs/meta/meta.c, src/plugins/conditionals/conditionals.c, src/plugins/ini/ini.c, src/plugins/ini/inih-r29/inih.c, src/plugins/line/testgetline.c, src/plugins/lineendings/lineendings.c, src/plugins/list/list.c, src/plugins/mathcheck/mathcheck.c, src/plugins/resolver/testmod_resolver.c, src/plugins/uname/testuname.c, src/plugins/validation/lookupre.c, src/plugins/xmltool/kdbtools.c, tests/abi/testabi_ks.c, tests/cframework/tests.c, tests/ctest/test_internal.c, tests/ctest/test_mount.c, tests/ctest/test_mountsplit.c, tests/ctest/test_opmphm_init.c, tests/ctest/test_splitget.c, tests/ctest/test_splitset.c, tests/ctest/test_trie.c
Fix issues reported by static code checkers
@markus2330 most of the issues have been minor things like unnecessary dead stores which i've removed, but there were also some possible null dereferences and obvious mistakes in some tests. If you find a change too drastic i can also just make it ignore some of the dead stores instead of removing them.
Furthermore i've made scan-build aware of our ELEKTRA_ASSERT to avoid some false positives and improved the documentation.
The only 4 reports left are in python.cpp of the python bindings, where it is not aware that SWIG_NewPointerObj takes care about freeing the allocated memory. I can supress the warnings though that requires some defines around the affected code. Is it even necessary?
=> Static code checker fixes

.oclint, doc/decisions/validation.md, doc/tutorials/validation.md, src/error/specification, src/include/kdbassert.h, src/plugins/README.md, src/plugins/file/file.c, src/plugins/mini/mini.c, src/plugins/yaml/CMakeLists.txt, src/plugins/yaml/README.md, src/plugins/yaml/testmod_yaml.c, src/plugins/yaml/yaml.c, src/plugins/yaml/yaml.h, src/plugins/yaml/yaml/simple.yaml, src/plugins/yaml/yaml/yaml.abnf, tests/shell/shell_recorder/tutorial_wrapper/CMakeLists.txt
This pull request adds a **very basic** YAML plugin. I wrote the parsing code myself, since I wanted to learn how to “properly” write a recursive descent parser. While the code should not be too hard to extend (see commit commit 17aa7a6 for an example), I do not think that it makes sense to continue with the development of this parser, since it currently has multiple issues that I listed below.
- **No Scanner:**  While I prefer a scanner-less parser (no distinction between lexing and parsing), this decision might be problematic. I assume that some advanced YAML features require a lookahead of one symbol and a one character (byte) lookahead is not enough. 
- **Ignores Whitespace:** This is problematic since YAML’s block style uses additional leading spaces to denote child nodes.
- **Error …
=> YAML Plugin: First Version

.travis.yml, doc/old/NEWS.md, src/bindings/cpp/examples/cpp_example_ordering.cpp, src/libs/elektra/key.c, tests/CMakeLists.txt
Currently the output of `ninja run_all` is buffered. Consequently we do not see which sub-command causes problems if we terminated the script before it finishes. This behaviour is especially problematic, if Travis kills the script cause it runs for too long.
=> Run All: Use Non-Buffered Output

doc/help/kdb-global-umount.md, src/plugins/conditionals/README.md, src/tools/kdb/factory.hpp, src/tools/kdb/globalumount.cpp, src/tools/kdb/globalumount.hpp, tests/shell/shell_recorder/tutorial_wrapper/CMakeLists.txt
Adds global-umount tool
@markus2330 Honestly this bugged me quite a lot because to me it seems to be too easy the way it currently is. So i was trying to find out what i'm missing. But judging from the kdb tools library (which is not really easy to understand imo) it seems that global plugins are always mounted to this particular path and just removing the keys from there seems to be sufficient. There is no need to reorder the array of global plugins or anything as the next time you mount a new global plugin, the mounting code reorders it anyway.
But shouldn't global plugins also have an entry in system/elektra/modules so i could call their corresponding close function before or is that not necessary?
=> kdb-global-umount: first draft #1290

src/include/kdbassert.h, src/include/kdbmacros.h, src/plugins/file/file.c, src/plugins/mini/mini.c, src/plugins/yaml/yaml.c
This pull request adds two simple macros:
- `ELEKTRA_NOT_NULL` and
- `ELEKTRA_MALLOC_ERROR`
.
=> Macros: Add `ELEKTRA_NOT_NULL` and `ELEKTRA_MALLOC_ERROR`

src/error/specification, src/plugins/crypto/botan_operations.cpp, src/plugins/crypto/crypto.c, src/plugins/crypto/crypto.h, src/plugins/crypto/gcrypt_operations.c, src/plugins/crypto/helper.c, src/plugins/crypto/openssl_operations.c
The `crypto` plugin adds a magic number and version hint about the version of the payload.
The prefix is `#!crypto00` where `00` refers to the version.
The version is defined in `crypto.h`.
Closes #1575 .
=> crypto: introduce payload version

.travis.yml, CMakeLists.txt
This update adds a basic Linux build for Travis. While we already [test multiple variations of Elektra on Linux](https://build.libelektra.org/jenkins), adding an additional build still has some merits:
1. Travis also [tests updates on forks](https://travis-ci.org/sanssecours/libelektra) of this repo
2. Since Travis uses Ubuntu instead of Debian there might be slight differences in the OS, which allow us to [discover new problems](https://github.com/ElektraInitiative/libelektra/issues/1579)
3. Travis still works if someone [compromises the build server](https://github.com/ElektraInitiative/libelektra/issues/1505)
.
=> Travis: Add Basic Linux Build

src/plugins/fcrypt/README.md, src/plugins/fcrypt/contract.h, src/plugins/fcrypt/fcrypt.c, src/plugins/fcrypt/fcrypt.h
Introduce the configuration option `fcrypt/tmpdir` to `fcrypt`.
`fcrypt` uses the given path to redirect GPG output to.
The default value is `/tmp`.
Closes #1567 .
=> fcrypt: tmpdir configuration option

.travis.yml, src/plugins/ini/README.md
This pull request adds additional Travis build jobs:
- Clang on Linux
- GCC on macOS
. I disabled `crypto_botan` in the build job that uses GCC on macOS, since linking the plugin produces the following [error message](https://travis-ci.org/sanssecours/libelektra/jobs/269100889#L2338):
```
Undefined symbols for architecture x86_64:
"Botan::get_cipher(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, Botan::OctetString const&, Botan::OctetString const&, Botan::Cipher_Dir)", referenced from:
_elektraCryptoBotanDecrypt in botan_operations.cpp.o
_elektraCryptoBotanEncrypt in botan_operations.cpp.o
"Botan::Pipe::read_all_as_string[abi:cxx11](unsigned long)", referenced from:
_elektraCryptoBotanDecrypt in botan_operations.cpp.o …
```
=> Travis: Test Additional Setups

src/plugins/crypto/botan_operations.cpp, src/plugins/crypto/gpg.c, src/plugins/fcrypt/fcrypt.c
Fix compiler warnings from #1579 in the `crypto` and `fcrypt` plugin.
=> Fix compiler warnings (#1579 )

src/tools/rest-backend/service_convert.cpp
Instance var m_pluginProviderStorage is a `std::string`, therefore the method `length()` should be used for the string length
fixes issue #1636 
=> rest-backend: fix wrong usage of sizeof

src/libs/tools/src/specreader.cpp
Fixes issue #1633
Don't know if this patch may be considered to be an ugly patch, also I didn't find a nicer way to filter spec keys. However, this filters out all non-spec keys (in that case all cascading) before we try to parse the specification and build the backend.
=> specreader: ignore non-spec keys

src/tools/rest-backend/config-specification.ini.in
The boolean plugin does not canonicalize boolean values here, since it
uses 'type' instead of 'check/type' meta key.
The type plugin requires integer values for boolean types.
So for a quick fix, provide valid defaults.
I wonder if this ever worked ...
=> restbackend: spec use 0/1 for booleans

tests/shell/check_gen.sh
This fixes a problem where `check_gen` would fail if [Cheetah](http://cheetahtemplate.org) is not installed.
=> Tests: Check Availability of Cheetah

cmake/Modules/LibAddHaskellPlugin.cmake, src/bindings/haskell/CMakeLists.txt, src/bindings/haskell/README.md, src/bindings/haskell/libelektra-haskell.cabal.in, src/bindings/jna/CMakeLists.txt, src/plugins/haskell/CMakeLists.txt, src/plugins/haskell/haskell.cabal.in, src/plugins/haskell/testmod_haskell.c
(Hopefully) allows the haskell tests to work even if elektra has only been built but not installed yet. Also recognized changes on the haskell binding source files so ninja recompiles it correctly.
@sanssecours lets see if this also works on travis now, seems fine locally but maybe i had some leftovers that make it work although it shouldn't (did clean the build directory though)
=> haskell-bindings-fix-tests

scripts/build-homepage
Do we really want to run the backend service as an ASAN build? It already crashed two times because of that.
Remove installed libraries before installing the new one. This way we ensure there are no old unwanted plugins that might cause problems.
Ensure rest-backend is started in daemon mode, otherwise the script will be blocked.
=> build-homepage: late fixes

src/tools/rest-frontend/build.sh
The Backend throws an excpetion if 'database' endpoint is called without
a 'sortBy' field. Therefore the backend returns with HTTP 500 which
aborts the frontend build process.
For now, we simply force the frontend build to be not blocked by this
minor issue.
=> build-homepage: build frontend with --force

src/plugins/xerces/testmod_xerces.c
Fixes #1666 and also fixes a memleak in the tests caused by a kdbOpen without a corresponding kdbClose.
@markus2330 
However there is still one little leak left, that again rather looks like some system issue to me and not caused by the xerces plugin, what do you think:
```
==8670==
==8670== HEAP SUMMARY:
==8670==     in use at exit: 32 bytes in 1 blocks
==8670==   total heap usage: 64,262 allocs, 64,261 frees, 7,765,932 bytes allocated
==8670==
==8670== 32 bytes in 1 blocks are still reachable in loss record 1 of 1
==8670==    at 0x4C31B25: calloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==8670==    by 0x70E082E: _dlerror_run (dlerror.c:141)
==8670==    by 0x70E0091: …
```
=> fix-xerces-installed-tests

cmake/Modules/FindHaskell.cmake, cmake/Modules/LibAddHaskellPlugin.cmake, src/bindings/haskell/CMakeLists.txt, src/bindings/haskell/README.md, src/bindings/haskell/libelektra-haskell.cabal.in
Improves the dependency management of the haskell bindings mentioned in #1670 . The readme is also more precise about the dependencies now.
@markus2330 There is one little issue left. If one dependency is missing, and it excludes the bindings, then the haskell plugin will fail later on. This is because for what i've seen the plugins get configured first, so the bindings are still included and thus the haskell plugin is happy. But then it configures the bindings, notices some lib is missing and excludes the bindings. Thus then in the later phases the haskell plugin fails because it depends on a target added by the bindings, which obviously is missing now. 
We currently don't have a simple mechanism to handle such cases, do we? Anyway its probably not the biggest deal as the user will see …
=> Haskell bindings check dependencies

src/bindings/haskell/README.md
As you can see only a very minor thing, had the links used in the bindings readme wrong. Should be fine to merge, only changes docu and i tried it in my fork already it works now.
@markus2330 please merge. Can i push such simple changes directly to master in the future?
=> haskell-bindings-fix-readme-links: correct relative and absolute links

src/plugins/ruby/CMakeLists.txt
This pull request disables the Ruby plugin on GCC 4.x and earlier. At least GCC 4.7 is [unable to compile](https://build.libelektra.org/jenkins/job/elektra-gcc47-all/1127/console) the plugin:
```
src/plugins/ruby/ruby.cpp: In function 'VALUE get_exception_string(VALUE)':
src/plugins/ruby/ruby.cpp:98:42: error: expected ')' before 'PRIsVALUE'
src/plugins/ruby/ruby.cpp:99:17: warning: spurious trailing '%' in format [-Wformat]
src/plugins/ruby/ruby.cpp:99:17: warning: too many arguments for format [-Wformat-extra-args]
src/plugins/ruby/ruby.cpp:103:42: error: expected ')' before 'PRIsVALUE'
src/plugins/ruby/ruby.cpp:103:100: warning: spurious trailing '%' in format [-Wformat]
src/plugins/ruby/ruby.cpp:103:100: warning: too many arguments for format [-Wformat-extra-args] …
```
=> Ruby: Disable Plugin on GCC 4

src/libs/tools/src/backendparser.cpp
Signed-off-by: Nick Sarnie <commendsarnex@gmail.com>
bind lives in "functional"
http://www.cplusplus.com/reference/functional/bind/
=> Properly include headers for std::bind

doc/tutorials/validation.md, src/plugins/directoryvalue/README.md, tests/shell/shell_recorder/CMakeLists.txt, tests/shell/shell_recorder/shell_recorder.sh
The Shell Recorder now uses `kdb-full` or `kdb-static` if `kdb` is unavailable. This update should hopefully fix the problems of the build job [`elektra-multiconfig-gcc47-cmake-options`](https://build.libelektra.org/job/elektra-multiconfig-gcc47-cmake-options).
=> Shell Recorder: Use Full or Static Version of `kdb`

doc/help/kdb.md, doc/man/kdb.1, src/tools/kdb/cmdline.cpp, src/tools/kdb/external.cpp
When KDB is severely broken (e.g. KDB.get does not work) currently the kdb tool always emits errors when trying to read its own configuration.
This is a proposal to add the profile "nokdb" which allows to not use KDB for the configuration of the kdb-tool. (Of course the main actions of `kdb` still use KDB.)
- This idea might be a misfeature (to give profiles a semantics), so I thought it would be good to discuss it first.
- The formatting is not really nice.
TODO:
=> kdb: proposal for nokdb profile

doc/docker/Dockerfile, doc/docker/README.md, doc/docker/buildelektra.sh
Install and option to compile with `clang` in the Docker container.
Also extended the build script `buildelektra.sh` with new options:
- `j` for setting number of parallel make recipes/jobs
- `c` for setting the clang version to use
- `D` for setting cmake parameters
=> Docker: add clang

cmake/ElektraCompiling.cmake, doc/man/elektra-merge-strategy.7, doc/man/kdb-mount.1, scripts/run_asan, src/include/kdbprivate.h, src/libs/tools/src/plugin.cpp, tests/sanitizer.blacklist, tests/shell/shell_recorder/CMakeLists.txt, tests/shell/shell_recorder/selftest.esr, tests/shell/shell_recorder/tutorial_wrapper/CMakeLists.txt
This PR simplifies the build process by using a blacklist to ignore sanitizer problems in `libstdc++`. Before this update we would explicitly disable tests, that reported problems in `libstdc++`.
=> Sanitizer: Ignore Issues in Old Versions of `libstdc++`

.travis.yml
This commit should fix the problem reported in issue #1764.
=> Travis: Always Consider Exit Status of `run_all`

cmake/ElektraCache.cmake, doc/news/_preparation_next_release.md, scripts/configure-mingw-w64, scripts/configure-xdg, src/plugins/dini/README.md, src/plugins/ini/ini.c
Change default storage plugin to dini
=> cmake: use dini as default

doc/API.md, doc/INSTALL.md, doc/dev/algorithm.md, doc/docker/buildelektra.sh, doc/help/elektra-bootstrapping.md, doc/man/elektra-bootstrapping.7, doc/news/_preparation_next_release.md, scripts/sed, src/plugins/semlock/README.md
This PR adds information about the new Homebrew formula for Elektra in [`homebrew-core`](https://github.com/Homebrew/homebrew-core/blob/master/Formula/elektra.rb).
=> Install: Add Information About New Homebrew Formula

cmake/Modules/FindPluginprocess.cmake, doc/news/_preparation_next_release.md, src/error/specification, src/include/CMakeLists.txt, src/include/kdbpluginprocess.h, src/libs/CMakeLists.txt, src/libs/README.md, src/libs/pluginprocess/CMakeLists.txt, src/libs/pluginprocess/pluginprocess.c
This adds a library that allows plugins to be executed in a child process to workaround the global initialization issue described in #1768. 
It uses fork with a simple communication protocol based on elektra itself, invoking the dump plugin to let a plugin communicate with its child process via named pipes (as the dump plugin expects a file as the input argument to serialize from/to) using a few extra keys which indicate which plugin function to execute and what was the original key for plugin function calls.
@markus2330 One more puzzle piece towards the typechecker. Actually, I have already used this library for it and indeed my reinitialization issues are now gone with it. I will make a separate PR which uses this for haskell plugins though to keep the PRs smaller (then you also see how …
=> pluginprocess

cmake/Modules/LibAddHaskellPlugin.cmake, src/bindings/haskell/src/Elektra/Plugin.chs, src/include/kdbpluginprocess.h, src/libs/pluginprocess/pluginprocess.c, src/plugins/haskell/Elektra/Haskell.hs, src/plugins/haskell/haskell.c.in, src/plugins/haskell/haskell.h.in
Executes Haskell Plugins in a separate process with libprocessplugin. As haskell plugins do not really work otherwise its directly integrated and not proxied via process, so it can be mounted directly also.
@markus2330 and the last big prerequisite for the typechecker prototype.. on macs ;) i'll fix the setup.hs issue in a separate pr.
=> Haskell pluginprocess

src/tools/rest-frontend/package.json
Due to a wont-fix vulnerability in jquery v2.x.x, it is necessary to update to jquery v3.x.x. For more details see #1786.
=> increment jquery version in package.json

tests/shell/check_kdb_internal_check.sh
`check_kdb_internal_check.sh` checks all added plugins and does not care about excluded testcases,
therefore `semlock` could fail and should be removed till fixed properly.
=> Tests: Shell: kdb_internal_check exclude semlock

tests/shell/shell_recorder/shell_recorder.sh
Fix a syntax error in the Shell Recorder script
=> Shell Recorder: Fix Syntax Error

doc/news/_preparation_next_release.md, src/include/kdbinvoke.h, src/include/kdbpluginprocess.h, src/libs/invoke/invoke.c, src/libs/pluginprocess/pluginprocess.c, src/plugins/blockresolver/blockresolver.c, src/plugins/curlget/curlget.c, src/plugins/dini/dini.c, src/plugins/gitresolver/gitresolver.c, src/plugins/haskell/haskell.c.in, src/plugins/multifile/multifile.c
Adds the possibility for the invoke library to report errors when trying to open/close a plugin as discussed in #1795 .
@markus2330 As C doesn't support overloaded functions, i've adjusted the original interface now as its not a part of the core elektra library as far as i've understood because i think the function names fit pretty well. I've also adapted those few plugins using it already, but for those i am passing simply 0 as the error key so invoke will take care about the error key creation itself, which basically is the old behavior to avoid possibly breaking anything in plugins i do not maintain. For my own plugins i've incorporated the new error key already (and even had to do a small pluginprocess library adjustment.
=> Invoke error key

cmake/Modules/Findyaml-cpp.cmake, doc/news/_preparation_next_release.md, src/plugins/yamlcpp/CMakeLists.txt
Do not require [Boost](http://www.boost.org) for the YAML CPP plugin anymore, if CMake locates yaml-cpp 0.6 or newer.
=> YAML CPP: Update CMake Code for yaml-cpp 0.6

src/tools/kdb/complete.cpp
There is a potential issue reported by asan, find will return str:npos if it is not found, which corresponds to -1 unsigned so the highest number, which can cause an overflow in the equality check then as this offset is added to the pointer.
@sanssecours on my machine it looks better now
=> fix-kdb-complete-heap-overflow

tests/shell/check_distribution.sh
fixes the concurrency issue when running multiple tests simultaneously by using mktemp instead of a fixed filename.
@markus2330 hopefully it was a simple fix, lets see what build all thinks
=> fix-check-distribution-concurrency

src/libs/invoke/invoke.c
I noticed keyDel doesn't decrease the refcount but assumed that for the error key for invoke functions, so i corrected this to get the correct behavior.
@markus2330 a quick fix, looks like you were happy with my assumption that keyDel decreases the refcount too :D i'll just merge it once the build passes
=> invoke-error-key-fix

doc/docker/jenkinsnode/Dockerfile, doc/docker/jenkinsnode/README.md, doc/docker/jenkinsnode/run-make, doc/docker/jenkinsnode/run-make-env, doc/docker/jenkinsnode/run-nice, doc/news/_preparation_next_release.md
Add Dockerfile, Readme and scripts for a jenkins build node with docker
@markus2330 There you go. I document the ssh setup for the v2 in our build server issue, as that has nothing to do with the build container in general.
=> docker-jenkins-buildnode

.travis.yml, cmake/ElektraCompiling.cmake, src/plugins/yamlcpp/CMakeLists.txt
This PR
- adds a Linux build job for an ASAN enabled GCC build, and
- removes some unneeded CMake code for the ASAN build.
=> Travis: Add ASAN Enabled GCC Build for Linux

doc/news/_preparation_next_release.md, tests/shell/shell_recorder/tutorial_wrapper/markdown_shell_recorder.sh
After this PR the Markdown Shell Recorder prints the location of the current test file.
=> Markdown Shell Recorder: Print Path to Test File

.travis.yml
Currently the Haskell build job does not build the Haskell bindings and the Haskell plugin anymore. This pull request should fix this problem.
=> Travis: Fix Haskell Build Job

tests/valgrind.suppression
For #1871: Add additional valgrind supression rules for leaking global state in glib 2.42 on Debian Jessie.
=> "io-glib" binding: add supression rules for glib 2.42

src/tools/kdb/test.cpp
Fix formatting inconsistency with clang-format on macOS (travis).
e.g. https://travis-ci.org/ElektraInitiative/libelektra/jobs/360580895
=> travis: fix for formatting issue on macOS

Jenkinsfile.daily, doc/news/_preparation_next_release.md, scripts/jenkins/Jenkinsfile.daily
Add the [existing pipeline](https://build.libelektra.org/jenkins/job/elektra-jenkinsfile-daily/) to VCS for better maintanence.
=> Add Jenkinsfile.daily

tests/cframework/tests.c
=> tests: remove clearenv in tests

.travis.yml, doc/news/_preparation_next_release.md, src/plugins/xerces/CMakeLists.txt
After this PR CMake disables the Xerces plugin on ASAN enabled GCC builds.
=> Xerces: Remove Plugin on ASAN Enabled GCC Build

cmake/Modules/LibAddPlugin.cmake, cmake/Modules/LibAddTest.cmake, doc/TESTING.md, doc/news/_preparation_next_release.md, scripts/run_all, scripts/run_memcheck, scripts/run_nokdbtests, src/bindings/gi/lua/CMakeLists.txt, src/bindings/gi/python/CMakeLists.txt, src/bindings/glib/tests/CMakeLists.txt, src/bindings/haskell/CMakeLists.txt, src/bindings/io/doc/CMakeLists.txt, src/bindings/io/glib/CMakeLists.txt, src/bindings/io/uv/CMakeLists.txt, src/bindings/swig/lua/tests/CMakeLists.txt, src/bindings/swig/python/tests/CMakeLists.txt, src/bindings/swig/python2/tests/CMakeLists.txt, src/bindings/swig/ruby/tests/CMakeLists.txt, src/libs/notification/tests/CMakeLists.txt, src/tools/web/CMakeLists.txt, tests/CMakeLists.txt, tests/shell/CMakeLists.txt, tests/shell/shell_recorder/CMakeLists.txt
* Allow ctest to run parallel.
* Remove test scripts.
ref #1900
=> Fix ctest and add parallel

src/plugins/yamlcpp/README.md
Currently the Markdown [Shell Recorder Test](https://master.libelektra.org/tests/shell/shell_recorder/tutorial_wrapper) of [YAML CPP](https://www.libelektra.org/plugins/yamlcpp) requires `ruby`. This update removes this requirement.
=> YAML CPP: Use Bash to Convert Hex Value

scripts/complexity.rb
This will add a simple ruby script which calculates the complexity of a lib elektra namespace based on the number and type of found configuration keys.
The ruby swig binding is required for this script to work.
=> scripts: add complexity calculation script

doc/news/_preparation_next_release.md, src/plugins/crypto/compile_botan.cpp, src/plugins/crypto/compile_gcrypt.c, src/plugins/crypto/compile_openssl.c, src/plugins/gitresolver/gitresolver_test.c
Before this update the build system did not detect 
- Botan,
- Libgcrypt,
- LibGit2 and
- OpenSSL
, if we treated warnings as errors (compiler switch `-Werror`).
=> Build: Fix Detection of Botan, Libgcrypt, LibGit2 and OpenSSL

src/plugins/crypto/openssl_operations.c
Fixes #1969 .
Fix OpenSSL-related linker warning.
=> crypto: fix OpenSSL related linker warning

src/libs/tools/src/CMakeLists.txt, src/libs/tools/tests/CMakeLists.txt
This pull request disables a compiler warning (`Wdelete-non-virtual-dtor`) that broke the Travis macOS builds that use `clang` to translate Elektra.
=> Tools: Disable Warning About Virtual Destructors

doc/INSTALL.md, doc/news/_preparation_next_release.md, scripts/docker/debian/stretch/Dockerfile, scripts/jenkins/Jenkinsfile
Enable debian package generation on the build server to replace the existing one.
resolves #1911
resolves #1752
=> Add package builds

doc/news/_preparation_next_release.md, tests/shell/shell_recorder/README.md, tests/shell/shell_recorder/shell_recorder.sh
The Shell Recorder now always removes the protocol file after it ran a test. It will still print the content of the protocol file
- if a test failed, or
- we used the command line switch `-p`
.
=> Shell Recorder: Always Remove Protocol File

tests/cframework/tests.c
see #1973
see #287
Long descriptions should be in documentation and not here.
=> ctest: cleanup .gnupg

scripts/jenkins/Jenkinsfile, scripts/jenkins/Jenkinsfile.daily
Currently coverage reports overwrite each other with each build. Further quite a lot of test time is spent on generating and transmitting coverage data.
This PR restricts coverage generation to debian stable builds (which should have the highest coverage) to improve build times.
Further it modifies the target path on the documentation server to include the PR name.
=> Improve coverage generation

doc/news/_preparation_next_release.md, src/plugins/mini/README.md
After this update the test `testshell_markdown_mini` should also complete successfully if we
- build Elektra with enabled address sanitizer and
- enable the leak sanitizer (via `ASAN_OPTIONS=detect_leaks=1`)
.
=> mINI: Require `ccode` Plugin Instead of `code`

doc/news/_preparation_next_release.md, scripts/docker/buildelektra.sh, scripts/reformat-cmake, scripts/vagrant/buildelektra.sh, src/plugins/ini/crash_test/crash_test.md, tests/shell/CMakeLists.txt, tests/shell/check_bashisms.sh
After this pull request the script `check_bashisms.sh` should work both on macOS (BSD find) and Linux (GNU find).
=> Check Bashisms: Fix Interoperability of Script

scripts/docker/debian/stretch/Dockerfile.doc, scripts/docker/homepage/backend/Dockerfile, scripts/docker/homepage/frontend/Dockerfile, scripts/jenkins/Jenkinsfile, src/tools/rest-backend/run.sh
Add homepage build to Jenkinsfile
=> Add jenkinsfile homepage

doc/help/kdb-ls.md, doc/man/man1/kdb-ls.1, doc/news/_preparation_next_release.md, tests/shell/shell_recorder/tutorial_wrapper/CMakeLists.txt, tests/shell/shell_recorder/tutorial_wrapper/markdown_shell_recorder.sh
This pull request should fix the problems of the Markdown Shell Recorder test of the Hexnumber plugin (see PR #1903).
=> Markdown Shell Recorder: Add Partial Support for Indented Code Blocks

doc/news/_preparation_next_release.md, tests/shell/shell_recorder/tutorial_wrapper/SyntaxCheck.md, tests/shell/shell_recorder/tutorial_wrapper/markdown_shell_recorder.sh
After this update the Shell Recorder should support intended code blocks properly.
=> Markdown Shell Recorder: Support Indented Code Blocks

doc/news/_preparation_next_release.md, scripts/reformat-cmake
This pull request should fix the problem described [here](https://github.com/ElektraInitiative/libelektra/pull/1903#discussion_r189332987).
=> Reformat CMake: Ensure `cmake-format` Works

scripts/jenkins/Jenkinsfile.daily
Calls docker system prune on each docker host for cleanup of dangling images.
This reclaims a lot of disk space.
=> build: prune docker daily

.travis.yml, doc/news/_preparation_next_release.md, src/tools/qt-gui/CMakeLists.txt
After this update building the Qt-GUI should also work if we use the [latest version of Qt](http://blog.qt.io/blog/2018/05/22/qt-5-11-released).
=> Qt-GUI: Support Qt 5.11

.travis.yml, doc/news/_preparation_next_release.md, src/libs/notification/tests/CMakeLists.txt
Turns out we only installed recent versions of compilers on most of the Linux build jobs, but did not use them to compile Elektra 😳. This update should fix this problem. The PR also disables `testlib_notification` on ASAN enabled build jobs, since the test [seems to leak memory](https://travis-ci.org/sanssecours/elektra/jobs/383014685#L2197).
=> Travis: Use Latest Version of GCC and Clang

doc/news/_preparation_next_release.md, doc/tutorials/README.md, doc/tutorials/notifications.md, src/plugins/journald/README.md, src/plugins/journald/journald.c, src/plugins/logchange/README.md, src/plugins/logchange/logchange.c, src/plugins/syslog/README.md, src/plugins/syslog/log.h, src/plugins/syslog/syslog.c
This PR adds an option for logging on kdbGet() before configuration is loaded.
The plugins "syslog", "journald" and "logchange" were changed. 
Logging on kdbGet() is disabled by default and needs to by enabled using "get=on" when mounting.
If enabled, the parentKey passed to kdbGet() is logged.
=> logging plugins: add option for logging on pregetstorage

debian/copyright
This pull request adds copyright info for [DownloadProject](https://github.com/Crascit/DownloadProject) to the file `debian/copyright`.
=> Debian: Add Attribution Info for DownloadProject

doc/news/_preparation_next_release.md, doc/todo/TESTING, scripts/docker/homepage/backend/Dockerfile, src/plugins/ni/CMakeLists.txt, tests/shell/shell_recorder/tutorial_wrapper/CMakeLists.txt
Fix issues with the rest-backend.
`ni` was disabled for ASAN builds but is needed for website setup.
We fix exclusions and disable the leaking test instead of the whole plugin.
Resolves #2026
=> Fix homepage builds

doc/news/_preparation_next_release.md, scripts/jenkins/Jenkinsfile
Replace old `debian-multiconfig-gcc-stable` buildjob.
=> build: Implement debian-stable-multiconf

.travis.yml, doc/news/_preparation_next_release.md, src/plugins/ni/CMakeLists.txt, src/plugins/ni/README.md, src/plugins/yamlcpp/write.cpp, tests/shell/shell_recorder/shell_recorder.sh, tests/shell/shell_recorder/tutorial_wrapper/markdown_shell_recorder.sh
This pull request adds
- support for empty `#>` checks to the Markdown Shell Recorder and
- a basic MSR test for the `ni` plugin.
.
=> Markdown Shell Recorder: Support Empty `#>` directive

doc/BUILDSERVER.md, doc/news/_preparation_next_release.md, scripts/jenkins/Jenkinsfile
Port https://build.libelektra.org/jenkins/job/elektra-gcc-configure-debian-optimizations/ to new build system.
=> build: Port no-optimizations build job

doc/METADATA.ini, doc/help/kdb-change-resolver-symlink.md, doc/help/kdb-change-storage-symlink.md, doc/man/man1/kdb-change-resolver-symlink.1, doc/man/man1/kdb-change-storage-symlink.1, doc/news/_preparation_next_release.md, doc/todo/NEWS.md, scripts/fix-spelling, src/plugins/typechecker/README.md
We now use a structure, similar to the one of the repository, for the release notes. Instead of personal interest (maintainer, developer, user) we now use general technical topics (bindings, plugins, tools, …) as headings. This structure should it make much simpler to decide where to look for a certain new feature or bug fix.
=>  Release: Improve Structure of Release Notes

doc/help/kdb-set.md, doc/help/kdb.md, doc/news/_preparation_next_release.md, src/tools/kdb/set.hpp
Update the usage text of `kdb set` to indicate how to set negative values.
=> kdb-set: add line about negative values to usage text

doc/BUILDSERVER.md, doc/news/_preparation_next_release.md, scripts/docker/debian/stretch/Dockerfile.i386, scripts/jenkins/Jenkinsfile
port i386 job to new build system
=> build: port i386 job to new build system

doc/news/_preparation_next_release.md, scripts/reformat-source, src/plugins/fstab/fstab/fstab-write, src/plugins/fstab/testmod_fstab.c, tests/cframework/tests.c, tests/cframework/tests.h
* Provide a way to compare files made of regex patterns with regular files for tests and
* rewrite fstab tests to use this new functionality
Resolves #2081 
=> Add regex tests + fix musl fstab issues

doc/news/_preparation_next_release.md, tests/CMakeLists.txt
After this update the build system should not install Google Test any more.
=> Build: Do Not Install Google Test

doc/news/_preparation_next_release.md, scripts/jenkins/Jenkinsfile
The space in buildDir can not be escaped during `cp` as it does not allow the shell to expand `*`.
=> Fix archivation

cmake/ElektraCompiling.cmake, doc/news/_preparation_next_release.md, tests/cframework/CMakeLists.txt, tests/cframework/tests.c
* check if required functions are available
* set test feature macros explicitly if needed
* replace manual file deletion with nftw call if nftw is available.
This should resolve #2008 and some parts of #1973. But fcrypt still fails as soon as a `TMPDIR` is specified.
=> tests: Properly remove temporary test home dir

.travis.yml, doc/news/_preparation_next_release.md
Bump macOS/Xcode versions on travis-ci.
I think there is no point to add this to release notes or anything else from the checklist.
=> travis-ci: bump macOS/Xcode versions

.cmake-format.yaml, cmake/Modules/LibAddPlugin.cmake, doc/news/_preparation_next_release.md, src/plugins/ccode/CMakeLists.txt, src/plugins/type/CMakeLists.txt
This pull request adds C++ test support to the CMake functions 
- `add_plugintest` and
- `add_plugin`
.
=> Build: Add Support for C++ Tests to LibAddPlugin

.cmake-format.yaml, cmake/Modules/LibAddPlugin.cmake, doc/news/_preparation_next_release.md
=> Build: Support Environment Variables in `add_plugintest`

doc/news/_preparation_next_release.md, tests/cframework/tests.h
=>  CFramework: Support Comparison of Empty Key Sets

doc/news/_preparation_next_release.md, scripts/jenkins/Jenkinsfile, tests/cframework/CMakeLists.txt
Resolve an issue where NFTW was not detected by CMake.
Also adds the ability to ignore aborts when sending status mails.
Closes #2157.
=> Detect nftw

doc/news/_preparation_next_release.md, tests/cframework/CMakeLists.txt
Before this PR the command `kdb_runall` in the Travis build job `🍏 GCC` prints the following text:
```
CYPTO        TESTS
==================
crypto_gcrypt Results: 65 Tests done — 0 errors.
/Users/travis/build/sanssecours/elektra/tests/cframework/tests.c:542: error in clean_temp_home: Could not delete TMPHOME manually
--- running testmod_crypto_openssl ---
CYPTO        TESTS
==================
crypto_openssl Results: 65 Tests done — 0 errors.
/Users/travis/build/sanssecours/elektra/tests/cframework/tests.c:542: error in clean_temp_home: Could not delete TMPHOME manually
```
. After the PR the error messages are gone:
```
CYPTO        TESTS
==================
crypto_gcrypt Results: 65 Tests done — 0 errors.
--- running testmod_crypto_openssl ---
CYPTO        TESTS
================== …
```
=>  CFramework: Improve Detection of `ftw.h`

doc/news/_preparation_next_release.md, tests/kdb/testkdb_allplugins.cpp
- [First Try](https://build.libelektra.org/jenkins/blue/organizations/jenkins/libelektra/detail/PR-2221/1/pipeline): 😊
- [Second Try](https://build.libelektra.org/jenkins/blue/organizations/jenkins/libelektra/detail/PR-2221/2/pipeline): 😊
- [Third Try](https://build.libelektra.org/jenkins/blue/organizations/jenkins/libelektra/detail/PR-2221/2/pipeline): 😊
- [First Try](https://build.libelektra.org/jenkins/blue/organizations/jenkins/libelektra/detail/PR-2221/4/pipeline): 😊
- [Second Try](https://build.libelektra.org/jenkins/blue/organizations/jenkins/libelektra/detail/PR-2221/5/pipeline): 😊
- [Third Try](https://build.libelektra.org/jenkins/blue/organizations/jenkins/libelektra/detail/PR-2221/6/pipeline): 😭
- [First Try](https://build.libelektra.org/jenkins/blue/organizations/jenkins/libele …
=> Test: Exclude Ruby Instead of Semlock Plugin

doc/INSTALL.md, doc/news/_preparation_next_release.md, src/bindings/cpp/tests/CMakeLists.txt
While reading the documentation for [PEGTL](https://github.com/taocpp/PEGTL), I stumbled upon a diagram that shows [the status of available packages for the library](https://github.com/taocpp/PEGTL/blob/master/doc/Installing-and-Using.md#installation-packages). Since the graph looked nice, I thought it makes sense to add a list of available packages to our documentation too.
The graph below shows an (incomplete) list of available packages for Elektra.
[![Packaging status](https://repology.org/badge/vertical-allrepos/elektra.svg)](https://repology.org/metapackage/elektra/versions)
=>  Documentation: Add List of Available Packages

doc/news/_preparation_next_release.md, src/bindings/cpp/tests/CMakeLists.txt
I included commit 1fdb15e, since otherwise the build job `🍏 Clang ASAN` will probably always hit the [timeout limit of public repositories](https://docs.travis-ci.com/user/customizing-the-build/#build-timeouts).
=> Travis: Fix Compilation With Clang 7 

doc/news/_preparation_next_release.md, src/include/kdbprivate.h, src/libs/elektra/keyset.c, src/plugins/mmapstorage/README.md, src/plugins/mmapstorage/internal.h, src/plugins/mmapstorage/mmapstorage.c, src/plugins/mmapstorage/testmod_mmapstorage.c
Resolves #2248. Unlinking is now implemented by simply calling `unlink()` instead of a custom approach that was error prone.
Includes some other small cleanups and fixes.
=> mmapstorage: change unlinking approach

.travis.yml, doc/news/_preparation_next_release.md
This update should mitigate the timeout problems of some Travis build jobs (`🐧 GCC ASAN`, `🍏 Clang` and `🍏 MMap`) a little bit. From what I can tell, all build jobs should usually [execute in less than 40 minutes](https://travis-ci.org/sanssecours/elektra/builds/437064505) after the update. This update does increase the overall build time a little bit though.
=> Travis: Mitigate Timeout Problems

cmake/Modules/LibAddPlugin.cmake, doc/news/_preparation_next_release.md
=> cmake: add dependency from plugin tests to plugins

doc/news/_preparation_next_release.md, src/bindings/swig/ruby/kdb.i
This is preparation for #1946 and #1293 but use a separate PR for this to get this merges soon.
=> Ruby bindings: kdb, do not use private headers

doc/news/_preparation_next_release.md, src/libs/ease/array.c, src/plugins/directoryvalue/directoryvalue_delegate.cpp, src/plugins/yamlcpp/write.cpp, tests/ctest/test_array.c
This pull request improves the behavior of `elektraArrayValidateBaseNameString`, which now returns the offset to the first digit of the array index for valid array elements:
```c
elektraArrayValidateBaseNameString ("#_10");
//                                     ~~^ Returns `2` (instead of `1`)
elektraArrayValidateBaseNameString ("#___1337");
//                                    ~~~~^ Returns `4` (instead of `1`)
```
. While the updated behavior is slightly different from the current one, I think the increased utility makes up for breaking (hypothetical existing) user code that compares the return value of the function to `1` using the equality operator (instead of `>=`).
=> Array: Change Behavior of `elektraArrayValidateBaseNameString` Slightly

doc/decisions/global_plugins.md, doc/news/_preparation_next_release.md, src/include/kdbplugin.h, src/include/kdbprivate.h, src/libs/elektra/global.c, src/libs/elektra/kdb.c, src/libs/elektra/mount.c, src/libs/plugin/plugin.c, src/plugins/doc/doc.c, src/plugins/doc/doc.h, tests/icheck.suppression
Adds a global keyset handle for global plugins #2270. 
Get return value of global plugin calls.
See docs & release notes of PR.
=> Global plugins: global keyset handle

doc/news/_preparation_next_release.md, src/libs/meta/meta.c
=> Documentation fix for elektraMetaArrayToKS

doc/decisions/gsettings_values.md
Decision on how to handle GSettings values when using Elektra as
backend.
=> GNOME Integration: decision to GSettings values

doc/METADATA.ini, doc/help/elektra-glossary.md, doc/news/_preparation_next_release.md, doc/tutorials/README.md, doc/tutorials/command-line-options.md, examples/CMakeLists.txt, examples/opts.c, examples/optsSnippets.c, src/error/specification, src/include/CMakeLists.txt, src/include/kdbopts.h, src/libs/CMakeLists.txt, src/libs/opts/CMakeLists.txt, src/libs/opts/opts.c, tests/ctest/CMakeLists.txt, tests/ctest/test_opts.c
Implementation of #1252. The name was changed to `elektraGetOpts` to avoid confusion with the old [getenv](https://master.libelektra.org/src/bindings/intercept/env).
=> Command line argument parsing

cmake/Modules/FindAugeas.cmake, doc/news/_preparation_next_release.md
It seems `/usr/local` is the correct directory, which is also used by some Linux distributions according to the [documentation of the Augeas plugin](https://master.libelektra.org/src/plugins/augeas/README.md#mounting-and-configuration).
=> Augeas: Change Prefix for Lens Directory on macOS

doc/news/_preparation_next_release.md, src/error/exporterrors.cpp, src/include/elektra/error.h, src/include/kdbprivate.h, src/libs/highlevel/README.md, src/libs/highlevel/elektra.c, tests/kdb/testkdb_highlevel.cpp
As discussed in #2399, this removes most of the current error access functions from the public API.
It also adds border tests for integer types and therefore closes #2430.
=> highlevel: remove most of error handling from public API

doc/news/_preparation_next_release.md, doc/todo/TESTING, scripts/jenkins/Jenkinsfile
This update should get rid of most of the temporary test failures reported in issue [#2439](https://issues.libelektra.org/2439).
=> Jenkins: Disable Failing Tests

doc/news/_preparation_next_release.md, src/plugins/specload/README.md, src/plugins/specload/specload.c, src/plugins/specload/specload.h, src/plugins/specload/testapp.c
This is a minor addition to the specload plugin, to abstract over the dependency on `quickdump`.
=> Minor addition to specload

doc/news/_preparation_next_release.md, src/include/kdbease.h, src/libs/ease/reference.c, src/plugins/reference/reference.c, tests/icheck.suppression
This simply moves reference resolution from the reference plugin into libease. That way it can be used by other parts of Elektra, in particular code generation.
=> move reference resolving into libease

README.md, doc/news/_preparation_next_release.md, scripts/check-env-dep
[LGTM](https://lgtm.com) provides automated source code checks for repositories. Currently the [LGTM page for Elektra](https://lgtm.com/projects/g/ElektraInitiative/libelektra) lists about 80 problems we should probably fix, or at least take a look at.
I think it would also make sense to activate LGTM’s [automated checks for pull request](https://lgtm.com/projects/g/ElektraInitiative/libelektra/ci/). I would do it myself, but I do not have the required administrator rights for the repository.
[![Total alerts](https://img.shields.io/lgtm/alerts/g/ElektraInitiative/libelektra.svg?logo=lgtm&logoWidth=18)](https://lgtm.com/projects/g/ElektraInitiative/libelektra/alerts)
=> Documentation: Add Badge for LGTM

doc/news/_preparation_next_release.md, lgtm.yml
Please ignore the failed build job [“LGTM analysis: C/C++”](
https://lgtm.com/projects/g/ElektraInitiative/libelektra/rev/pr-02da0df8383b852d5cc447d0a37cd56a044b80f5). The reason why this build job fails is that LGTM is currently not able to build Elektra from the `master` branch of the repository. This pull request should [fix this issue](https://lgtm.com/projects/g/ElektraInitiative/libelektra/logs/rev/pr-02da0df8383b852d5cc447d0a37cd56a044b80f5/lang:cpp/stage:Build%20merge_2c5a5488b802bd666dcab1ac2b4a1b68cb6236b4).
=> LGTM: Add Initial Version of Configuration File

doc/METADATA.ini, doc/news/_preparation_next_release.md, src/plugins/reference/README.md
This PR is a fix for the reference plugin because I received the following error when trying to mount a specification:
```
kdb spec-mount '/sw/lcdproc/lcdexec/#0/current'
#> The command kdb spec-mount terminated unsuccessfully with the info:
#> No plugin that provides check/reference/restrict/# could be found
#> Please report the issue at https://issues.libelektra.org/
```
I hope it is ok that I do not add something in the news doc because it is not that relevant
=> reference: fix README

doc/help/kdb-get.md, doc/news/_preparation_next_release.md, doc/todo/TESTING, src/tools/kdb/get.cpp, tests/shell/shell_recorder/tutorial_wrapper/CMakeLists.txt
src/tools/kdb/get.cpp
I've added the check after the final key-lookup inside the execute-method. If the printTrace-method is the better place for this please let me know and I'll find a way to retrieve the information there.
Close #2474
=> Let kdb get -v display if value comes from default

doc/ERROR_CONCEPT.md, doc/decisions/README.md, doc/decisions/error_message.md, doc/news/_preparation_next_release.md
This PR is done as a basis for discussions on the new error concept and is not intended to be merged.
=> Error message concept

doc/news/_preparation_next_release.md, scripts/pre-commit-check-formatting, scripts/reformat-all, scripts/reformat-cmake, scripts/reformat-markdown, scripts/reformat-shfmt, scripts/reformat-source
This adds a `reformat-all` script. It also adds a `pre-commit` hook script to check formatting before every commit.
Note: the pre-commit hook only notifies you of unformatted files and provides a diff, it doesn't auto-apply formatting because unstaged changes may cause merge conflicts
=> Formatting improvements

doc/help/kdb-cp.md, doc/news/_preparation_next_release.md, src/tools/kdb/cp.cpp, tests/shell/shell_recorder/tutorial_wrapper/CMakeLists.txt
src/tools/kdb/cp.cpp
Added ckeck of key-values of target- and source-key. If the values are identical, 'kdb cp' now succeeds.
Close #2560 
=> kdb: Don't fail if target-key has same value as source-key

doc/news/_preparation_next_release.md, src/libs/tools/tests/testtool_keyhelper.cpp
src/libs/tools/tests/testtool_keyhelper.cpp
Added test to check calculation of newPath for cascading keys. See issue #2460 or PR #2576
=> Added keyhelper-test

doc/dev/logging.md, doc/news/_preparation_next_release.md, src/include/kdblogger.h, src/libs/elektra/log.c
After this update the logger
- adds debug messages to the system log, if you enable the CMake variable `DEBUG`
- also logs messages at the specified minimum log level
- does not truncate relative file paths incorrectly anymore
.
=> Logger: Fix Minor Problems

doc/news/_preparation_next_release.md, src/libs/elektra/log.c, src/plugins/mmapstorage/README.md, src/plugins/mmapstorage/internal.h, src/plugins/mmapstorage/mmapstorage.c, src/plugins/mmapstorage/shelltests.md, src/plugins/mmapstorage/testmod_mmapstorage.c, tests/shell/shell_recorder/tutorial_wrapper/CMakeLists.txt
=> mmapstorage: add  import/export compatibility

doc/news/_preparation_next_release.md, src/plugins/yajl/testmod_yajl.c, src/plugins/yajl/yajl_gen.c, src/plugins/yajl/yajl_parse.c
This PR replaces the `###empty_array` syntax of yajl with the metakey according to the [array decision](https://github.com/ElektraInitiative/libelektra/blob/master/doc/decisions/array.md), #182 and #2477.
Please add the "ready to …
=> WIP: Yajl: Empty arrays with metakey

.github/CONTRIBUTING.md, doc/news/_preparation_next_release.md, doc/tutorials/contributing-clion.md
I've written a tutorial to help newcomers contributing to libelektra using CLion as proposed in #2623. Instead of solely focusing on development using CLion, I've described the whole process of adding new code to this project. If therefore anything important is missing especially regarding the development-procedure, just leave me a note.
Closes #2623
Tagging @kodebach too, if you have time to spare and want to, your input is also very welcome (of course this applies to everyone) =)
=> Added tutorial for newcomers contributing to libelektra using CLion

doc/decisions/error_codes.md, doc/dev/README.md, doc/dev/error-categorization.md, doc/news/_preparation_next_release.md
=> Error categorization guidelines & design decision splitup

doc/news/_preparation_next_release.md, src/plugins/crypto/openssl_operations.c
Initialization and deinitialization is not needed anymore.
=> Fix compilation without deprecated OpenSSL APIs

doc/news/_preparation_next_release.md, src/tools/qt-gui/src/treeviewmodel.cpp, src/tools/qt-gui/src/treeviewmodel.hpp
I'ts been a while since my last merge request, so I'm not exactly sure what to do and …
=> #2717: Improve qt-gui error message popup

cmake/ElektraCache.cmake, cmake/Modules/LibAddTest.cmake, doc/news/_preparation_next_release.md
look up the required tool in TOOLS and REMOVED_TOOLS.
Continues #2672 .
Fixes #2668 .
=> cmake: fix REQUIRED_TOOLS in function add_msr_test

doc/news/_preparation_next_release.md, doc/tutorials/run_all_tests_with_docker.md, doc/tutorials/run_reformatting_script_with_docker.md
@markus2330 Please review my another tutorial. I thought it was a good idea to merge it with my previous tutorial, but even it is in a separate branch, I still see all the other commits... I hope it is OK.
- [x ] Short descriptions should be in the release notes (added as entry in
- Add the "ready to merge" label **if the build server …
=> Reformat with docker tutorial

doc/news/_preparation_next_release.md, src/CMakeLists.txt
=> Add plugin tests only if BUILD_TESTING=ON

cmake/Modules/SafeCheckSymbolExists.cmake, doc/news/_preparation_next_release.md
@markus2330 @sanssecours , please review my pull request
=> Add temporary fix for finding jni plugin

.restyled.yaml, doc/news/_preparation_next_release.md
The changes in this PR should get rid of problems regarding the formatting style of Shell files in pull requests. Unfortunately [Restyled](https://restyled.io) does not support 
- [`clang-format`](https://github.com/restyled-io/restyled.io/issues/161) and
- [`cmake-format`](https://github.com/restyled-io/restyled.io/issues/162)
. The tool does support `prettier`, but currently [only for `JavaScript` and `YAML` code](https://github.com/restyled-io/restyled.io/wiki/Available-Restylers).
For the Restyled integration to work, someone with administrator rights has to [install the GitHub application](https://github.com/apps/restyled-io/installations/new) and grant it rights to Elektra’s main repository.
=> Restyled: Add Configuration for `shfmt`

doc/news/_preparation_next_release.md, scripts/kdb-bash-completion
see #2835
**Short release notes**: Fix bash completion
**Longer description**: Now you can call kdb <TAB><TAB> and it will return
```
check          fstab          import         mount          shell
complete       get            info           mv             smount
convert        getmeta        list           remount        spec-mount
cp             global-mount   list-commands  rm             test
editor         global-umount  list-tools     rmmeta         umount
export         gmount         ls             set            vset
file           gumount        lsmeta         setmeta        
find           help           merge          sget
``` …
=> fix color completition

doc/decisions/README.md, doc/decisions/warning-array.md, doc/news/_preparation_next_release.md
=> error: warning array concept added

doc/news/2019-02-26_0.8.26.md, doc/news/_preparation_next_release.md, scripts/reformat-cmake
As far as I can tell the test `testscr_check_formatting` now fails in the
- [Travis](https://travis-ci.org/ElektraInitiative/libelektra/builds/571743570),
- [Cirrus](https://cirrus-ci.com/build/5150337176961024), and
- [Jenkins](https://build.libelektra.org/jenkins/blue/organizations/jenkins/libelektra/detail/PR-2877/1/pipeline/315)
build jobs, if a CMake file contains improperly formatted code.
=> Reformat CMake: Fix Version Detection

doc/news/_preparation_next_release.md, src/include/elektra/conversion.h, src/include/kdbease.h, src/include/kdbtypes.h, src/libs/ease/conversion.c, src/libs/ease/symbols.map, src/libs/highlevel/symbols.map, src/plugins/type/CMakeLists.txt, src/plugins/type/type.c, src/plugins/type/types.c, tests/icheck.suppression
=> Move conversion functions from highlevel to ease

doc/news/_preparation_next_release.md, scripts/link-checker, tests/linkchecker.whitelist
Changes the linkchecker so it de-duplicates before checking them (reduces from ~1100 to ~800 checks). In addition the timeout was reduced from 10s to 5s and the number of retries from 20 (default) to 3.
=> Link checker: deduplicate links

doc/news/_preparation_next_release.md, src/plugins/tcl/CMakeLists.txt
I think it makes sense to merge this as soon as possible, since the [Travis build job `🍏 GCC` will continue to fail](https://travis-ci.org/ElektraInitiative/libelektra/jobs/581677651) otherwise.
=> Tcl: Fix Name of Boost Include Directory

cmake/ElektraConfig.cmake.in, doc/help/elektra-highlevel-gen.md, doc/news/_preparation_next_release.md
More update from the review of #2927.
=> Minor documentation updates

doc/decisions/README.md, doc/decisions/highlevel_help_message.md, doc/help/kdb-gen-highlevel.md, doc/man/man1/kdb-gen-highlevel.1, doc/man/man7/elektra-highlevel-gen.7, doc/news/_preparation_next_release.md, src/include/kdbopts.h, src/libs/ease/symbols.map, src/libs/highlevel/elektra.c, src/plugins/gopts/gopts.c, src/plugins/spec/README.md, src/plugins/spec/spec.c, src/plugins/spec/testmod_spec.c, src/tools/kdb/CMakeLists.txt, src/tools/kdb/gen/highlevel/highlevel.cpp, src/tools/kdb/gen/highlevel/highlevel.hpp, src/tools/kdb/gen/templates/highlevel.c.mustache, tests/shell/gen/highlevel/empty.expected.c, tests/shell/gen/highlevel/enum.expected.c, tests/shell/gen/highlevel/externalspec.expected.c, tests/shell/gen/highlevel/externalwithdefaults.expected.c, tests/shell/gen/highlevel/nosetter.expected.c, tests/shell/gen/highlevel/notype.expected.c, tests/shell/gen/highlevel/simple.data.ini, tests/shell/gen/highlevel/simple.expected.c, tests/shell/gen/highlevel/struct.expected.c
If the user starts an application that has required keys with `-h`/`--help`, it would result in an error and the help message wouldn't be printed. This changes that.
It also adds the regenerated man page that is missing from #2942 (should've been part of 
b18447e).
=> Codegen: Ignore missing required keys in help mode

doc/man/man7/elektra-plugins.7, doc/news/_preparation_next_release.md, doc/tutorials/plugins.md, src/plugins/README.md, src/plugins/c/c.c, src/plugins/c/c.h, src/plugins/cpptemplate/cpptemplate.cpp, src/plugins/cpptemplate/cpptemplate.hpp, src/plugins/multifile/multifile.c, src/plugins/multifile/multifile.h, src/plugins/process/process.c, src/plugins/process/process.h, src/plugins/reference/reference.h, src/plugins/specload/specload.c, src/plugins/specload/specload.h, src/plugins/specload/testmod_specload.c, src/plugins/template/template.c, src/plugins/template/template.h
May I ask why we now [use the name `checkConf`](https://github.com/ElektraInitiative/libelektra/commit/3478694d) instead of `checkConfig`? I liked the old name better, since I am usually not a fan of abbreviated names. It also looks like we still use the similar name `kdbGenConfig` in the [ReadMe of all plugins](https://github.com/ElektraInitiative/libelektra/blob/master/src/plugins/README.md#c-interface). Do we use this function anywhere? At least searching the code base for `GenConfig` did only show two occurrences of the string, one in the ReadMe of all plugins, and one in the man page generated from said ReadMe file.
=> Plugins: Unify Name of Configuration Check Function

doc/news/_preparation_next_release.md, src/bindings/rust/Cargo.lock, src/bindings/rust/PublishCrate.md, src/bindings/rust/README.md, src/bindings/rust/elektra-sys/Cargo.toml.in, src/bindings/rust/elektra-sys/build.rs.in, src/bindings/rust/elektra-sys/published_Cargo.toml, src/bindings/rust/elektra-sys/published_build.rs, src/bindings/rust/elektra-sys/src/lib.rs, src/bindings/rust/elektra/Cargo.toml.in, src/bindings/rust/elektra/published_Cargo.toml, src/bindings/rust/elektra/src/key.rs, src/bindings/rust/elektra/src/lib.rs, src/bindings/rust/elektra/src/readable.rs, tests/linkchecker.whitelist
The Rust Bindings are now published to crates.io. Since there are some differences between what cmake requires and what I need for publishing, I had to add modified versions of `Cargo.toml` and `build.rs`. I also added some additional documentation in the elektra crate and added a short guide for publishing future crate versions.
fixes #2730 
need to be …
=> Published Rust Bindings

doc/CODING.md, doc/TESTING.md, doc/news/_preparation_next_release.md, doc/tutorials/run_reformatting_script_with_docker.md
FreeBSD has `csh` as default shell. The syntax of `run_dev_env` is invalid in `csh`. 
```csh
source ../scripts/run_dev_env
echo $?
#1
```
@d3nwp I added you as reviewer as you were mentioned in #3067.
=> Various documentation improvements

doc/help/kdb-plugin-list.md, doc/news/_preparation_next_release.md, src/tools/kdb/pluginlist.cpp, src/tools/kdb/pluginlist.hpp
=> Kdb plugin list doc

doc/news/_preparation_next_release.md, src/plugins/jni/CMakeLists.txt
=> build: make jni depend on jna to avoid mvn dependency resolution fails

doc/news/_preparation_next_release.md, src/bindings/cpp/include/key.hpp, src/bindings/swig/common.i, src/bindings/swig/lua/kdb.i, src/bindings/swig/python/kdb.i
Hi Markus,
as requested I've looked into this in more detail. The first commit fixes one of the extra copies. Fixing the other was only possible by providing a `char *`-alternative (making the first commit actually unnecessary). As all SWIG wrapped languages operate on char pointers wrapping a function with `std::string` always adds an extra copy.
Can you please assign (+ping if already assigned) issues you want me to fix. Thanks
=> SWIG performance

doc/news/_preparation_next_release.md, src/plugins/gopts/CMakeLists.txt
Closes #3148.
Try to increase gopts timeout due to slow valgrind tests (#3148).
=> gopts: increase test timeout

doc/news/.gitattributes, doc/news/_preparation_next_release.md
This solves #2925.
The following code snippets are from my test. The first one still produced a merge conflict while the second one (which is based on this branch) did not.
```zsh
10086* gco -b anton
10087* echo "anton" > _preparation_next_release_test.md
10088* git add _preparation_next_release_test.md
10089* git commit -m "test"
10090* gcm
10091* gco -b berta
10092* echo "berta" > _preparation_next_release_test.md
10093* git add _preparation_next_release_test.md
10094* git commit -m "test"
10095* git merge anton
```
```zsh
10119* gco mergeDriver
10120* gco -b anton2
10121* echo "anton" > _preparation_next_release_test.md
10122* git add _preparation_next_release_test.md
10123* git commit -m "test"
10124* gco mergeDriver
10125* gco -b berta2
10126* echo "berta" > …
```
=> Close 2925: Add merge driver for release notes

doc/news/_preparation_next_release.md, src/bindings/glib/gelektra-key.c, src/bindings/glib/gelektra-keyset.c, src/bindings/glib/gelektra-keyset.h, src/bindings/glib/tests/testglib_keyset.c, src/bindings/gsettings/elektrasettingsbackend.c
=> GLIB changes

doc/news/_preparation_next_release.md, src/libs/merge/CMakeLists.txt, src/libs/merge/kdbmerge.c, tests/ctest/CMakeLists.txt, tests/shell/shell_recorder/tutorial_wrapper/CMakeLists.txt
Should fix #3206 
This is required by their documentation. This certainly gives us memleaks but
avoids segfaults.
If you are already Elektra …
=> Merge: Always initialize LibGit

doc/news/2018-08-18_0.8.24.md, doc/news/_preparation_next_release.md, scripts/CMakeLists.txt, scripts/dev/CMakeLists.txt, scripts/dev/run_all.in, scripts/dev/run_checkshell.in, scripts/dev/run_memcheck.in, scripts/dev/run_nocheckshell.in, scripts/dev/run_nokdbtests.in, scripts/run_memcheck.in, tests/CMakeLists.txt
=> tests: run cmake twice

doc/news/_preparation_next_release.md, src/plugins/mmapstorage/mmapstorage.c, src/plugins/mmapstorage/testmod_mmapstorage.c
=> mmapstorage: filter empty meta keysets

doc/news/_preparation_next_release.md, src/plugins/augeas/augeas.c
=> Augeas add lenspath to errormessage

doc/news/_preparation_next_release.md, scripts/docker/website/backend/Dockerfile, scripts/docker/website/frontend/Dockerfile, scripts/jenkins/Jenkinsfile
=> Deploy website

.cirrus.yml, .travis.yml, doc/news/_preparation_next_release.md
This pull request is partially based on PR #3350. As far as I know, it should fix the current build problems on both Cirrus and Travis. It is a little bit less intrusive than PR #3350, since afterwards `ronn` should still build the man pages in the Cirrus macOS build jobs. This has the advantage that the uninstall check:
https://github.com/ElektraInitiative/libelektra/blob/5f742352a5bc1a6a25d8e153cf5c30203fbcc89a/.cirrus.yml#L197-L205
makes sure that uninstalling also removes all man pages. Please feel free to close this PR in favor of pull request #3350 if you like.
=> CI: Fix macOS Build Jobs

doc/news/_preparation_next_release.md, scripts/docker/debian/sid/Dockerfile, scripts/jenkins/Jenkinsfile
Debian sid bumped some package versions so some packages we used are no longer available. Notably python 2 was dropped and ruby was bumped to 2.7.
=> docker: fix debian sid packages

.cirrus.yml, doc/news/_preparation_next_release.md, scripts/docker/cirrus/fedora/Dockerfile, scripts/docker/debian/buster/Dockerfile, scripts/docker/fedora/31/Dockerfile, scripts/jenkins/Jenkinsfile
Jenkins: main build stage with debian and fedora stable. Move oldstable to second build stage.
Improve cirrus fedora image and add fedora docker image for jenkins to cover many tests.
Closes #3227.
=> CI: improve fedora image

doc/news/_preparation_next_release.md, src/tools/webd/package-lock.json
Update webd dependencies.
@raphi011 we have some insecure packages in webd. I tried updating with `npm update` and `npm audit fix` to test if it still works. Autoupdate with dependabot does not work for some reason. Can you take a look if this makes sense or do you want to update this within your PR #3400?
=> Webd: update dependencies

doc/news/_preparation_next_release.md, scripts/docker/ubuntu/focal/Dockerfile, scripts/jenkins/Jenkinsfile.release, scripts/release/get-installed-version.sh, scripts/release/release.sh
Fixes issues of the release pipeline mentioned in #3528, adds the ubuntu focal docker image and improves log output of the release script.
If you …
=> release: fix release pipeline

doc/news/2020-10-30_0.9.3.md, src/plugins/toml/README.md
=> Release notes

doc/news/_preparation_next_release.md, src/libs/elektra/kdb.c
=> core: kdbSet read-only parentKey

doc/news/_preparation_next_release.md
=> doc: rework release notes

doc/news/_preparation_next_release.md, doc/tutorials/highlevel.md
This is just a minor change to improve readability. After having read through all items of the PR guidelines, I believe none of them applies.
=> doc: Improve readability of section in High-Level API tutorial

.cirrus.yml, .github/workflows/macOS_gcc10.yml, doc/news/_preparation_next_release.md, scripts/dev/run_nocheckshell.in
Fixes multiple CI issues.
Closes #3635.
=> CI: update macOS images and various fixes

doc/news/_preparation_next_release.md, src/libs/notification/notification.c, src/plugins/internalnotification/internalnotification.c, src/plugins/internalnotification/testmod_internalnotification.c
=> Fix ARM builds

doc/news/_preparation_next_release.md, doc/tutorials/mount.md
Copy of #3723. Rebased and removed duplicate/unrelated news entries.
Closes #3722.
Closes #3723.
=> doc: fix mount example

doc/THIRD-PARTY-LICENSES, doc/news/_preparation_next_release.md, scripts/check-third-party-license-file-paths, scripts/cmake/Modules/FindLua.cmake, scripts/cmake/Modules/FindPython2Interp.cmake, scripts/cmake/Modules/FindPython2Libs.cmake
=> [CM H2] Third party licensing cleanup

doc/news/_preparation_next_release.md, scripts/docker/README.md, scripts/docker/debian/bullseye/Dockerfile, scripts/docker/debian/bullseye/package.Dockerfile, scripts/docker/debian/bullseye/release.Dockerfile, scripts/docker/debian/buster/package.Dockerfile, scripts/docker/debian/buster/release.Dockerfile, scripts/docker/fedora/33/package.Dockerfile, scripts/docker/fedora/33/release.Dockerfile, scripts/docker/fedora/34/package.Dockerfile, scripts/docker/fedora/34/release.Dockerfile, scripts/docker/ubuntu/bionic/package.Dockerfile, scripts/docker/ubuntu/bionic/release.Dockerfile, scripts/docker/ubuntu/focal/package.Dockerfile, scripts/docker/ubuntu/focal/release.Dockerfile, scripts/jenkins/Jenkinsfile, scripts/jenkins/Jenkinsfile.daily, scripts/jenkins/Jenkinsfile.release, scripts/release/release.sh
Part of #3716
- Adds release Docker images that can be used to try out Elektra with multiple distributions
- Fixes a problem with the release script, where if the version codename is not stated in /etc/os-release (e.g. bullseye), it could not be detected and therefore the memcheck failed. (necessary for #3824)
Check relevant points but **please do not remove …
=> docker: add release images for distributions packages are generated for

doc/news/2021-06-07_0.9.6.md, doc/news/_preparation_next_release.md, doc/tutorials/java-plugins.md, scripts/cmake/Modules/LibAddMacros.cmake, src/plugins/jni/CMakeLists.txt, src/plugins/jni/README.md
Many parts of the README.md in the JNI plugins were still wrong (outdated things, not mentioned new requirements, like jna version). This should fix most of it but I did not find a solution to actually mount JNI plugins with Debian Buster yet, see: #3881
For docu fixes, spell checking, and similar none of …
=> JNI docu updates

doc/news/_preparation_next_release.md, doc/tutorials/highlevel.md
The signature of the generated function `loadConfiguration` was changed in 71ecdaf57497775d187d60cefef633aa70ac8ac9. See https://github.com/ElektraInitiative/libelektra/commit/71ecdaf57497775d187d60cefef633aa70ac8ac9#diff-3ce2fe58e9535e358d204695e70faf8635d2191dd5b5ad582c32f8618e54b621R112
This PR updates the tutorial to reflect this change.
=> Update tutorial "High-level API (with code-generation)"

doc/news/_preparation_next_release.md, src/libs/tools/include/specreader.hpp, src/libs/tools/src/specreader.cpp, tests/shell/gen/highlevel/nodefault.data.ini
Improves problems described in #3983 and #3987.
(This PR should not close these issues).
I've implemented several sanity checks in the spec-mounter.
Reviewers will usually check the …
=> Add sanity-checks for keys to "kdb spec-mount" command

doc/METADATA.ini, doc/news/_preparation_next_release.md, src/plugins/range/README.md, src/plugins/range/range.c
Fixes #3984.
Changes the range plugin to use `type` metakey as fallback if `check/type` is not given.
- Add …
=> Use `type` metakey as fallback in range plugin

doc/api_review/core/keyCopyAllMeta.md, doc/api_review/core/keyCurrentMeta.md, doc/api_review/core/keyGetMeta.md, doc/api_review/core/keyMeta.md, doc/api_review/core/keyNextMeta.md, doc/api_review/core/keyRewindMeta.md, doc/api_review/core/keySetMeta.md, doc/news/_preparation_next_release.md, src/libs/elektra/keymeta.c, tests/abi/testabi_meta.c
=> Add additional test cases for module keymeta

doc/decisions/README.md, doc/decisions/error_handling.md, doc/decisions/functions_with_buffers.md, doc/decisions/iterators.md, doc/decisions/key_string_return_value.md, doc/decisions/reference_counting.md, doc/decisions/remove_elektra_malloc.md, doc/news/_preparation_next_release.md
=> doc: add decision docs for decision meeting 15.07.2021

doc/news/_preparation_next_release.md, src/libs/ease/hash.c, tests/ctest/test_hash.c, tests/shell/gen/highlevel/commands.expected.c, tests/shell/gen/highlevel/empty.expected.c, tests/shell/gen/highlevel/enum.expected.c, tests/shell/gen/highlevel/externalspec.expected.c, tests/shell/gen/highlevel/externalwithdefaults.expected.c, tests/shell/gen/highlevel/nosetter.expected.c, tests/shell/gen/highlevel/notype.expected.c, tests/shell/gen/highlevel/simple.expected.c, tests/shell/gen/highlevel/struct.expected.c
=> [FLOSS H3] fix hashing collisions in specification token

doc/news/2021-02-01_0.9.4.md, doc/news/_preparation_next_release.md, scripts/docker/debian/bullseye/doc.Dockerfile, scripts/jenkins/Jenkinsfile
Build the documentation with Debian Bullseye instead of Sid. This fixes #4455.
=> build: use Debian Bullseye to build the documentation (closes #4455)

doc/news/_preparation_next_release.md, src/plugins/specload/specload.c, src/plugins/specload/testmod_specload.c
if parentKey was NULL when calling elektraSpecloadSendSpec dumping the spec failed because the quickdump parent key was not set correctly.
=> specload: don't allow NULL as parameter in elektraSpecloadSendSpec

doc/decisions/README.md, doc/decisions/array.md, doc/decisions/ensure.md, doc/decisions/hooks.md, doc/dev/hooks.md, doc/news/_preparation_next_release.md, src/include/kdbprivate.h, src/libs/elektra/CMakeLists.txt, src/libs/elektra/global.c, src/libs/elektra/hooks.c, src/libs/elektra/kdb.c, src/libs/elektra/plugin.c, src/plugins/gopts/gopts.c, tests/ctest/CMakeLists.txt, tests/ctest/test_hooks.c
This PR aims to provide a basic implementation for the "gopts" hook. In theory it works, but there is still one assert in the test cases that does not, as mentioned in #4412.
This PR should also provide an opportunity to discuss the architecture of hooks in general.
=> Basic implementation of "gopts" hook

doc/help/kdb-get.md, doc/help/kdb-global-umount.md, doc/news/_preparation_next_release.md, src/include/kdbprivate.h, src/libs/elektra/hooks.c, src/libs/elektra/kdb.c, src/plugins/spec/README.md, src/plugins/spec/spec.c, src/plugins/spec/spec.h, src/plugins/spec/testmod_spec.c, tests/ctest/test_hooks.c, tests/shell/check_kdb_internal_check.sh, tests/shell/check_spec_set.sh
This is still a work in progress:
=> [new-backend] spec hook

doc/decisions/README.md, doc/decisions/change_tracking.md, doc/news/_preparation_next_release.md, scripts/sed
=> [decision] Change Tracking

doc/decisions/README.md, doc/decisions/change_tracking.md, doc/decisions/internal_cache.md, doc/decisions/operation_sequences.md, doc/news/_preparation_next_release.md
=> [decisions] sequences of kdbGet and kdbSet operations

doc/decisions/change_tracking.md, doc/decisions/operation_sequences.md, doc/news/2014-09-02_0.8.8.md, doc/news/2022-10-05_0.9.11.md, doc/news/_preparation_next_release.md, scripts/docker/debian/sid/Dockerfile, src/bindings/jna/CMakeLists.txt, tests/linkchecker.whitelist
=> Fix JavaDoc generation on Debian Sid

doc/news/_preparation_next_release.md, scripts/docker/jenkinsnode/Dockerfile
Since the CMake version is now incompatible with the one from the Debian stretch repository, I upgraded the Dockerfile to use Debian bullseye.
The only change in packages was:
* `openjdk-8-jdk-headless` to `openjdk-11-jdk-headless`
I successfully ran
```sh
run-make-env
```
in the container.
=> [FLOSS H2] Upgrade Jenkins node to Debian bullseye

doc/contrib/documentation.md, doc/dev/architecture.md, doc/dev/data-structures.md, doc/news/_preparation_next_release.md, src/plugins/template/README.md
This are just some suggestions for improvements in the course of a review for the PR #4492.
As that PR was already merged, I decided to publish my suggested changes as a new PR.
**Review:**
The content of the documents looks really good. 👍🏻 
I could not find a thing that is unclear or hard to understand, esp. after including the suggestions from other reviews. 💯 
However, I made some changes like adding links, formatting or rephrasing.
Please review my suggested changes, thx!
=> PR#4492 (updates for upcoming release) Review - suggestions

doc/news/_preparation_next_release.md, src/plugins/quickdump/quickdump.c, src/plugins/specload/specload.c, src/plugins/specload/testmod_specload.c
elektraQuickdumpSet always(at the end or on failure) closed `file`, which makes sense, but `file` can be `stdout` in which case it should not be closed.
Should be merge after #4469 since a `TODO` added in acecca9e8f0e56d4aad7cfab76c16f92bc735569 is removed.
=> quickdump: don't close stdout

doc/news/_preparation_next_release.md, src/libs/elektra/keyset.c, tests/ctest/test_ks.c
Fixes the segfault from doing a circular lookup:
```sh
$ kdb meta-set "spec:/circular" "override/#0" "/circular"
$ kdb get "/circular"
```
Note that this only handles the trivial self-reference. Circular lookups with multiple hops still cause havoc:
```sh
$ kdb meta-set "spec:/circular1" "override/#0" "/circular2"
$ kdb meta-set "spec:/circular2" "override/#0" "/circular1"
$ kdb get "/circular1"
```
Nevertheless, I think this is an improvement since the self-reference is certainly more likely than the situation with multiple hops.
=> [FLOSS T1] Fix segfault from circular links (overrides)

doc/news/_preparation_next_release.md, src/plugins/toml/testmod_toml.c, src/plugins/toml/write.c
=> [FLOSS H3] toml: fix silent failure on meta-key insertion

doc/news/_preparation_next_release.md, src/plugins/yajl/testmod_yajl.c, src/plugins/yajl/yajl_gen.c
=> [FLOSS H3] yajl: fix silent failure on meta-key insertion

doc/news/_preparation_next_release.md, src/plugins/date/date.c, src/plugins/date/date.h, src/plugins/date/testmod_date.c
- add tests
- fix an issue where rfc822 dates are not correctly validated
There are also two date types for rfc822 dates which are accepted by the validaton, but invalid according to the specification. I did not change them for now, as I did not want to break backwards compatibility. I commented this on the affected test cases. 
- We found the bug by wanting to improve the code coverage to the date plugin
- tests run on jenkins and cirrus-ci
- we split the test cases we wrote and identified and fixed the issue together
=> [FLOSS T1] plugin: date: Fix rfc822 validation issue

.github/workflows/stale.yml, doc/news/_preparation_next_release.md
Fixes the remaining issues of #4476.
* Update action to latest version.
* Now closes issues as "not planned".
Closes #4476
- [] Short descriptions of your changes are in the release notes
=> GitHub actions: Update stale issue/PR action

doc/decisions/0_drafts/operation_sequences.md, doc/decisions/1_in_discussion/change_tracking.md, doc/decisions/2_in_progress/copy_on_write.md, doc/news/_preparation_next_release.md
=> [decision]: Changetracking (round 2)

doc/man/man7/elektra-libs.7, doc/news/_preparation_next_release.md, examples/CMakeLists.txt, examples/cmerge.c, src/bindings/swig/python/merge.i, src/include/kdbmerge.h, src/libs/README.md, src/libs/merge/kdbmerge.c, src/libs/merge/symbols.map, src/tools/kdb/cmerge.cpp, tests/ctest/test_merge.c
=> cmerge: add methods to get all conflicting keys

src/include/CMakeLists.txt, src/include/kdbmount.h, src/libs/elektra/CMakeLists.txt, src/libs/elektra/cmount.c, src/libs/elektra/symbols.map, src/tools/kdb/command.c, src/tools/kdb/command.h, src/tools/kdb/main.c, src/tools/kdb/mount.c, src/tools/kdb/mount.h, src/tools/kdb/mountpoint-list.c, src/tools/kdb/mountpoint-list.h, src/tools/kdb/mountpoint-mount.c, src/tools/kdb/mountpoint.c, src/tools/kdb/mountpoint.h
Implements code for listing mountpoints and mounting new files (includes plugin-resolution and -handling for mounting) in C.
Most of the C++-based code is now implemented in C, but there is still some work left, including testing, and refactoring.
I'll write a posting in this PR and add the label `needs review` as soon as
- I've successfully finished and
- refactored the implementation,
- tested some use cases and
- reviewing seems feasible.
Thank you!
=> WIP: Mount cli integration in C

doc/news/_preparation_next_release.md, doc/tutorials/install-webui.md, src/tools/elektrad/helper_test.go, src/tools/elektrad/meta_handler.go, src/tools/elektrad/meta_handler_test.go, src/tools/elektrad/router.go, src/tools/webd/package-lock.json, src/tools/webd/src/connector.js, src/tools/webd/src/routes/instances.js
=> `Webd` and `elektrad` bulk kdb meta-set

doc/news/_preparation_next_release.md, tests/shell/external/example_codegen_econf_empty_array_spec.sh
=> Add shell test case for parent array spec bug

doc/dev/algorithm.md, doc/help/elektra-bootstrapping.md, doc/help/kdb-convert.md, doc/help/kdb-editor.md, doc/help/kdb-export.md, doc/help/kdb-import.md, doc/man/man1/kdb-convert.1, doc/man/man1/kdb-editor.1, doc/man/man1/kdb-export.1, doc/man/man1/kdb-import.1, doc/man/man7/elektra-bootstrapping.7, doc/news/2016-04-29_0.8.16.md, doc/news/_preparation_next_release.md, doc/tutorials/contributing-clion.md, scripts/change-resolver-symlink.in, scripts/change-storage-symlink.in, scripts/cmake/Modules/LibAddPlugin.cmake, scripts/cmake/Modules/PackagingFedora.cmake, src/libs/loader/dl.c, src/plugins/CMakeLists.txt
=> Set new target name for so files (#3486)

doc/news/_preparation_next_release.md, src/libs/elektra/kdb.c
=> lib: memory leak, fixes #4925

doc/news/_preparation_next_release.md, scripts/docker/openwrt/sdk/Dockerfile
This PR tries to fix #4958 by replacing the `openwrtorg/sdk` with the `openwrt/sdk` docker image.
=> Replace openwrt image

doc/news/_preparation_next_release.md, scripts/docker/cirrus/arch/Dockerfile, src/libs/elektra/keyname.c
This PR contains three fixes for errors with recent build jobs on Cirrus.
1. Please see the issue #4966 for a detailed description of the bug in the Doxygen comment that gets fixed by this PR.
2. Additionally, I've noticed that the current Cirrus jobs are canceled because the
package `texlive-most` is not available anymore.
Therefore, I replaced it with `texlive-core`, `texlive-bin`, `texlive-latexextra` and `texlive-fontsextra` in the Dockerfile for Arch Linux on Cirrus.
3. Include the header `cstdint` to /src/bindings/cpp/include/key.hpp.
This is needed for the enum in that file that uses the `std::uint8_t` type.
(first line should have `module: short …
=> [CI] Fix bugs that lead to errors on Cirrus jobs (esp. building PDF documentation)

doc/news/_preparation_next_release.md, doc/tutorials/README.md, doc/tutorials/xfconf.md
This PR adds a tutorial for Xfconf as mentioned in issue #280.
=> Xfconf Tutorial

doc/contrib/README.md, doc/contrib/contrib-glossary.md, doc/dev/README.md, doc/dev/dev-glossary.md, doc/help/elektra-glossary.md, doc/news/_preparation_next_release.md
=> doc: add glossaries for contrib and dev

doc/CONTRACT.ini, doc/news/_preparation_next_release.md, src/plugins/c/CMakeLists.txt, src/plugins/c/README.md, src/plugins/c/c.c, src/plugins/c/c.h, src/plugins/c/testmod_c.c
- some small refactoring (e.g. remove unnecessary dups, reduce scope of variables)
- add code documentation (Doxygen)
- extended README.md
- add unit tests
=> Plugins: Improve c plugin (doc, tests, refactor)

doc/news/_preparation_next_release.md, src/bindings/rust/elektra-sys/Cargo.toml.in
=> bindings/rust: upgrade bindgen version
