ElektraInitiative/libelektra

src/bindings/gi/lua/lgi/override/GElektra.lua
src/bindings/gi/lua/testgi_key.lua
src/bindings/gi/python3/gi/overrides/GElektra.py
src/bindings/gi/python3/testgi_key.py
src/bindings/glib/gelektra-key.c
src/bindings/glib/gelektra-key.h
src/bindings/swig/common.i
src/bindings/swig/lua/kdb.i
src/bindings/swig/lua/tests/test_key.lua
src/bindings/swig/python2/kdb.i
src/bindings/swig/python2/tests/testpy2_key.py
src/bindings/swig/python3/kdb.i
src/bindings/swig/python3/tests/test_key.py

... and deprecate all other flags

implement KEY_FLAGS for gi and swig

---

doc/AUTHORS

PR for testing jenkins custom triggers

add my e-mail address

---

src/libelektra/backend.c
src/libelektra/kdb.c
src/libelektra/keyhelpers.c
src/libelektra/split.c
src/plugins/resolver/resolver.c
src/plugins/uname/uname.c

the first is a no-brainer, but let jenkins verify the 2nd one

two small bugfixes

---

src/bindings/glib/gelektra-keyset.c
src/bindings/swig/CMakeLists.txt
src/bindings/swig/lua/CMakeLists.txt
src/bindings/swig/python2/CMakeLists.txt
src/bindings/swig/python3/CMakeLists.txt
src/bindings/swig/python3/kdb.i
src/include/kdbconfig.h.in

swig: fix + hide warnings

---

src/plugins/rename/README.md
src/plugins/rename/rename.c
src/plugins/rename/testmod_rename.c

Fixed an issue in rename that caused the parentKey value to be discarded

---

src/tools/race/race.c

fix compilation of race tool under oS-11.4

---

cmake/Modules/LibAddTest.cmake
doc/NEWS.md
src/libelektra/key.c
src/libelektra/keyname.c
src/libelektra/plugin.c

- "allows to" -> "allows one to"
- "informations" -> "information"

A couple of typo fixes

---

examples/functional.c
src/libelektra/backend.c
src/libelektra/internal.c
src/libelektra/key.c
src/libelektra/keymeta.c
src/libelektra/keyname.c
src/libelektra/keyset.c
src/libelektra/keytest.c
src/libelektra/keyvalue.c
src/libelektra/meta.c
src/libelektra/mount.c
src/libelektra/plugin.c
src/libelektra/split.c
src/plugins/doc/doc.h
src/plugins/iconv/iconv.c
src/plugins/resolver/filename.c
src/plugins/resolver/resolver.c
src/plugins/xmltool/stream.c
tests/cframework/tests.c
tests/cframework/tests.h

Switch from `@return` to `@retval` in more places, so return values are properly marked.

doc: use @retval more

---

doc/COMPILE.md
scripts/configure-debian
src/bindings/swig/python2/CMakeLists.txt
src/bindings/swig/python3/CMakeLists.txt

Also adds a bit of documentation about SWIG_EXECUTABLE cmake variable

Issue a warning if SWIG 2 will generate the python bindings

---

src/bindings/swig/lua/examples/example_key.lua
src/bindings/swig/lua/examples/example_keyset.lua
src/bindings/swig/lua/tests/test_key.lua
src/bindings/swig/lua/tests/test_keyset.lua
src/bindings/swig/python2/tests/testpy2_key.py
src/bindings/swig/python2/tests/testpy2_keyset.py
src/bindings/swig/python3/examples/example_key.py
src/bindings/swig/python3/examples/example_keyset.py
src/bindings/swig/python3/kdb.i
src/bindings/swig/python3/tests/test_key.py
src/bindings/swig/python3/tests/test_keyset.py

swig-python: add support for copy module

---

doc/NEWS.md
src/bindings/cpp/include/key.hpp
src/bindings/swig/lua/kdb.i
src/bindings/swig/lua/tests/test_key.lua
src/bindings/swig/python2/tests/testpy2_key.py
src/bindings/swig/python3/kdb.i
src/bindings/swig/python3/tests/test_key.py

first commit adds support for python.

add support for key name iterator

---

src/plugins/python/python.cpp

don't do any python calls if script instance hasn't been created

fix python crash

---

CMakeLists.txt

this should fix `kdb` as well #270

fix OS X RPATH issues

---

src/tools/kdb/metals.cpp

This commit should fix the error I reported in Issue #318

Fix `kdb lsmeta` Segfault.

---

src/plugins/csvstorage/README.md
src/plugins/csvstorage/csvstorage.c
src/plugins/csvstorage/testmod_csvstorage.c

added an option to set a fixed number of columns, everything that has more or less columns gets rejected.

set fix number of column count for Csvstorage

---

src/libelektra/backend.c
src/plugins/resolver/resolver.c
src/plugins/resolver/testmod_resolver.c
src/tools/qt-gui/qml/AboutWindow.qml
src/tools/qt-gui/qml/main.qml
tests/kdb/testkdb_simple.cpp

qt-gui: fix search results bug

---

doc/CMakeLists.txt
doc/Doxyfile
doc/markdownlinkconverter/README.md
doc/markdownlinkconverter/elektraSpecialCharacters.sty
doc/markdownlinkconverter/markdownlinkconverter.c

fixed #345 and manual invocation improved

fix issue 345

---

doc/NEWS.md
doc/tutorials/plugins.md
src/plugins/ccode/README.md
src/plugins/iconv/README.md

fix UTF-8 and characters mess

---

src/plugins/ini/README.md
src/plugins/ini/ini.c
src/plugins/ini/ini/emptySectionBugTest
src/plugins/ini/ini/plaininireverse
src/plugins/ini/inih-r29/inih.c
src/plugins/ini/inih-r29/inih.h
src/plugins/ini/testmod_ini.c

using the `meta` config key the ini plugin gets turned into ni

metakey support added to ini plugin

---

src/plugins/ini/README.md
src/plugins/ini/ini.c
src/plugins/ini/inih-r29/inih.c
src/plugins/ini/testmod_ini.c

just a draft, ignore syntax/formating problems and memleaks

INI: subkey draft

---

doc/AUTHORS
src/plugins/dbus/README.md
src/plugins/dbus/dbus.c
src/plugins/dbus/dbus.h
src/plugins/dbus/sendmessage.c
src/plugins/dbus/testmod_dbus.c

Added new notifications features and updated the README to reflect the changes

Updated DBus plugin

---

src/plugins/crypto/testmod_crypto.c

fixed the warnings reported in #391

crypto-plugin: fix compiler warning (issue #391)

---

src/bindings/glib/CMakeLists.txt
src/bindings/swig/lua/CMakeLists.txt
src/bindings/swig/python/CMakeLists.txt
src/bindings/swig/python2/CMakeLists.txt

Last one for today. Please merge *after* libproposal issue has been solved. Otherwise gi-bindings won't work anymore.
Edit: Or reject in case you don't think it's worth it :-)

bindings: only link against lib-core and lib-kdb

---

src/plugins/rename/README.md
src/plugins/rename/rename.c
src/plugins/rename/rename.h
src/plugins/rename/testmod_rename.c

added:
renaming of keys
toupper conversion
tolower conversion

RENAME: some enhancements

---

doc/help/kdb-list.md

This is a fix for #420. 
<sub>Also: My first Github pull-request.</sub>

Fix documentation text for "kdb list"

---

src/plugins/crypto/crypto.c
src/plugins/crypto/gcrypt_operations.c
src/plugins/crypto/testmod_crypto.c

crypto-plugin: fix compile error for wheezy #453

---

src/plugins/crypto/README.md
src/plugins/crypto/contract.h

set plugin status as discussed in #416.

set plugin status for crypto-plugin (see #416)

---

doc/AUTHORS
src/plugins/crypto/README.md
src/plugins/crypto/crypto.h
src/plugins/crypto/testmod_crypto.c

as requested per mail today, I shortened the config paths for the crypto plugin

shorten config path in crypto plugin

---

src/plugins/list/list.c

@markus2330 
ok, i guess i got it now, not sure what went wrong last time, probably some issue with my 37 local branches and installed binaries

LIST: invalid free fix #464

---

cmake/ElektraCache.cmake
src/error/specification
src/plugins/README.md
src/plugins/spec/CMakeLists.txt
src/plugins/spec/README.md
src/plugins/spec/metafunctions.c
src/plugins/spec/metafunctions.h
src/plugins/spec/spec.c
src/plugins/spec/spec.h
src/plugins/spec/test/spec.ini
src/plugins/spec/test/spectest.ini
src/plugins/spec/test/spectest.sh
src/plugins/spec/testmod_spec.c

needs better config key names.

spec plugin

---

doc/markdownlinkconverter/README.md
doc/markdownlinkconverter/markdownlinkconverter.c

Add support for plugin README.mds

MLC: plugin titles

---

src/plugins/crypto/README.md

documents the changes that have been made to the CMakeLists.txt file during #487 .

update crypto-plugin's README.md

---

doc/API.md
doc/CMakeLists.txt
doc/COMPILE.md
doc/decisions/relative.md
doc/decisions/specification.md
doc/decisions/unit_testing.md
doc/help/elektra-algorithm.md
doc/help/elektra-architecture.md
doc/help/elektra-classes.md
doc/help/elektra-data-structures.md
doc/tutorials/application-integration.md
doc/tutorials/elektra-merge-integration.md
doc/tutorials/export.md
examples/keyNew.c
src/include/kdbplugin.h
src/libs/README.md
src/libs/elektra/keyset.c
src/libs/getenv/README.md
src/plugins/augeas/README.md
src/plugins/ccode/README.md
src/plugins/csvstorage/README.md
src/plugins/doc/doc.h
src/plugins/dump/README.md
src/plugins/error/README.md
src/plugins/glob/README.md
src/plugins/hexcode/README.md
src/plugins/iconv/README.md
src/plugins/ini/README.md
src/plugins/jni/README.md
src/plugins/keytometa/README.md

Hi,
the following commits contain minor updates to the documentation. If there are any questions about the changes, please just comment below. Thanks.

Fix Minor Mistakes in Documentation

---

doc/NEWS.md

Mainly typo fixes in the release notes

small release-notes fixes

---

cmake/ElektraCache.cmake
doc/CONTRACT.ini
doc/NEWS.md
doc/SECURITY.md
doc/decisions/bootstrap.md
doc/help/elektra-algorithm.md
doc/help/elektra-namespaces.md
doc/help/kdb.md
doc/old/NEWS.md
scripts/filter-coverage.awk.in
src/bindings/jna/CMakeLists.txt
src/libs/elektra/keyname.c
src/plugins/resolver/README.md
src/plugins/resolver/filename.c
src/tools/qt-gui/qml/Page3.qml
src/tools/qt-gui/qml/i18n/lang_de_DE.ts
tests/gtest-framework/gtest/gtest-elektra.h
tests/shell/check_resolver.sh

This pull request contains various minor improvements to the documentation. If you think the changes in commit 6f77d53 do not improve the release notes, then please just do not merge them.

Small Fixes for Documentation

---

src/bindings/README.md
src/plugins/README.md

doc: add list of supported bindings

---

src/plugins/list/CMakeLists.txt

fixes #516 but doesn't look extremely nice
I'm thinking maybe we should make a macro for describing the dependencies of a plugin. I haven't seen dependency checking in any of the other plugins. Any thoughts?

fixes #516

---

src/plugins/conditionals/conditionals.c
src/plugins/simpleini/CMakeLists.txt
tests/shell/check_resolver.sh
tests/shell/include_common.sh.in

fixing tests on OS X

---

scripts/benchmark_augeas_hosts.sh
src/plugins/augeas/augeas.c

The PR contains a small script (should be sh compatible :)) for benchmarking the augeas plugin performance with a provided hosts file. While analysing the plugin with callgrind I realised that an easy performance improvement can be made which is also included.

Benchmark script and performance improvement for augeas plugin

---

cmake/ElektraCache.cmake
src/plugins/README.md
src/plugins/dpkg/CMakeLists.txt
src/plugins/dpkg/README.md
src/plugins/dpkg/dpkg.c
src/plugins/dpkg/dpkg.h
src/plugins/dpkg/testmod_dpkg.c
tests/shell/include_common.sh.in

mounts /var/lib/dpkg/{available,status} (read only)

dpkg plugin

---

src/plugins/ini/ini.c
tests/shell/check_export.sh
tests/shell/check_import.sh
tests/shell/shell/again_two_value.ini

Works as default storage now + all unit tests are working.
the only issue left is the metadata added by the plugin used for ordering.

INI: fixed sections and ordering

---

src/bindings/jna/elektra/Elektra.java
src/bindings/jna/elektra/KDB.java
src/bindings/jna/elektra/Key.java
src/bindings/jna/elektra/KeyNameIterator.java
src/bindings/jna/elektra/KeySet.java
src/bindings/jna/elektra/KeySetIterator.java
src/bindings/jna/elektra/test/AllTests.java
src/bindings/jna/elektra/test/KeySetTest.java
src/bindings/jna/elektra/test/KeyTest.java
src/bindings/jna/elektra/test/README.md

Most stuff should work now as expected. I updated the code docs to contain all important information of the c-docs and split the updates into single commits.

jUnit tests for JNA binding + code docs + small bugfixes

---

src/libs/meta/meta.c
tests/ctest/test_meta.c

@markus2330 
not really sure how to implement actual tests for that part so for now there are just debug outputs for proof.
can you take a look and tell me if the way it works is fine with you ? i'll reformat it and remove the outputs afterwards

Topological search ordering

---

src/bindings/glib/gelektra-keyset.c
src/bindings/glib/gelektra-keyset.h

... and make gobject introspection happy again
fixes #573

glib: replace cursor_t with gssize

---

src/libs/meta/meta.c
tests/ctest/test_meta.c

@markus2330, can you give it a try ? 
Not sure if it's an issue, but dependencies that can be resolved immediately will be resolved, so the KeySet
```
ksNew (
10, keyNew ("/a", KEY_VALUE, "b", KEY_META, "dep", "#0", KEY_META, "dep/#0", "/b", KEY_META, "order", "#0", KEY_END),
keyNew ("/b", KEY_VALUE, "d", KEY_META, "dep", "#0", KEY_META, "dep/#0", "/d", KEY_META "order", "#1", KEY_END),
keyNew ("/c", KEY_VALUE, "-", KEY_META, "order", "#3", KEY_END), 
keyNew ("/d", KEY_VALUE, "-", KEY_META, "order", "#2", KEY_END), 
KS_END);
```
will result in 
`c -> d -> b -> a`
instead of
`d -> b -> a -> c`
```
KEY META     TESTS
==================
---- TEST 1 ----
-------NEW: 183519
-------OLD: 474165
---- TEST 2 ----
-------NEW: 277925
-------OLD: 1374282
---- TEST 3 ----
-------NEW: 188224 …
```

Improved topological search

---

src/include/kdbease.h
src/libs/ease/keyname.c
src/plugins/ni/CMakeLists.txt
src/plugins/ni/ni.c
tests/ctest/CMakeLists.txt
tests/ctest/test_keyname.c

(This time) I added some tests for `elektraKeyGetRelativeName`. If I should change anything, then please just comment below.

Move elektraKeyGetRelativeName to Libease

---

tests/ctest/test_keyname.c

Hope this does not break anything :).

Libease: Minor Changes for `test_keyname`

---

src/libs/elektra/keytest.c
tests/abi/testabi_key.c

rewrote keyIsBelow because there were still some cascading edge cases missing + tests

keyIsBelow fix + tests

---

src/bindings/cpp/include/kdb.hpp
src/libs/tools/include/merging/mergingkdb.hpp
src/libs/tools/src/merging/mergingkdb.cpp
src/libs/tools/tests/testtool_mergingkdb.cpp
src/tools/qt-gui/src/main.cpp
src/tools/qt-gui/src/treeviewmodel.cpp
src/tools/qt-gui/src/treeviewmodel.hpp

Because of #603 I could not fully test the qt-gui update, however the wrapper should provide a good starting ground to easily test KDB synchronisations.

Kdb sync in libtools

---

src/plugins/conditionals/conditionals.c

This should take care of issue #610. If there is anything I should change in the pull request, then please comment below.

Conditionals Plugin: Fix OS X specific problems

---

src/libs/elektra/kdb.c

@markus2330 
this seems to fix most issues. there are still a few memleaks i have a hard time finding though.
can you give it a try to see if it solves the problems ?

fix global hooks

---

src/plugins/tcl/CMakeLists.txt

tcl plugin: include Boost headers, fixes #648

---

doc/COMPILE.md

add OpenBSD note to doc/COMPILE.md

---

src/libs/elektra/mount.c

ok, that was a really stupid mistake...

fix #523 again

---

src/error/specification
src/plugins/crypto/gcrypt_operations.c
src/plugins/crypto/openssl_operations.c

crypto-plugin: replace plugin-specific error numbers with macros

---

scripts/metaini-to-c

is there any use for that script ? 
it basically parses METADATA.ini und outputs c arrays. One is just the metakey names for storage plugins to check if the data should be written or not, one is metakey name + usedby/plugin, and one metakey + usedby/api

metaini to c array

---

tests/shell/check_get_set.sh

should fix at least the seq problem from #656

remove seq, blind fix for #656

---

src/plugins/yajl/CMakeLists.txt

fixes #711: add yajl include dir to module tests

---

src/bindings/glib/CMakeLists.txt
src/bindings/glib/tests/CMakeLists.txt

glib: make sure we use all definitions returned by pkg-config

---

cmake/Modules/FindLua.cmake

fix #745 'empty LUABIN_VERSION_STRING'

---

src/bindings/jna/elektra/Elektra.java

fix jna load library

---

doc/decisions/cryptograhic_key_handling.md

adding a decision as requested on the mailing list.

document decision about cryptographic key handling (crypto plugin)

---

doc/NEWS.md

add experimental GSettings notes to release notes for 0.8.17

Release Notes: add information regarding experimental gsettings backend

---

doc/GIT.md
doc/help/elektra-plugins-framework.md

link trigger phrases to build jobs
fixes #749

doc: add jenkins build trigger phrase documentation

---

doc/GIT.md

The commit message guidelines are based on:
- https://www.git-scm.com/book/en/v2/Distributed-Git-Contributing-to-a-Project#Commit-Guidelines
- http://chris.beams.io/posts/git-commit/
Fixes #790

doc: describe how commit messages should look

---

src/tools/qt-gui/CMakeLists.txt

Elektra Qt Editor: add optional svg component in cmake

---

src/bindings/gsettings/elektrasettingsbackend.c

Sorry this is a bad one that slipped us on 5b3aa15ad7b03812fb564db6c8de523bd8ee50f7

GSettings Backend: fix double free on get writable

---

src/plugins/augeas/augeas.c

This PR should fix #798. Please note the use of goto for memory allocation error handling. I know it is not perfect, but neither are the other solutions.

Fix unused result warnings in augeas

---

scripts/CMakeLists.txt
scripts/kdb_zsh_completion

@markus2330 some things are working, but there are also others missing...
I'm not sure if the install is correct... should i have left out the /usr?

zsh completion WIP

---

doc/AUTHORS

as requested earlier today at the Elektra meeting

add github user to AUTHORS

---

scripts/kdb_zsh_completion

small change to make the zsh completion work in zsh -f

zsh completion, fix = not found

---

src/plugins/conditionals/README.md

conditionals also works as global plugin, i've updated the readme with an example.

CONDITIONALS: updated README

---

src/plugins/crypto/CMakeLists.txt
src/plugins/crypto/openssl_operations.c
tests/valgrind.suppression

Yet Another Memory Leak ( #840 )

---

tests/shell/shell_recorder/README.md
tests/shell/shell_recorder/shell_recorder.sh

setting File to mktemp provides a fresh database temp file for ever run

Shell Recorder: File: mktemp feature

---

src/error/specification
src/plugins/README.md
src/plugins/passwd/CMakeLists.txt
src/plugins/passwd/README.md
src/plugins/passwd/hasfgetpwent.c
src/plugins/passwd/hasputpwent.c
src/plugins/passwd/passwd.c
src/plugins/passwd/passwd.h
src/plugins/passwd/passwd/passwd_in
src/plugins/passwd/passwd/passwd_out
src/plugins/passwd/testmod_passwd.c
tests/shell/include_common.sh.in

will add unittests later
can someone with a system not supporting fgetpwent/putpwent test the cmake code ?
EDITED

passwd plugin

---

examples/spec/highlevel.ini
examples/spec/locationtracker.ini

updated `examples/spec` files to new `conditionals` syntax

adjusted examples/spec to new conditionals syntax

---

scripts/ffconfig/setupConfig
scripts/ffconfig/setupHomepage
scripts/ffconfig/setupProxy
src/plugins/mozprefs/autoconfig/README.md

Fixed locking values at runtime
seems like i screwed up and FF supports locking existing values

configure-firefox: fixed locking preferences

---

src/plugins/conditionals/README.md

Fixed example in README after changing plugin syntax

conditionals: fixed README example

---

doc/decisions/README.md
doc/decisions/api_documentation.md

Decision on how to document APIs.

Decision: API documentation

---

src/libs/meta/meta.c
src/plugins/filecheck/filecheck.c

Fix warnings openwrt

---

tests/shell/shell_recorder/shell_recorder.sh

fixes based on @KurtMi 's post in #807
(shellcheck currently seems to be broken at my system)

shell_recorder: fix shellcheck warnigns

---

src/plugins/crypto/gpg.c
src/plugins/crypto/openssl_operations.c
tests/valgrind.suppression

Fixes some mistakes detected by valgrind.
Updates the suppressions file.
Fixes #932 .

Memleak Crypto Plugin

---

src/tools/kdb/CMakeLists.txt

Build improvement for the KDB tool through usage of an object library.

Build improvement: object library for kdb tool

---

src/error/specification
src/plugins/README.md
src/plugins/boolean/CMakeLists.txt
src/plugins/boolean/README.md
src/plugins/boolean/boolean.c
src/plugins/boolean/boolean.h
src/plugins/boolean/testmod_boolean.c

canonicalizes boolean values, see #308

boolean: initial commit

---

src/plugins/mathcheck/mathcheck.c
src/plugins/mathcheck/testmod_mathcheck.c

fixed #653 + some other issues and a broken unittest

mathcheck: fix #653 + many other things

---

src/include/kdbtypes.h

fix openwrt warnings

---

src/plugins/crypto/botan_operations.cpp
src/plugins/crypto/crypto.c
src/plugins/crypto/gcrypt_operations.c
src/plugins/crypto/gpg.c
src/plugins/crypto/gpg.h
src/plugins/crypto/helper.c
src/plugins/crypto/helper.h
src/plugins/crypto/openssl_operations.c
src/plugins/crypto/test_internals.h

Make exported function names unique by using the `CRYPTO_PLUGIN_FUNCTION` macro.
See #951 for full discussion.

crypto-plugin: fix static link issues

---

src/error/specification
src/plugins/README.md
src/plugins/blockresolver/CMakeLists.txt
src/plugins/blockresolver/README.md
src/plugins/blockresolver/blockresolver.c
src/plugins/blockresolver/blockresolver.h
src/plugins/blockresolver/blockresolver/compare.block
src/plugins/blockresolver/blockresolver/test.block
src/plugins/blockresolver/testmod_blockresolver.c

```
% cat /tmp/test.block
bla
bla
bla
[section1]
key1 = val1
[section2]
key2 = val2
asdf
asdf
asdf
% kdb mount -R blockresolver /tmp/test.block system/blocktest -c identifier="### block config"
% kdb export system/blocktest
[section1]
key1 = val1
[section2]
key2 = val2
% kdb set system/blocktest/section1/key12 val12
Create a new key system/blocktest/section1/key12 with string val12
% cat /tmp/test.block
bla
bla
bla
[section1]
key1 = val1
key12 = val12
[section2]
key2 = val2
asdf
asdf
asdf
```

blockresolver

---

scripts/configure-xdg

XDG build: add plugins as workaround for shellrecorder

---

doc/AUTHORS

Added myself to AUTHORS
not really sure what else to write.

Added myself to AUTHORS

---

src/plugins/spec/spec.c

spec: keep metadata

---

src/error/specification
src/plugins/README.md
src/plugins/crypto/gpg.c
src/plugins/fcrypt/CMakeLists.txt
src/plugins/fcrypt/README.md
src/plugins/fcrypt/contract.h
src/plugins/fcrypt/fcrypt.c
src/plugins/fcrypt/fcrypt.h
src/plugins/fcrypt/testmod_fcrypt.c

The `fcrypt` plugin enables file based encryption and decryption.
See #914 for full discussion.
Closes #914 .

Fcrypt file encryption plugin

---

doc/usecases/TEMPLATE.md
doc/usecases/snippet_sharing/UC_authenticate.md
doc/usecases/snippet_sharing/UC_convert_snippet.md
doc/usecases/snippet_sharing/UC_create_snippet.md
doc/usecases/snippet_sharing/UC_delete_snippet.md
doc/usecases/snippet_sharing/UC_details_snippet.md
doc/usecases/snippet_sharing/UC_download_snippet.md
doc/usecases/snippet_sharing/UC_duplicate_snippet.md
doc/usecases/snippet_sharing/UC_edit_snippet.md
doc/usecases/snippet_sharing/UC_edit_user.md
doc/usecases/snippet_sharing/UC_register.md
doc/usecases/snippet_sharing/UC_reset_password.md
doc/usecases/snippet_sharing/UC_search_snippet.md
doc/usecases/snippet_sharing/UC_search_user.md
doc/usecases/snippet_sharing/distinction_use_cases.md

Use cases for sharing of configuration snippets.

Use cases: sharing of configuration snippets

---

tests/shell/shell_recorder/db_changes.esr
tests/shell/shell_recorder/hosts.esr
tests/shell/shell_recorder/listtest.esr
tests/shell/shell_recorder/mathcheck.esr
tests/shell/shell_recorder/script.esr

fixed shellrecorder tests

---

src/error/specification
src/plugins/augeas/contract.h
src/plugins/glob/README.md
src/plugins/glob/glob.c
src/plugins/glob/glob.h
src/plugins/glob/testmod_glob.c
src/plugins/hosts/README.md
src/plugins/hosts/contract.h
src/plugins/keytometa/README.md

Fixes the issues described in #709. 

Globbing flag fix

---

src/plugins/ini/ini.c

INI: dont alloc array for keysize == 0

---

src/plugins/conditionals/conditionals.c
src/plugins/conditionals/testmod_conditionals.c

conditionals: fix regex

---

scripts/update-infos-status

Does the nodoc part of the devils issue #666

scripts: update-info-status: nodoc

---

doc/CMakeLists.txt
doc/markdownlinkconverter/README.md
doc/markdownlinkconverter/markdownlinkconverter.c
scripts/link-checker
src/error/exporterrors.cpp

* stat files
* cleanup external-links.txt
* link checker: fix fales positive

Markdownlink Converter

---

src/plugins/lua/README.md
src/plugins/python/README.md

Improve plugin readme of lua and python plugin. This PR should solve #1106.

readme improvements for lua & python plugin

---

src/plugins/mathcheck/mathcheck.c
src/plugins/mathcheck/testmod_mathcheck.c

fix #1094 (../ multiple times)

mathcheck: fixed regex (fix #1094)

---

src/plugins/fcrypt/testmod_fcrypt.c

This should finally resolve #1113 .

fcrypt: use elektraFilename () in test cases

---

src/include/kdbopmphm.h
src/include/kdbprivate.h
src/libs/elektra/opmphm.c
src/libs/elektra/opmphm_vheap.c
src/libs/elektra/opmphm_vstack.c
tests/ctest/test_opmphm_vheap.c
tests/ctest/test_opmphm_vstack.c

Trie removed from doxygen, due to be internal and no doc.

OPMPHM: remove kdbprivate include, refactor vstack vheap

---

cmake/Modules/FindLibJWT.cmake
src/tools/rest-backend/authentication_application.cpp
src/tools/rest-backend/config-specification.ini

Should fix #1145 and solves #1144.

rest-backend: fix build and config

---

src/tools/rest-frontend/public/assets/translations/en.json
src/tools/rest-frontend/public/pages/main/error/404.html
src/tools/rest-frontend/public/pages/main/error/template.html
src/tools/rest-frontend/resources/assets/js/config/routes.js
src/tools/rest-frontend/resources/assets/skin/base/theme.less

Adds 404 Not Found page to the rest-frontend.

rest-frontend: add 404 page

---

src/tools/rest-backend/benchmarks/benchmark_kdbrest_mysql.cpp
src/tools/rest-backend/benchmarks/testdata.cpp
src/tools/rest-backend/conversion_application.cpp
src/tools/rest-backend/database_application.cpp
src/tools/rest-backend/model_entry.hpp
src/tools/rest-backend/model_user.hpp
src/tools/rest-backend/service.hpp
src/tools/rest-backend/service_convert.cpp
src/tools/rest-backend/service_storage.cpp
src/tools/rest-backend/tests/test_model_entry.cpp
src/tools/rest-backend/tests/test_service_configengine.cpp
src/tools/rest-backend/tests/test_service_convertengine.cpp

This PR adds some tests for the conversion (they only run if the required plugins are available). It does also fix the import / conversion issue mentioned in #1151.

rest-backend: add conversion tests + fix issues

---

src/tools/rest-backend/benchmarks/benchmark_kdbrest_elektra.cpp
src/tools/rest-backend/benchmarks/benchmark_kdbrest_mysql.cpp
src/tools/rest-backend/benchmarks/testdata.cpp

This PR fixes some issues with the rest-backend benchmarks and adds some speed improvements (in the prepare-test-data section). Details can be found in the commit messages.

rest-backend: benchmark fixes and improvements

---

src/tools/rest-backend/root_application.cpp

rest-backend: dispatch api description with and without trailing slash

---

src/tools/qt-gui/qml/i18n/lang_es.ts

Added Spanish Translation of qt-gui #682 
- [ x ] i18n spanish

Added Spanish Translation of qt-gui #682

---

doc/tutorials/snippet-sharing-rest-service.md
scripts/build-homepage

Description of the libelektra website setup added to the snippet sharing tutorial.

snippet-sharing: tutorial updated (added libelektra setup)

---

scripts/build-homepage
src/tools/rest-backend/config-specification.ini.in
src/tools/rest-backend/main.cpp
src/tools/rest-backend/run.sh
src/tools/rest-backend/stop.sh

The PR should fix the issue that the backend dies at the end of the build.

rest-backend: ensure backend starts daemonized

---

src/plugins/csvstorage/csvstorage.c
src/plugins/csvstorage/csvstorage/complicated.csv
src/plugins/csvstorage/csvstorage/unescapedQuote.csv
src/plugins/csvstorage/testmod_csvstorage.c

improvements according to RFC 4180

CSVStorage improvements

---

src/plugins/conditionals/CMakeLists.txt
src/plugins/conditionals/README.md
src/plugins/conditionals/conditionals.c
src/plugins/conditionals/testmod_conditionals.c

allow multiple conditionals in meta arrays

Conditionals multi

---

scripts/CMakeLists.txt
scripts/build-homepage
scripts/update-snippet-repository
src/tools/rest-backend/config.hpp.in
src/tools/rest-backend/conversion_application.cpp
src/tools/rest-backend/database_application.cpp
src/tools/rest-backend/model_pluginformat.hpp
src/tools/rest-backend/service.hpp
src/tools/rest-backend/service_convert.cpp
src/tools/rest-backend/service_storage.cpp

Adds auto-commit script for a snippet git-repo as mentioned in #1179.

snippet-sharing: auto-commit script for git repo

---

scripts/build-homepage
src/tools/rest-frontend/Gruntfile.js
src/tools/rest-frontend/public/assets/translations/en.json
src/tools/rest-frontend/public/pages/main/template.html
src/tools/rest-frontend/public/pages/main/website/home.html
src/tools/rest-frontend/resources/assets/html/index.html.in
src/tools/rest-frontend/resources/assets/js/services/EntryService.js

Some improvements mentioned in #1151 and #1153. See commit messages for further details.

rest-frontend: improvements

---

src/tools/rest-backend/authentication_application.cpp
src/tools/rest-backend/database_application.cpp
src/tools/rest-backend/main.cpp
src/tools/rest-backend/root_application.cpp
src/tools/rest-backend/root_application.hpp
src/tools/rest-backend/user_application.cpp
src/tools/rest-frontend/README.md
src/tools/rest-frontend/application-config.json.tpl
src/tools/rest-frontend/public/pages/main/entries/form.html
src/tools/rest-frontend/public/pages/main/website/conversion.html
src/tools/rest-frontend/public/pages/main/website/listfiles.html
src/tools/rest-frontend/public/pages/main/website/news.html
src/tools/rest-frontend/resources/assets/js/config/http.js
src/tools/rest-frontend/resources/assets/js/controllers/main/entries/EntryCreateController.js
src/tools/rest-frontend/resources/assets/js/controllers/main/entries/EntryEditController.js
src/tools/rest-frontend/resources/assets/js/controllers/main/website/WebsiteConversionController.js
src/tools/rest-frontend/resources/assets/js/services/UserService.js
src/tools/rest-frontend/resources/assets/skin/base/theme.less
src/tools/rest-frontend/resources/structure.json.in

Fixes some issues described in #1151 and #1214.

rest-frontend / rest-backend: improvements

---

scripts/build-homepage

Handles the missing API description of #1181.

build-homepage script: create and copy api description

---

doc/INSTALL.md

Add information about our new Homebrew formula to the installation documentation.
@markus2330 Please review my pull request.

Documentation: Add information About Homebrew Tap

---

scripts/update-snippet-repository
src/tools/rest-backend/benchmarks/benchmark_kdbrest_mysql.cpp
src/tools/rest-backend/benchmarks/testdata.cpp
src/tools/rest-backend/database_application.cpp
src/tools/rest-backend/database_application.hpp
src/tools/rest-backend/model_entry.hpp
src/tools/rest-backend/tests/test_model_entry.cpp
src/tools/rest-backend/user_application.cpp
src/tools/rest-frontend/Gruntfile.js
src/tools/rest-frontend/public/assets/translations/en.json
src/tools/rest-frontend/public/pages/main/entries/form.html
src/tools/rest-frontend/public/pages/main/website/conversion.html
src/tools/rest-frontend/resources/assets/html/index.html.in

Fixes some issues and #1151 features.

rest-backend: fixes

---

src/tools/rest-frontend/resources/assets/js/controllers/main/entries/EntrySearchController.js
src/tools/rest-frontend/resources/assets/js/controllers/main/users/UserSearchController.js

Fixes pagination for the rest-frontend.

rest-frontend: pagination fix

---

src/tools/rest-backend/service_storage.cpp

Fixes disappearance of meta data as described in #1151.

rest-backend: fix disappearing of meta data

---

src/error/specification
src/plugins/curlget/CMakeLists.txt
src/plugins/curlget/README.md
src/plugins/curlget/curlget.c
src/plugins/curlget/curlget.h

added set/upload support + turned curlget into a resolver

Curlget put

---

.gitignore
src/bindings/jna/.gitignore

Small additions to the gitignore files
@markus2330 as you suggested, i made a new branch and only included some additions for jna bindings and the DS_Store

gitignore-improvements: small java and mac additions

---

src/plugins/ini/ini.c

don't write error and warnings meta, keep ordering meta in parent key

INI: some small fixes

---

doc/CONTRACT.ini
doc/METADATA.ini
scripts/mount-info

consistent line continuation / multiline values in `METADATA.ini` and `CONTRACT.ini`
use "  " as line continuation string in `mount-info`

Metadata linecont

---

src/plugins/date/README.md
src/plugins/date/testmod_date.c

(Long descriptions should be in documentation, not here)

Date: set locale to \"C\" in testmod_date

---

doc/decisions/high_level_api.md

(Long descriptions should be in documentation, not here)

Improve formatting

---

doc/decisions/elektra_web_recursive.md

elektra-web recursive structure decision

---

src/bindings/jna/CMakeLists.txt
src/bindings/jna/README.md
src/bindings/jna/libelektra4j/pom.xml.in
src/bindings/jna/libelektra4j/src/main/java/org/libelektra/KDB.java
src/bindings/jna/libelektra4j/src/main/java/org/libelektra/KeyUtils.java

Fix the failing jna bindings test as the native library is not yet installed to the system, so use the one from the build environment for our tests

jna-maven-fix-tests

---

doc/decisions/README.md
doc/decisions/elektra_web.md
doc/decisions/elektra_web_recursive.md

as requested in #999 
new version of #1173

elektra-web structure decision

---

src/plugins/crypto/CMakeLists.txt
src/plugins/crypto/README.md

- Clarification on how to set up the build environment on Mac OS Sierra
- Fix #1357 
- Reduce clutter in `CMakeLists.txt`

Crypto: update documentation

---

src/plugins/file/file/multiline
src/plugins/file/file/singleline

missing testfiles for testmod_file

file: missing testfiles (fix #1396)

---

src/plugins/range/CMakeLists.txt
src/plugins/range/README.md
src/plugins/range/range.c
src/plugins/range/testmod_range.c
tests/valgrind.suppression

range: fix warnings + unit test locale

---

doc/METADATA.ini
src/plugins/conditionals/README.md
src/plugins/conditionals/conditionals.c
src/plugins/conditionals/testmod_conditionals.c

Better evaluation of multiple conditions

Conditionals: multiple conditions

---

src/tools/web/README.md
src/tools/web/clusterd/src/routes/instances.js
src/tools/web/clusterd/src/routes/utils.js
src/tools/web/kdb.js

@reox unfortunately I could not reproduce the issue in #1424 
I think there is a race condition with the buffer file - please test this potential fix for the bug and let me know if it works now

elektra-web buffer file fix

---

src/plugins/range/range.c

range: add missing error message

---

cmake/ElektraCompiling.cmake
doc/help/CMakeLists.txt
src/libs/elektra/internal.c
src/libs/utility/text.c
tests/ctest/test_utility.c

This pull request contains minor fixes addressing the following issues:
- #1406: Documentation Compilation broken
- #1440: libutility: sanitizer tests fail
- #1442: macOS: Compiling with Option `ENABLE_ASAN` Does Not Work
. I am not that sure about commit 214898ed, since generating the documentation worked for me before setting `RUBYOPT`.
- `test_kdb.lua`,
- `test_key.lua`,
- `test_keyset.lua`,
- `testmod_range` and
- `testabi_ks`.
@markus2330: 👋 Please review my pull request.

Various Minor Fixes

---

.travis.yml
src/bindings/swig/ruby/CMakeLists.txt
src/plugins/jni/CMakeLists.txt

This pull request:
- fixes a minor problem with the version check of the Ruby bindings, and
- enables the JNI plugin on macOS if `JAVA_HOME` is not set properly
.

Build: Fix Detection of Java/Swig 

---

doc/tutorials/cascading.md
doc/tutorials/namespaces.md

fixes for cascading and namespaces tutorials
see commit messages for more details

Tutorial fixes

---

cmake/ElektraCompiling.cmake

Now using srandom and random.
Fix: #1254

Fix: mingw: undefined reference rand_r

---

doc/decisions/validation.md
src/plugins/date/date.c
src/plugins/enum/enum.c
src/plugins/path/path.c
src/plugins/validation/validation.c

prepare type plugins for type dispatcher

Prepare types

---

.travis.yml

This change makes sure that the installed version of Elektra also works without problems.

Travis: Also Test Installed Version of Elektra

---

src/tools/rest-frontend/Gruntfile.js
src/tools/rest-frontend/resources/assets/skin/bootstrap/bootstrap.less
src/tools/rest-frontend/resources/assets/skin/bootstrap/variables.less

Preparations in the build configuration of "rest-frontend" for upcoming custom website theme.

Theme: Preparations for custom website theme

---

doc/TESTING.md

Extend documentation how some common static code checkers can be used with the project
@markus2330 here you go

static-code-checking

---

src/tools/kdb/file.hpp
src/tools/kdb/mount.hpp
src/tools/kdb/set.hpp

some forgotten option colons which apparently caused sigsevs
@markus2330 lets see what travis says now, i only had some issues with shellrecorder tests now but those don't seem to be related to that at a first glance

fix-getopt

---

.travis.yml
doc/dev/error-handling.md
doc/markdownlinkconverter/elektraSpecialCharacters.sty
doc/tutorials/logging.md
src/include/kdblogger.h
src/plugins/conditionals/README.md
src/plugins/mini/mini.c

This pull request contains various minor enhancements. I am not really sure if the reformatting of the code in commit 0614e57a is correct. It would be nice if some could check this particular update.

Minor Enhancements

---

benchmarks/benchmarks.c
doc/dev/data-structures.md
scripts/draw-opmphm
src/include/kdbopmphm.h
src/libs/elektra/opmphm.c
tests/ctest/test_opmphm_init.c

- Fix small stufff at `generateKeySet ()` and draw-opmphm.
- Opmphm Api Finalization
@markus2330 please review my pull request and please answer the following question in the comments,
my next PR will be the integration of the OPMPHM in elektra, but this is a big step and leaving a PR, which is concerning the core of elektra, open for long time is not a good idea, so is it alright when I mark the feature as non functioning at this time and make sure it can not be used accidentally?
@mpranj please have a look at the `Opmphm` struct in `kdbopmphm.h` and let me know if it does not suits you!

Opmphm Api Finalization + small fixes

---

src/plugins/boolean/boolean.c

switched from own case insensitive strcmp implementation to POSIX strcasecmp (didn't know it existed back then'

boolean: use strcasecmp

---

src/libs/proposal/proposal.c
tests/ctest/test_proposal.c

fixed checking relations between metakeys

keyRel2: fix handling of meta namespace

---

src/error/specification
src/libs/tools/benchmarks/benchmark_crypto_comparison.cpp
src/plugins/crypto/README.md
src/plugins/crypto/gpg.c
src/plugins/crypto/gpg.h
src/plugins/crypto/test_internals.h
src/plugins/fcrypt/README.md
src/plugins/fcrypt/fcrypt.c
src/plugins/fcrypt/testmod_fcrypt.c

- consolidate plugin config parameter names
- prevent re-signing / re-encryption at get
- validate given GPG key ids in the plugin configuration at checkconf
- add documentation and examples about signatures
Closes #1528 .

fcrypt improvements

---

doc/TESTING.md

This pull request adds information about the code checker [OCLint](http://oclint.org/) to the testing documentation.

Testing: Add Information About OCLint

---

doc/markdownlinkconverter/markdownlinkconverter.c
src/include/kdbopmphm.h
src/libs/elektra/opmphm.c
tests/ctest/test_opmphm_init.c

fix prototype warnings in my code.

Elektra: Opmphm + markdownlinkconverter : fix void functions

---

src/plugins/enum/CMakeLists.txt
src/plugins/enum/README.md
src/plugins/enum/enum.c
src/plugins/enum/testmod_enum.c

removed useless "features", added postgetstorage placement, kicked posix regex, refactored

enum: simplify

---

tests/shell/shell/again_two_value.simpleini
tests/shell/shell/one_value.simpleini
tests/shell/shell/three_value.simpleini
tests/shell/shell/two_value.simpleini

makes the simpleini shellrecorder files relative
@markus2330 should be fine

simpleini-relative

---

cmake/Modules/FindLibBotan.cmake
doc/dev/logging.md
src/plugins/multifile/README.md
src/plugins/xerces/testmod_xerces.c
src/plugins/xerces/xerces.cpp
src/plugins/xerces/xerces.hpp

This pull request contains minor improvements for
- the `crypto_botan` plugin,
- the `multifile` plugin,
- the `xerces` plugin and
- the logging documentation
.

Small Improvements for Crypto, MultiFile & Xerces Plugin

---

doc/dev/architecture.md
src/plugins/camel/README.md
src/plugins/camel/camel.c
src/plugins/date/date.c
src/plugins/xerces/deserializer.cpp

This pull request fixes minor problems in the Camel plugin.

Camel: Fix Contract and “Use After Free” Error

---

src/plugins/fcrypt/testmod_fcrypt.c

The unit test that should detect faulty signatures caused non-reproducible errors on the build servers (see #1593 ).
This re-designed test should be more robust. Instead of writing a file and corrupting it afterwards, a modified clear-signed text file is written in a separate unit test.
This should hopefully fix #1593 .

fcrypt: improve unit test

---

.travis.yml
doc/tutorials/README.md
doc/tutorials/hello-elektra.md
examples/external/README.md
examples/helloElektra.c
scripts/fix-spelling
scripts/sed
src/libs/elektra/key.c
src/tools/gen/Makefile
src/tools/gen/gen
tests/shell/check_gen.sh
tests/shell/shell_recorder/common.sh

This pull request contains various minor fixes concerning Elektra’s **code generation tools** and a new **basic Elektra tutorial**. It also adds support for BSD’s versions of `sed` to **`fix-spelling`**.

Minor Fixes for Code Generation, New Tutorial & Improvements for Spelling Script

---

src/include/CMakeLists.txt
src/include/kdbconfig.h.in
src/libs/elektra/opmphm.c

Introduce a flag to determine endianness.

Introduce ELEKTRA_BIG_ENDIAN

---

benchmarks/benchmarks.c
benchmarks/benchmarks.h
benchmarks/opmphm.c
scripts/benchmark_opmphm
src/libs/elektra/opmphm.c
src/libs/elektra/trie.c

Includes:
* refactor `opmphmHashfunction (...)`
* remove of Trie entry in doxygen Modules
* update `generateKeySet (...)`
* adapt opmphm benchmark for `generateKeySet (...)` and general structure changes
@markus2330 please review my pull request, in the `benchmarks/opmphm.c` is unfinished stuff so notice me when there is a crucial problem.

The mother of all KeySet generation

---

src/plugins/tcl/README.md
src/plugins/tcl/action.cpp
src/plugins/tcl/action.hpp
tests/shell/shell_recorder/tutorial_wrapper/CMakeLists.txt
tests/shell/shell_recorder/tutorial_wrapper/markdown_shell_recorder.sh

This pull request contains a partial fix for issue #1019.

TCL: Require Additional Plugins

---

cmake/Modules/LibAddHaskellPlugin.cmake
src/bindings/haskell/CMakeLists.txt
src/bindings/haskell/src/Elektra/Key.chs

Fixes #1616 build error, also makes the GHC library variables and executables advanced
@markus2330 Should be fine to merge i think, the issue was reproducible and seems to work now.

haskell-bindings-improve-cmake

---

.travis.yml
cmake/Modules/LibAddHaskellPlugin.cmake
src/bindings/haskell/CMakeLists.txt
src/bindings/haskell/libelektra-haskell.cabal.in
src/plugins/haskell/haskell.cabal.in

This pull request should fix
1. problems with build paths that contain spaces, and
2. an issue where the build system always rebuilds the Haskell plugin/binding, even if we do not touch a single source file
.

Haskell: Improve Build System

---

benchmarks/benchmarks.c
benchmarks/opmphm.c
src/include/CMakeLists.txt
src/include/kdbconfig.h.in

This pull request contains all changes from the [lastest pull request](https://github.com/ElektraInitiative/libelektra/pull/1635) by Kurt. The last commit in the pull request fixes a minor formatting issue in `benchmarks/opmphm.c`.

OPMPHM: Benchmarks

---

benchmarks/benchmarks.c
benchmarks/opmphm.c
src/include/CMakeLists.txt
src/include/kdbconfig.h.in

speed up the `generateKeySet (...)` with hsearch, finalize the KeySets population for the opmphm benchmarks and the opmphm mapping benchmark

Benchmark OPMPHM mapping

---

scripts/build-homepage

Fix and enhance `build-homepag` script
fixes #1629

fix build-homepage for Debian 9

---

doc/COMPILE.md
scripts/sed
src/libs/loader/dl.c
src/plugins/crypto/botan_operations.cpp
src/plugins/crypto/gcrypt_operations.c
tests/sanitizer.blacklist
tests/shell/shell_recorder/tutorial_wrapper/CMakeLists.txt

This is an extended version of pull request #1558.
This pull request closes #1558. It also closes #788.

ASAN: Fix Sanitizer Issues

---

src/plugins/yamlcpp/README.md
src/tools/kdb/file.cpp

This pull request fixes issue #1647.

KDB File: Ignore Parsing Errors

---

scripts/build-homepage

@markus2330 you have been a little bit too fast with the last merge ;)

build-homepage: enable ASAN exclude some plugins

---

doc/news/_2017-10-25_0.8.20.md
src/plugins/ini/README.md

This pull request tries to improve the release notes for the next release. 
@markus2330 If you do not like the changes, then please feel free to ignore them.

News: Rephrase Parts of the Release Notes

---

src/tools/rest-frontend/resources/assets/js/services/EntryService.js
src/tools/rest-frontend/resources/assets/js/services/UserService.js
src/tools/rest-frontend/resources/assets/js/services/WebsiteService.js

fix homepage due to angular version upgrade.
The fixed version is already online ;)

rest-frontend: fix $http.get calls

---

doc/AUTHORS.md

hmm wasn't aware of that file ;)

Authors: add me to authors

---

src/plugins/boolean/README.md
src/plugins/boolean/boolean.c
tests/shell/shell_recorder/tutorial_wrapper/CMakeLists.txt

This update fixes the bugs described in issue #1645 and issue #1646.
a5a39cd should be correct.

Boolean Plugin: Fix Bugs

---

doc/GIT.md
doc/help/kdb.md

This PR adds documentation for the new build phrase `jenkins build all please`.

Jenkins: Add Information About New Build Job 

---

doc/news/_preparation_next_release.md

Doc: News: Preparation next release: OPMPHM

---

doc/TESTING.md

Fix and improvement for wrong paths in TESTING.md. See issue #1717 

doc: fixed paths in TESTING.md

---

doc/news/_preparation_next_release.md

add short note about `fcrypt` including the link to the ASCII-cast.

release notes for fcrypt

---

scripts/run_icheck
tests/icheck.suppression

This pull requests adds a script that addresses the API/ABI compatibility problems described in issue #1733.

API: Add Script to Check API/ABI Compatibility

---

doc/news/_preparation_next_release.md

Improve the release notes for the next version of Elektra

Release: Rephrase Minor Parts of Release Notes

---

src/bindings/glib/gelektra-key.h

Fix for #1739 - just added `void`

glib: fix clang warning (#1739)

---

tests/shell/shell_recorder/shell_recorder.sh

This commit addresses issue #1746.

Shell Recorder: Fix Cleanup Procedure

---

doc/news/_preparation_next_release.md
src/plugins/semlock/CMakeLists.txt
src/plugins/semlock/README.md

Disable semlock plugin tests and add release info for new logo 

---

src/tools/rest-frontend/package.json

…to newest
this change will hopefully fix the login issue discussed in #1679 and #1678 

rest-frontend: update dependency version for angular-ui-notification

---

src/libs/pluginprocess/pluginprocess.c

Uses mkdtemp and puts the pipe inside this directory to avoid the mktemp warning (possible race condition between file name generation and pipe creation, maybe something else picks the name in the meanwhile, highly unlikely but theoretically possible). Fixes the issue mentioned in #1782 .
@markus2330 tested by using this in conjunction with the process PR, i doubt any separate testing makes sense.

pluginprocess-mktemp-warning-fix

---

debian/copyright

Moved updated licenses from #1780 to this PR.

debian: updated and added licenses in "copyright"

---

benchmarks/CMakeLists.txt
benchmarks/opmphm.c
cmake/ElektraCache.cmake
doc/dev/data-structures.md
doc/news/_preparation_next_release.md
scripts/run_icheck
src/bindings/intercept/env/src/getenv.cpp
src/include/CMakeLists.txt
src/include/kdbconfig.h.in
src/include/kdbopmphm.h
src/include/kdbproposal.h
src/libs/elektra/keyset.c
src/libs/elektra/opmphm.c
src/libs/elektra/rand.c
tests/ctest/test_ks_opmphm.c
tests/ctest/test_opmphm.c
tests/icheck.suppression

Integrate the Order Preserving Minimal Perfect Hash Map

Opmphm Integration

---

src/libs/elektra/keyset.c

Elektra: Core: KeySet: fix warning when ENABLE_OPTIMIZATIONS=OFF

---

.travis.yml
doc/COMPILE.md
doc/news/_preparation_next_release.md
src/plugins/crypto/CMakeLists.txt
src/plugins/ini/README.md
src/plugins/ini/inih-r29/inih.c
src/plugins/multifile/CMakeLists.txt

This PR should fix issue #1721 and issue #1757.

Various Small Fixes

---

.travis.yml
doc/TESTING.md
doc/help/kdb-complete.md
doc/man/kdb-complete.1
doc/news/_preparation_next_release.md
doc/tutorials/cascading.md
doc/tutorials/validation.md
scripts/sed
src/bindings/cpp/tests/testcpp_kdb.cpp
src/error/exporterrors.cpp
src/libs/notification/tests/CMakeLists.txt
src/libs/notification/tests/testlib_notification.c
src/plugins/base64/base64.c
src/plugins/yamlcpp/README.md
src/plugins/yamlcpp/read.cpp
src/plugins/yamlcpp/write.cpp
src/tools/qt-gui/CMakeLists.txt
tests/shell/shell_recorder/listtest.esr
tests/shell/shell_recorder/profiletest.esr
tests/shell/shell_recorder/shell_recorder.sh

This PR fixes various minor problems.

Fix Various Minor Problems

---

.travis.yml
doc/news/_preparation_next_release.md
src/bindings/cpp/include/kdbvalue.hpp
src/libs/tools/include/plugindatabase.hpp
src/plugins/python2/CMakeLists.txt

This pull request should fix issue #1838 by adding virtual destructors to some polymorphic classes.

Compiler Warnings: Add Virtual Destructors

---

doc/news/_preparation_next_release.md
src/bindings/README.md
src/bindings/io/CMakeLists.txt
src/bindings/io/glib/CMakeLists.txt
src/bindings/io/glib/README.md
src/bindings/io/glib/elektra-io-glib.pc.in
src/bindings/io/glib/example/CMakeLists.txt
src/bindings/io/glib/example/exampleio_glib.c
src/bindings/io/glib/io_glib.c
src/bindings/io/glib/testio_glib.c
src/bindings/io/test/test_fd.c
src/bindings/io/test/test_idle.c
src/include/CMakeLists.txt
src/include/kdbio.h
src/include/kdbio_glib.h
src/libs/io/io.c
tests/valgrind.suppression

I/O Bindings integration into glib.

I/O Bindings for glib

---

src/plugins/crypto/crypto.h
src/plugins/crypto/gpg.c
src/plugins/fcrypt/fcrypt.c

Add missing documentation for enums in:
- crypto
- fcrypt
See #1843 .

Crypto/fcrypt: add doc for enums

---

benchmarks/opmphm.c
doc/news/_preparation_next_release.md
scripts/configure-debian-optimizations
src/include/CMakeLists.txt
src/include/kdbconfig.h.in
src/include/kdbopmphm.h
src/libs/elektra/keyset.c
src/libs/elektra/opmphm.c
tests/ctest/test_opmphm.c

- save time and space at OPMPHM
- invert configure-debian-optimization
- fix printf format for 386 systems

Opmphm optimization

---

doc/COMPILE.md
doc/todo/FUTURE
examples/external/cmake/CMakeLists.txt

Cmake update

---

src/plugins/resolver/resolver.c

Fix memleak as reported in #1871

resolver: fix memleak

---

benchmarks/README.md
benchmarks/opmphm.c

Add benchmarks for the OPMPHM build/search, binary search and hsearch

Benchmarks: opmphm: add time benchmarks for opmphm, binary search and hsearch

---

doc/news/_preparation_next_release.md
src/bindings/haskell/CMakeLists.txt
src/bindings/haskell/README.md

Resolve #1891 
@markus2330 @e1528532 please review my pull request

haskell:Check GHC version in cmake

---

.github/ISSUE_TEMPLATE.md
doc/help/kdb-cp.md
doc/help/kdb-get.md
doc/help/kdb-mv.md
doc/man/kdb-cp.1
doc/man/kdb-get.1
doc/man/kdb-mv.1
doc/news/_preparation_next_release.md
doc/tutorials/cascading.md
doc/tutorials/validation.md
src/plugins/blockresolver/README.md
src/plugins/haskell/testmod_haskell.c
src/plugins/ini/README.md
src/tools/kdb/cmdline.cpp
src/tools/kdb/cmdline.hpp
src/tools/kdb/cp.cpp
src/tools/kdb/get.cpp
src/tools/kdb/mv.cpp
tests/shell/include_common.sh.in
tests/shell/shell_recorder/shell_recorder.sh
tests/shell/shell_recorder/tutorial_wrapper/SyntaxCheck.md

This pull request should fix the test issues of PR #1915 and therefore closes #1915.

Shell Recorder: Fix Test Issues of PR #1915

---

scripts/jenkins/Jenkinsfile.daily

* Remove pipelineTriggers
* Keep stages better seperated
* Split up into more functions
* Add 'Stage2' of #1908
Resolves #1916

build: Rewrite Jenkinsfile.daily

---

src/tools/web/client/package-lock.json
src/tools/web/client/package.json
src/tools/web/client/src/components/TreeItem/dialogs/AddDialog.jsx
src/tools/web/client/src/components/TreeItem/dialogs/AdditionalMetakeysSubDialog.jsx
src/tools/web/client/src/components/TreeItem/dialogs/DuplicateDialog.jsx
src/tools/web/client/src/components/TreeItem/dialogs/EditDialog.jsx
src/tools/web/client/src/components/TreeItem/dialogs/FocusTrapDialog.jsx
src/tools/web/client/src/components/TreeItem/dialogs/NumberSubDialog.jsx
src/tools/web/client/src/components/TreeItem/dialogs/RemoveDialog.jsx
src/tools/web/client/src/components/TreeItem/dialogs/SettingsDialog.jsx
src/tools/web/client/src/components/TreeItem/dialogs/utils.js
src/tools/web/client/src/components/TreeItem/fields/SimpleTextField.jsx
src/tools/web/client/src/components/TreeItem/index.js
src/tools/web/client/src/components/TreeView.jsx
src/tools/web/client/src/components/debounce.js
src/tools/web/client/src/components/pages/Configuration.jsx
src/tools/web/client/src/css/treeview.css
src/tools/web/kdb.js

Elektra Web 1.4

---

CODE_OF_CONDUCT.md

- project -> initiative
- state who gets the abuse@ mails
- avoid word "leadership"

doc: changes in code of conduct

---

cmake/Modules/LibAddBinding.cmake
cmake/Modules/LibAddHaskellPlugin.cmake
doc/news/_preparation_next_release.md
src/bindings/haskell/CMakeLists.txt

Fixed use of LibAddBinding CMake API and added quick introduction for it.

Fix for #1890

---

doc/news/_preparation_next_release.md
src/plugins/type/README.md
src/plugins/type/type_checker.hpp

Also use type metadata in type plugin.

type: also use type metadata

---

scripts/include-common
scripts/list-tools.in
scripts/run_dev_env

see #1956
Long descriptions should be in documentation and not here.

scripts: fixes for dev env

---

tests/shell/shell_recorder/shell_recorder.sh

shell recorder: avoid reimport of whole config

---

doc/GIT.md
scripts/docker/debian/stretch/Dockerfile
scripts/jenkins/Jenkinsfile
scripts/run_icheck

build: Add icheck

---

.travis.yml
doc/CODING.md
doc/news/_preparation_next_release.md
tests/shell/check_formatting.sh

After this pull request `check_formatting` will check the style of CMake code using [`cmake_format` ](https://github.com/cheshirekow/cmake_format). 
The PR also contains minor updates to the Travis configuration. Hopefully these updates reduce the overall build time a little bit.

Build: Check Formatting of CMake Code & Travis Updates

---

doc/news/_preparation_next_release.md

Document changes to run_icheck script.
closes #2009

Add doc icheck update

---

doc/GIT.md
doc/news/_preparation_next_release.md
scripts/jenkins/Jenkinsfile.daily

* lowerCamelCaseEverywhere
* add docker registry cleanup script

Daily jenkinsfile update

---

doc/help/kdb-find.md
doc/man/kdb-find.1
doc/man/man1/kdb-find.1
doc/news/_preparation_next_release.md
scripts/kdb.fish
src/tools/kdb/factory.hpp
src/tools/kdb/find.cpp
src/tools/kdb/find.hpp
tests/shell/shell_recorder/tutorial_wrapper/CMakeLists.txt

Closes #1943
@omnidan  please review my pull request

kdb-find: initial commit

---

doc/news/_preparation_next_release.md
src/plugins/list/README.md
src/plugins/list/list.c
src/plugins/list/testmod_list.c

list: fix for #1855

---

.travis.yml
cmake/Modules/FindLibEv.cmake
doc/news/_preparation_next_release.md
scripts/docker/Dockerfile
scripts/docker/jenkinsnode/Dockerfile
src/bindings/README.md
src/bindings/io/CMakeLists.txt
src/bindings/io/doc/io_doc.c
src/bindings/io/ev/CMakeLists.txt
src/bindings/io/ev/README.md
src/bindings/io/ev/elektra-io-ev.pc.in
src/bindings/io/ev/example/CMakeLists.txt
src/bindings/io/ev/example/exampleio_ev.c
src/bindings/io/ev/example/exampleio_uv.c
src/bindings/io/ev/io_ev.c
src/bindings/io/ev/testio_ev.c
src/bindings/io/glib/README.md
src/bindings/io/glib/example/exampleio_glib.c
src/bindings/io/glib/io_glib.c
src/bindings/io/glib/testio_glib.c
src/bindings/io/test/test_fd.c
src/bindings/io/test/test_mix.c
src/bindings/io/uv/README.md
src/bindings/io/uv/example/exampleio_uv.c
src/bindings/io/uv/io_uv.c
src/include/CMakeLists.txt
src/include/kdbio_ev.h
src/include/kdbio_glib.h

I/O Bindings integration for [libev](http://software.schmorp.de/pkg/libev.html).
This PR is based on #1833. I will rebase on `master` after it is merged.

I/O Bindings for ev

---

doc/BUILDSERVER.md
doc/news/_preparation_next_release.md
scripts/jenkins/Jenkinsfile

doc: implement debian-stable-full-ini

---

doc/BUILDSERVER.md
doc/news/_preparation_next_release.md
scripts/jenkins/Jenkinsfile

Add no kdb

---

cmake/ElektraCompiling.cmake
doc/BUILDSERVER.md
doc/news/_preparation_next_release.md
scripts/docker/debian/stretch/Dockerfile
scripts/jenkins/Jenkinsfile

port mingw-64 build job
resolve #2052

build: port mingw-64 build job

---

doc/BUILDSERVER.md
doc/news/_preparation_next_release.md
scripts/jenkins/Jenkinsfile

Long descriptions should be in documentation and not here.

jenkins: port xdg build to new system

---

doc/BUILDSERVER.md
doc/news/_preparation_next_release.md
scripts/jenkins/Jenkinsfile
tests/shell/check_kdb_internal_check.sh
tests/shell/include_common.sh.in

Add statically and fully linked builds.

Add static and full builds

---

doc/news/_preparation_next_release.md
src/plugins/network/network.c

see https://github.com/ElektraInitiative/libelektra/issues/654#issuecomment-397571475
Resolves #654 

network: fix getaddrinfo call

---

benchmarks/opmphm.c
doc/news/_preparation_next_release.md
src/include/kdbopmphm.h
src/include/kdbopmphmpredictor.h
src/include/kdbprivate.h
src/libs/elektra/keyset.c
src/libs/elektra/opmphm.c
src/libs/elektra/opmphmpredictor.c
tests/ctest/CMakeLists.txt
tests/ctest/test_ks_opmphm.c
tests/ctest/test_opmphm.c
tests/ctest/test_opmphm_predictor.c

* Introduces ks flag `KS_FLAG_REBUILD_OPMPHM`
* changes `opmphmIsBuild (...)` semantics
* adds the opmphm predictor
* adds a opmphm test case

Opmphm Build Prediction Preparements

---

doc/news/_preparation_next_release.md
src/plugins/crypto/common_gpg_tests.c
src/plugins/crypto/gpg.c
src/plugins/crypto/gpg.h
src/plugins/crypto/test_internals.h
src/plugins/fcrypt/testmod_fcrypt.c

crypto, fcrypt: check gpg availability in unit tests

---

doc/news/_preparation_next_release.md
doc/todo/NEWS.md
scripts/git-checkout-ronn-files
src/bindings/intercept/fs/intercept.c
src/libs/notification/notification.c
src/plugins/base64/base64.c
src/plugins/boolean/boolean.c
src/plugins/conditionals/conditionals.c
src/plugins/fcrypt/fcrypt.c
src/plugins/glob/glob.c
src/plugins/ini/ini.c
src/plugins/mozprefs/mozprefs.c
src/plugins/validation/validation.c

replace strdup elektraStrDup

---

.travis.yml
doc/news/_preparation_next_release.md
tests/kdb/testkdb_allplugins.cpp

This pull request contains a temporary “fix” for issue #2113.

Semlock: Disable Plugin Test

---

benchmarks/opmphm.c
doc/news/_preparation_next_release.md
src/include/kdbopmphmpredictor.h
src/include/kdbprivate.h
src/libs/elektra/keyset.c
src/libs/elektra/opmphmpredictor.c
tests/ctest/test_opmphm_predictor.c

Opmphm Predictor update + some benchmark update

---

doc/news/_preparation_next_release.md
src/plugins/yamlsmith/README.md
src/plugins/yamlsmith/yamlsmith.cpp

YAML Smith: Fix Scalar Only Export

---

.travis.yml
doc/news/_preparation_next_release.md

Travis: Add Unique Name to Each Build Job

---

doc/help/elektra-introduction.md
doc/man/man7/elektra-introduction.7
doc/news/_preparation_next_release.md
doc/tutorials/README.md
doc/tutorials/arrays.md
scripts/sed
tests/shell/shell_recorder/tutorial_wrapper/CMakeLists.txt

Documentation: Add Array Tutorial

---

doc/news/_preparation_next_release.md
src/plugins/directoryvalue/directoryvalue.c
src/plugins/yajl/README.md
src/plugins/yajl/yajl_gen.c
src/plugins/yajl/yajl_gen_close.c
src/plugins/yajl/yajl_gen_open.c
src/plugins/yajl/yajl_parse.c
src/plugins/yamlcpp/CMakeLists.txt
src/plugins/yamlcpp/README.md

 Directory Value: Add Leafs For Empty & Null Keys

---

.travis.yml
doc/news/_preparation_next_release.md

This pull request should improve the average build time of the job `🍏 Clang ASAN` slightly.

 Travis: Use Environment Variables to Specify Build Configuration

---

doc/news/_preparation_next_release.md
scripts/jenkins/Jenkinsfile

jenkins: add email notifications

---

doc/news/_preparation_next_release.md
scripts/jenkins/Jenkinsfile

Resolves most of the issues described in #2146.
Still do not see a way to determine if a build was aborted due to reasons.
We can track the following upstream issue if a good solution pops up:
https://issues.jenkins-ci.org/browse/JENKINS-34376
Resolve #2146 

improve email message

---

doc/news/_preparation_next_release.md
src/plugins/python/README.md
src/plugins/python/python.cpp

Never Ending Python Story

---

doc/tutorials/validation.md
src/tools/kdb/specmount.hpp

I added clarification for spec-mount. Extra entry in release notes is unnessecary imo.

Clarify spec mount indoc

---

doc/news/_preparation_next_release.md
src/bindings/cpp/tests/tests.hpp
src/plugins/cpptemplate/README.md

Tests: Exit Test Programm in `exit_if_fail` If Check Fails

---

doc/news/_preparation_next_release.md
src/libs/pluginprocess/pluginprocess.c
src/libs/pluginprocess/tests/testlib_pluginprocess.c
src/plugins/dump/dump.cpp

pluginprocess: use pipes instead of named pipes

---

doc/news/_preparation_next_release.md
src/bindings/cpp/tests/tests.hpp

Test: Add C++ Version of `compare_keyset`

---

doc/news/_preparation_next_release.md
src/bindings/cpp/include/key.hpp
src/plugins/directoryvalue/directoryvalue_delegate.cpp

C++: Add Method `delBaseName`

---

doc/news/_preparation_next_release.md
scripts/docker/alpine/3.8/Dockerfile
src/plugins/type/README.md
tests/shell/shell_recorder/tutorial_wrapper/markdown_shell_recorder.sh

Markdown Shell Recorder: Improve Bourne Shell Compatibility

---

doc/news/_preparation_next_release.md
scripts/generate-haskell-dependencies
scripts/generate-haskell-dependencies.hs
src/bindings/haskell/README.md
src/plugins/regexdispatcher/Elektra/DefaultDispatcher.hs
src/plugins/regexdispatcher/Elektra/RangeDispatcher.hs

Some small improvements to get into the release
trying to create a haskell build on xenial and documenting the dependency script

typechecker-finalizations

---

.travis.yml
doc/man/man7/elektra-plugins.7
doc/news/_preparation_next_release.md
scripts/docker/debian/jessie/Dockerfile
scripts/docker/debian/sid/Dockerfile
scripts/docker/debian/stretch/Dockerfile
scripts/docker/legacy/Dockerfile
scripts/docker/ubuntu/xenial/Dockerfile
scripts/vagrant/debian/jessie64/provision.sh
src/include/kdbconfig.h.in
src/libs/tools/tests/testtool_backendbuilder.cpp
src/libs/tools/tests/testtool_plugindatabase.cpp
src/plugins/augeas/CMakeLists.txt
src/plugins/dbus/testmod_dbus.c
src/plugins/type/CMakeLists.txt
tests/kdb/testkdb_allplugins.cpp
tests/shell/check_kdb_internal_check.sh

Travis: Enable Memory Check on macOS ASAN Build Job

---

doc/news/_preparation_next_release.md
scripts/jenkins/Jenkinsfile

Enable the build of artifacts even during PR's.

jenkins: build artifacts everywhere

---

doc/news/_preparation_next_release.md
scripts/jenkins/Jenkinsfile.daily

Stricter cleanup

---

doc/BUILDSERVER.md
doc/news/_preparation_next_release.md
scripts/docker/README.md

doc: Add text about Jenkins + Docker

---

doc/TESTING.md
doc/news/_preparation_next_release.md
src/plugins/yanlr/yanlr/list-list_map-mixed_scalars.h
tests/cframework/tests.h

 CFramework: Compare Values of Meta Keys

---

doc/news/_preparation_next_release.md
src/libs/typesystem/libfa/CMakeLists.txt
src/libs/typesystem/specelektra/Elektra/Parse.hs
src/libs/typesystem/spectranslator/Elektra/Parsers.hs

Haskell: Fix Compilation of Spec Translator

---

benchmarks/opmphm.c
doc/news/_preparation_next_release.md
scripts/docker/debian/stretch/Dockerfile
scripts/run_icheck
src/include/kdbopmphmpredictor.h
src/include/kdbprivate.h
src/include/kdbproposal.h
src/libs/elektra/keyset.c
src/libs/elektra/opmphmpredictor.c
tests/ctest/test_opmphm_predictor.c
tests/icheck.suppression

also adds new ksLookup flag `KDB_O_BINSEARCH` and a new 
benchmarks of the OPMPHM Prediction Time

Integrate the OpmphmPredictor

---

doc/news/_preparation_next_release.md

Doc: News: prepare next release update

---

doc/news/_preparation_next_release.md
src/plugins/crypto/test_internals.h
src/plugins/fcrypt/testmod_fcrypt.c
src/plugins/gpgme/testmod_gpgme.c

Hopefully once and for all fixes the infamous #1973 .

Terminate gpg-agent after unit test is done

---

doc/news/_preparation_next_release.md
src/plugins/crypto/gpgagent_teardown.c
src/plugins/crypto/gpgagent_teardown.h
src/plugins/crypto/test_internals.h
src/plugins/fcrypt/testmod_fcrypt.c
src/plugins/gpgme/testmod_gpgme.c

fcrypt, crypto, gpgme: refactor shared gpgagent shutdown code

---

doc/news/_preparation_next_release.md
src/plugins/xerces/xerces/pom.xml

xerces: change version within test XML

---

doc/news/_preparation_next_release.md
src/plugins/ruby/README.md

Small docu fix for Ruby plugin.

Ruby plugin: fix docu for Ruby plugin

---

doc/METADATA.ini
doc/news/_preparation_next_release.md
src/error/specification
src/plugins/network/README.md
src/plugins/network/network.c
src/plugins/network/network.h
src/plugins/network/testmod_network.c

This pull request contains a rebased version of PR #2253.
@Piankero: If you want you can use this branch to continue working on the network plugin. I just rebased your work on the `master` branch. Afterwards I did an interactive rebase to edit and squash some of your commits.
This pull request closes #2253.

Network: Port Check Extension

---

.cirrus.yml
.github/ISSUE_TEMPLATE.md
README.md
doc/news/_preparation_next_release.md
doc/todo/NEWS.md
src/plugins/camel/camel.c
src/plugins/csvstorage/README.md
src/plugins/directoryvalue/README.md
src/plugins/line/line.c
src/plugins/mini/README.md
src/plugins/mini/mini.c
src/plugins/network/network.h
src/plugins/resolver/filename.c
tests/shell/shell_recorder/shell_recorder.sh

This pull request adds support for [Cirrus CI](https://cirrus-ci.com). To enable Cirrus builds for this repository one of the administrators for the [Elektra Initiative](https://github.com/orgs/ElektraInitiative/people) (either Bernhard, Markus or `elektrabot`😊) has to activate Cirruc CI [here](
https://github.com/marketplace/cirrus-ci). For more information, please take a look at the [Cirrus quick start guide](https://cirrus-ci.org/guide/quick-start).
@markus2330 👋 Can you please enable Cirrus for the main repository?
This PR closes #2318.
- [`sanssecours/elektra`](http://github.com/sanssecours/elektra): [![Cirrus Build Status](https://api.cirrus-ci.com/github/sanssecours/elektra.svg)](https://cirrus-ci.com/github/sanssecours/elektra) 
- …

Cirrus CI: Test Elektra on FreeBSD

---

README.md
doc/news/_preparation_next_release.md

[![Jenkins Build Status](https://img.shields.io/jenkins/t/https/build.libelektra.org/jenkins/job/libelektra/job/master.svg)](https://build.libelektra.org/jenkins/job/libelektra/job/master/lastBuild)

Jenkins: Add Status Badge to ReadMe

---

.cirrus.yml
doc/news/_preparation_next_release.md
src/plugins/range/CMakeLists.txt

Cirrus: Also Test Elektra on FreeBSD 12

---

src/tools/qt-gui/qml/i18n/lang_tr_TR.ts

(Long descriptions should be in documentation, not here)
I'll finish the rest of the way.

#682 Added turkish translation for i18n.

---

doc/decisions/README.md
doc/decisions/global_keyset.md
doc/decisions/global_plugins.md
doc/news/_preparation_next_release.md
src/include/kdbprivate.h
src/libs/elektra/backend.c
src/libs/elektra/kdb.c
src/libs/elektra/mount.c
src/libs/elektra/plugin.c
src/libs/plugin/plugin.c
src/plugins/doc/doc.h
src/plugins/list/list.c
tests/ctest/test_backend.c

Improvements to the global keyset.
- all plugins in the KDB now get a handle to the global keyset
- includes all improvements suggested in #2307

Global KeySet: improvements

---

doc/news/_preparation_next_release.md
examples/optsSnippets.c
src/include/kdbopts.h
src/libs/opts/opts.c

libopts: use errorKey as parentKey

---

doc/news/_preparation_next_release.md
examples/highlevel/README.md
src/libs/highlevel/CMakeLists.txt

highlevel: fix linker flags

---

debian/elektra-tests.install
debian/libelektra4-experimental.install

This update tries to address issue #2371. Markus, can you please check, if this PR really fixes the problem you reported?

Debian: Update Build Instructions for YAy PEG Plugin

---

doc/news/_preparation_next_release.md
doc/tutorials/command-line-options.md
examples/opts.c
src/libs/opts/opts.c
tests/ctest/test_opts.c

Libopts improvements

---

doc/news/_preparation_next_release.md
src/libs/ease/reference.c
src/plugins/specload/README.md
src/plugins/specload/specload.c
src/plugins/specload/testapp.c

This incorporates minor changes suggested in [#2458](https://github.com/ElektraInitiative/libelektra/pull/2458#discussion_r263295363) and [#2459](https://github.com/ElektraInitiative/libelektra/pull/2459#discussion_r263296838)

ease/specload: minor improvements

---

doc/news/_preparation_next_release.md
examples/spec/cassandra.ini
examples/spec/cassandra.yaml
examples/spec/lcdproc/LCDd.ini
examples/spec/lcdproc/lcdexec.ini
examples/spec/lcdproc/lcdproc.ini
examples/spec/lcdproc/lcdvc.ini

As promised I add my written specifications for cassandra and lcdproc.
@kodebach thankfully wrote lcdexec.ini
Please note that some checks are intentionally commented out because of the max plugin error.
With this they can at least still be spec-mounted.

examples: added some specification examples

---

doc/news/_preparation_next_release.md
src/plugins/type/README.md

Added more information concerning metadata in the documentation

type: improved documentation

---

doc/news/_preparation_next_release.md
doc/tutorials/hello-elektra.md

Updated the program-output inside the hello-elektra-tutorial. (CM)

Updated hello-elektra-tutorial (CM PR)

---

doc/news/_preparation_next_release.md
doc/tutorials/hello-elektra.md

CM Add fix to the documentation of 'Hello, Elektra' tutorial

---

doc/news/_preparation_next_release.md
doc/tutorials/java-kdb.md

CM: Fix Typo

---

doc/news/_preparation_next_release.md
examples/helloElektra.c
examples/keyCopy.c
examples/keyMeta.c
src/bindings/cpp/include/kdbtimer.hpp
src/include/kdbassert.h
src/include/kdbos.h
src/include/macros/type_create_to_value.h
src/plugins/conditionals/conditionals.c
src/plugins/crypto/gpgagent_teardown.h
src/plugins/curlget/curlget.c
src/plugins/hosts/hosts.h
src/plugins/iconv/conv.h
src/plugins/mathcheck/floathelper.h
src/plugins/mmapstorage/internal.h
src/plugins/mmapstorage/mmapstorage.c
src/plugins/ni/nickel-1.1.0/src/include/bohr/ds_vector.h
src/plugins/python/python/python_filter.py
src/plugins/python/python/python_plugin2.py
src/plugins/resolver/shared.h
src/plugins/syslog/syslog.c
src/plugins/tcl/action.hpp
src/tools/kdb/coloredkdbio.hpp
src/tools/kdb/info.cpp
src/tools/kdb/rename.hpp
src/tools/qt-gui/qml/TooltipCreator.js

@markus2330 👋 Markus, can you please [activate the LGTM integration for the repository](https://lgtm.com/projects/g/ElektraInitiative/libelektra/ci/)? I think that would be really helpful in checking, if the PR really fixes some of the warnings reported by [LGTM](https://lgtm.com).

Code Check: Fix Some Warnings Reported by LGTM

---

README.md
doc/news/_preparation_next_release.md

I'm making a new pull request, but I'm already in the cm2019s group.

[CM] Documentation: Improve readability in README

---

README.md
doc/news/_preparation_next_release.md

CM Pull request for the Configuration management course registration.

CM Pull request

---

doc/news/_preparation_next_release.md
scripts/reformat-shfmt
tests/shell/include_common.sh.in

also make sure it is 1000 lines long

shfmt: format include_common.sh.in

---

doc/news/_preparation_next_release.md
doc/tutorials/plugins.md

See #2524 for further details and discussion.

doc: improve section about checkconf in the plugin tutorial

---

doc/news/_preparation_next_release.md
doc/tutorials/cascading.md
src/plugins/csvstorage/csvstorage.c
src/plugins/csvstorage/csvstorage/validDos.csv
src/plugins/csvstorage/testmod_csvstorage.c

Fix dos newlines

---

doc/news/_preparation_next_release.md
src/tools/rest-frontend/public/pages/main/website/home.html

added badges to website

---

doc/news/_preparation_next_release.md
src/tools/web/client/src/components/pages/Configuration.jsx

These changes fix issue #2441 in a workaround style.
There still exist the problem of issue #2408 --> When this problem is fixed, this workaround may not be needed anymore.

Workaround fix for issue #2441

---

doc/METADATA.ini
doc/news/_preparation_next_release.md
src/plugins/type/README.md
src/plugins/type/testmod_type.c
src/plugins/type/type.c
src/plugins/type/type.h
src/plugins/type/types.c

This adds more configuration options to the `type` plugin. This could be used to implement #2571.

type: more boolean config

---

doc/news/_preparation_next_release.md
src/plugins/crypto/gpg.c
src/plugins/fcrypt/fcrypt.c

Fcrypt keyid fix

---

doc/news/_preparation_next_release.md
src/plugins/multifile/multifile.c

Adds cache support for multifile (#2598).

multifile: add support for cache

---

doc/news/_preparation_next_release.md
src/libs/elektra/mount.c
src/plugins/cache/CMakeLists.txt
src/plugins/cache/cache.c

Closes #2605.
- [] References to issues, e.g. `close #X`, should be in the commit messages.

mmapcache: fix dependencies and segfault

---

doc/news/_preparation_next_release.md
src/plugins/type/testmod_type.c
src/plugins/type/type.c
tests/shell/shell_recorder/tutorial_wrapper/CMakeLists.txt

I expanded a test case in `testmod_type` to ensure there is no regression.
(It took some time to fix this, because of #2605)

type bugfix

---

doc/help/kdb-cp.md
doc/news/_preparation_next_release.md
src/tools/kdb/cp.cpp
tests/shell/shell_recorder/tutorial_wrapper/CMakeLists.txt

src/tools/kdb/cp.cpp
Reintroduced fix with ksAppend on the right position.
Close #2600 

Fix kdb cp

---

doc/news/_preparation_next_release.md
src/libs/elektra/kdb.c
src/libs/elektra/split.c

cache: fix file name check

---

doc/decisions/logging.md
doc/dev/logging.md
doc/news/_preparation_next_release.md
src/error/exporterrors.cpp
src/include/kdbassert.h
src/include/kdbhelper.h
src/include/kdblogger.h
src/include/kdbmacros.h
src/libs/elektra/log.c
src/libs/opts/opts.c

As discussed in the last meeting, I changed the default logging settings.
I also changed the default message format to make the message easier to read.

Logging changes

---

doc/news/_preparation_next_release.md
src/libs/elektra/kdb.c
tests/kdb/testkdb_ensure.cpp

Fast Cache

---

doc/news/_preparation_next_release.md
scripts/docker/debian/stretch/Dockerfile
scripts/jenkins/Jenkinsfile

After this PR the [Coveralls coverage analysis](https://coveralls.io/github/ElektraInitiative/libelektra) will also include some generated source files from the build directory. This update decreases the reported coverage to a more realistic value of about 56%.

Coveralls: Improve Exclusion Patterns

---

doc/decisions/README.md
doc/decisions/ingroup_removal.md
doc/dev/error-handling.md
doc/news/_preparation_next_release.md
src/bindings/cpp/examples/cpp_example_userio.cpp
src/bindings/cpp/include/kdbio.hpp
src/bindings/jna/libelektra4j/src/main/java/org/libelektra/Key.java
src/bindings/jna/libelektra4j/src/main/java/org/libelektra/KeyUtils.java
src/error/exporterrors.cpp
src/libs/elektra/kdb.c
src/plugins/augeas/README.md
src/plugins/conditionals/README.md
src/plugins/crypto/README.md
src/plugins/doc/doc.c
src/plugins/mathcheck/README.md
src/plugins/yambi/README.md
src/plugins/yanlr/README.md
src/plugins/yawn/README.md
src/plugins/yaypeg/README.md
src/tools/kdb/coloredkdbio.hpp
src/tools/web/kdb.js
tests/cframework/tests.c

error: removed `ingroup` metadata

---

doc/INSTALL.md
doc/news/_preparation_next_release.md
doc/tutorials/python-kdb.md

See #2593.
Currently, additional steps are necessary such that the dynamic libraries are found correclty. Since that will no longer be necessary after the next release, I did not add that to the tutorial.
@markus2330 please review my …

Python Tutorial: Alpine Linux instruction for Python bindings

---

cmake/ElektraCache.cmake
doc/news/_preparation_next_release.md

2668 tutorial bug

---

doc/news/_preparation_next_release.md
src/libs/elektra/mount.c
src/plugins/cache/shelltests.md
tests/shell/shell_recorder/tutorial_wrapper/CMakeLists.txt

Disable cache plugin temporarily, because of #2702 and #2694.

disable cache plugin, add regression tests

---

doc/news/_preparation_next_release.md
doc/tutorials/plugins.md

Added a section on elektraPluginGetGlobalKeySet to the plugin tutorial as referenced in #2524 
that everything is ready …

doc: added section on elektraPluginGetGlobalKeySet to plugin tutorial

---

CMakeLists.txt
doc/news/_preparation_next_release.md

if you cross compile, you do not necessarily need tests and benchmarks. If
you do not want tests, you might not be interessted in benchmarks as well
and therefore you do not need additional (build) dependencies
@markus2330 please …

core: only add_subdirectory(benchmark) if BUILD_TEST is set

---

doc/news/_preparation_next_release.md
src/plugins/multifile/multifile.c

Disable caching with ini and add Global Keyset handle to storage plugin too.

multifile: disable ini caching, add Global Keyset reference

---

doc/news/_preparation_next_release.md
src/plugins/multifile/multifile.c

Closes #2780 and closes #2694.

Multifile error fixes

---

src/tools/rest-frontend/public/vendor/asciinema/LICENCE

added license for asciinema

---

README.md
doc/news/_preparation_next_release.md
doc/tutorials/application-integration.md
doc/tutorials/mount.md
scripts/sed
src/include/kdbconfig.h.in
src/plugins/resolver/README.md
src/tools/README.md

Hi guys - this is my first pull request for Elektra, it contains a small typo fix in the root README.md file.
You will probably see more of me because as part of my bachelors thesis I will write go bindings and rewrite the nodejs web api with GO :)
- Add the "work in progress" label if you …

Fix readme typos

---

doc/news/_preparation_next_release.md
src/plugins/cache/cache.c

cache: fix GCC ASAN Build Warnings, closes #2820

---

doc/news/_preparation_next_release.md
src/libs/elektra/kdb.c

Enable PROCGETSTORAGE on CACHE_HIT

---

doc/news/_preparation_next_release.md
src/error/specification
src/libs/elektra/mount.c
src/plugins/fcrypt/fcrypt.c
src/plugins/jni/jni.c
src/plugins/shell/shell.c
src/plugins/type/type.c
src/plugins/wresolver/wresolver.c
tests/kdb/testkdb_ensure.cpp
tests/kdb/testkdb_error.cpp

Minor error improvments

---

doc/news/_preparation_next_release.md
scripts/docker/debian/buster/Dockerfile
scripts/jenkins/Jenkinsfile

jenkins: add some buster tests

---

doc/news/_preparation_next_release.md
src/bindings/jna/libelektra4j/pom.xml.in

jna: upgraded dependency versions

---

doc/news/_preparation_next_release.md
scripts/reformat-cmake

format: check version of cmake-format

---

doc/news/_preparation_next_release.md
scripts/jenkins/Jenkinsfile

Buster minimal

---

cmake/Modules/FindLibOpenSSL.cmake
cmake/Modules/LibAddMacros.cmake
doc/news/_preparation_next_release.md
src/bindings/swig/CMakeLists.txt

Cmake swig

---

doc/news/_preparation_next_release.md
scripts/draw-all-plugins

I think this should be ready to merge. I do have one question though. Is it expected behavior that the generated image look differently, even if I use Docker and execute the current version of the script from the `master` branch?

Draw Plugins: Support Space Characters in Repository Path

---

doc/news/_preparation_next_release.md
scripts/jenkins/Jenkinsfile

jenkins: build+deploy WebUI

---

.cirrus.yml
doc/news/_preparation_next_release.md
scripts/link-checker

Link Checker merge PRs before checking links

---

doc/news/_preparation_next_release.md
scripts/docker/debian/buster/Dockerfile
scripts/jenkins/Jenkinsfile

Buster Debian Packages

---

doc/news/_preparation_next_release.md
doc/tutorials/highlevel-bindings.md
doc/tutorials/language-bindings.md

Highlevel Bindings tutorial

---

doc/news/_preparation_next_release.md
src/plugins/type/README.md
src/plugins/type/testmod_type.c
src/plugins/type/type.c
src/plugins/type/types.c

Type: disabling restore

---

cmake/ElektraConfig.cmake.in
doc/help/elektra-highlevel-gen.md
doc/help/kdb-gen-highlevel.md
doc/man/man1/kdb-gen-highlevel.1
doc/man/man7/elektra-highlevel-gen.7
doc/man/man7/elektra-plugins.7
doc/news/_preparation_next_release.md
doc/tutorials/application-integration.md
src/tools/kdb/gen/highlevel/enums.cpp
src/tools/kdb/gen/highlevel/enums.hpp
src/tools/kdb/gen/highlevel/highlevel.cpp

This incorporates the last review from #2927.

Minor changes to codegen

---

doc/news/_preparation_next_release.md
src/libs/elektra/keyset.c

ksAppendKey: fix deletion on resizing

---

doc/BUILDSERVER.md
doc/news/_preparation_next_release.md
doc/tutorials/plugins.md
src/tools/website-frontend/resources/structure.json.in

Build server

---

doc/news/_preparation_next_release.md
scripts/dev/pre-commit-check-formatting

scripts: fix and move pre-commit-check-formatting

---

doc/decisions/highlevel_help_message.md
doc/news/_preparation_next_release.md
doc/tutorials/command-line-options.md
src/libs/opts/opts.c
src/plugins/gopts/gopts.c
src/tools/kdb/gen/highlevel/highlevel.cpp
tests/ctest/test_opts.c

opts:  remove -h as help mode option

---

doc/news/_preparation_next_release.md
scripts/jenkins/Jenkinsfile

**Note:** I did only test the changes contained in this pull request in a Groovy console using a mockup version of the usual Jenkins code.

Jenkins: Do Not Auto Cancel `master` Build Jobs

---

doc/news/_preparation_next_release.md
doc/tutorials/highlevel-bindings.md

doc: improve binding tutorial

---

doc/news/_preparation_next_release.md
src/plugins/spec/spec.c

spec: minor change to error handling

---

doc/decisions/error_codes.md
doc/news/_preparation_next_release.md
scripts/docker/webui/elektrad-demo/realworld.ini
src/include/kdbmacros.h
src/libs/elektra/kdb.c
src/plugins/augeas/README.md
src/plugins/crypto/README.md
src/plugins/dump/dump.cpp
src/plugins/error/README.md
src/plugins/network/network.c
src/plugins/path/path.c
src/plugins/python/python.cpp
src/plugins/type/README.md
src/plugins/type/type.c
src/plugins/validation/validation.c
src/plugins/yajl/README.md

Error improvements

---

doc/news/_preparation_next_release.md
examples/ksIterate.c
src/libs/elektra/kdb.c
src/libs/elektra/key.c
src/libs/elektra/keymeta.c
src/libs/elektra/keyname.c
src/libs/elektra/keyset.c
src/plugins/README.md

Fix some typos in the documentation of the C-API.

doc: Fix typos in documentation

---

doc/help/kdb-showmeta.md
doc/man/man1/kdb-showmeta.1
doc/news/_preparation_next_release.md
src/tools/kdb/factory.hpp
src/tools/kdb/showmeta.cpp
src/tools/kdb/showmeta.hpp
tests/shell/shell_recorder/tutorial_wrapper/CMakeLists.txt

Kdb showmeta

---

doc/news/_preparation_next_release.md
src/bindings/jna/libelektra4j/src/main/java/org/libelektra/Elektra.java
src/bindings/rust/README.md
src/bindings/rust/elektra-sys/build.rs.in
src/bindings/rust/elektra-sys/published_build.rs
src/libs/elektra/CMakeLists.txt
src/libs/elektra/symbols.map
src/libs/invoke/CMakeLists.txt
src/libs/pluginprocess/CMakeLists.txt

Remove elektra

---

doc/news/_preparation_next_release.md
src/plugins/xerces/README.md

This PR adds additional commands in the xerces plugin doc how to include this plugin when …

doc: xerces add homebrew dependency instructions

---

doc/news/_preparation_next_release.md
src/tools/gen-gpg-testkey/gen-gpg-testkey.c

The string 'gen-gpg-testkey' is being put into the key description to prevent mismatches with libelektra.org e-mail addresses. See #2957 for full discussion.
Fixes #2957 .
Reviewers will …

tools: fix key description in gen-gpg-testkey

---

doc/news/_preparation_next_release.md
src/bindings/cpp/include/kdbvalue.hpp
src/include/kdbease.h
src/include/kdbhelper.h
src/include/kdbinternal.h
src/include/kdbprivate.h
src/include/kdbproposal.h
src/libs/ease/functional.c
src/libs/elektra/global.c
src/libs/elektra/proposal.c
src/libs/elektra/split.c
src/libs/elektra/symbols.map
src/libs/proposal/proposal.c
src/libs/proposal/symbols.map
src/plugins/hosts/keymetaformatting.c
src/plugins/keytometa/keytometa.c
src/tools/kdb/get.cpp
tests/ctest/CMakeLists.txt
tests/ctest/test_ks.c
tests/ctest/test_proposal.c
tests/ctest/test_spec.c

Merge after #3034.
Removes or moves some functions of `kdbproposal.h` in order to get rid of it (#2993).
- …

Remove & move parts of kdbproposal

---

doc/news/_preparation_next_release.md
src/bindings/rust/CMakeLists.txt
src/bindings/rust/elektra/src/kdb.rs

#3045 showed that an error code wasn't properly mapped to a Rust error. 
I don't believe it was the original cause of the test failure though.
I'm testing if this occurs again with this pr. …

Fix rust test case

---

doc/news/_preparation_next_release.md
scripts/docker/ubuntu/bionic/Dockerfile
scripts/jenkins/Jenkinsfile
tests/linkchecker.whitelist

This pull request contains an updated version of the changes of PR #2932.
This PR closes #2932.

Docker: Add Dockerfile for Ubuntu Bionic Beaver

---

doc/news/_preparation_next_release.md
src/plugins/crypto/botan_operations.cpp
src/plugins/crypto/gcrypt_operations.c
src/plugins/crypto/helper.c
src/plugins/crypto/openssl_operations.c
src/plugins/fcrypt/fcrypt.c
src/plugins/gpgme/gpgme.c

Improve error messages (crypto, fcrypt, gpgme)

---

doc/man/man1/kdb-check-env-dep.1
doc/man/man1/kdb-editor.1
doc/man/man1/kdb-elektrify-getenv.1
doc/man/man1/kdb-export.1
doc/man/man1/kdb-import.1
doc/man/man7/elektra-metadata.7
doc/man/man7/elektra-plugins.7
doc/news/_preparation_next_release.md
doc/tutorials/contributing-clion.md
src/libs/elektra/keytest.c

docu: update man pages

---

doc/news/_preparation_next_release.md
examples/codegen/econf/README.md
examples/codegen/tree/README.md
src/plugins/specload/README.md
src/plugins/specload/specload.c
src/plugins/specload/testmod_specload.c
src/tools/kdb/gen/templates/highlevel.c.mustache
tests/shell/gen/highlevel/empty.expected.c
tests/shell/gen/highlevel/enum.expected.c
tests/shell/gen/highlevel/externalspec.expected.c
tests/shell/gen/highlevel/externalwithdefaults.expected.c
tests/shell/gen/highlevel/nosetter.expected.c
tests/shell/gen/highlevel/notype.expected.c
tests/shell/gen/highlevel/simple.expected.c
tests/shell/gen/highlevel/struct.expected.c

Various bugfixes

---

doc/news/_preparation_next_release.md
src/bindings/jna/README.md
src/plugins/range/range.c
src/plugins/range/range.h

error: Improved error message for range plugin

---

doc/news/_preparation_next_release.md
scripts/dev/reformat-all
scripts/dev/reformat-markdown
scripts/dev/reformat-shfmt

Fix reformat

---

tests/linkchecker.whitelist

The cppcms website has been unreachable for a whole day and it is unknown
when it will be back online.
- Add …

Whitelist cppcms links

---

doc/news/_preparation_next_release.md
src/plugins/ini/README.md

ini: improve docu

---

doc/news/_preparation_next_release.md
src/include/kdbprivate.h
src/include/kdbproposal.h
src/libs/elektra/backend.c
src/libs/elektra/kdb.c
src/libs/elektra/mount.c
src/libs/elektra/plugin.c
src/libs/elektra/proposal.c
src/libs/elektra/symbols.map
src/libs/proposal/proposal.c
src/libs/proposal/symbols.map
src/plugins/csvstorage/CMakeLists.txt
src/plugins/csvstorage/csvstorage.c
src/plugins/list/list.c
src/plugins/multifile/multifile.c
tests/ctest/test_ks.c

Part of #2993.
With this, the signature of ksRenameKeys changed from
`KeySet * ksRenameKeys (KeySet * config, const Key * name);`
to 
`KeySet * ksRenameKeys (KeySet * config, const char * name);`
since that was the signature of `elektraRenameKeys`.
For docu fixes, spell checking, and similar none of these …

Replace elektraRenameKeys with ksRenameKeys

---

doc/news/_preparation_next_release.md
src/bindings/jna/README.md
src/bindings/jna/libelektra4j/src/main/java/org/libelektra/Elektra.java
src/bindings/jna/libelektra4j/src/main/java/org/libelektra/Key.java
src/bindings/jna/libelektra4j/src/main/java/org/libelektra/KeySet.java
src/bindings/jna/libelektra4j/src/main/java/org/libelektra/Plugin.java
src/bindings/jna/libelektra4j/src/main/java/org/libelektra/PluginLoader.java
src/bindings/jna/libelektra4j/src/main/java/org/libelektra/plugin/NativePlugin.java
src/bindings/jna/libelektra4j/src/test/java/org/libelektra/ExceptionMapperIT.java

Jna improvments part 2

---

doc/dev/error-handling.md
doc/news/_preparation_next_release.md

error-doc: Added information on how warnings are stored

---

doc/news/_preparation_next_release.md
doc/tutorials/language-bindings.md

bindings-tutorial: Fix TODO and added subtyping information

---

doc/news/_preparation_next_release.md
tests/abi/testabi_ks.c

Cleanup commented KeySet abi testcases

---

doc/news/_preparation_next_release.md
src/plugins/crypto/gpg.c

crypto: handle return code of execv in the gpg module

---

doc/news/_preparation_next_release.md
examples/keyMetaKeySet.c
examples/ksNew.c
src/include/kdb.h.in
src/include/kdbprivate.h
src/libs/elektra/key.c
src/libs/elektra/keyhelpers.c
src/libs/elektra/keymeta.c
src/libs/elektra/keyset.c
src/libs/elektra/symbols.map
src/libs/versions.def
tests/abi/testabi_ks.c
tests/ctest/test_ks.c

Improvements for exposed meta keyset

---

doc/news/_preparation_next_release.md
src/bindings/rust/README.md
src/bindings/rust/elektra/src/kdb.rs
src/bindings/rust/elektra/src/keyset.rs
src/bindings/rust/elektra/src/lib.rs
src/bindings/rust/example/src/bin/kdb.rs

fixes #3059 
This implements `KDBError` using string matching in particular to allow using `kdb_error.is_resource()` to also catch an out of memory error, as the specification demands.
I additionally smoothed out some points in the documentation and the Readme.
I also added a `keyset!` macro that I think will be useful to easily create a larger keyset in a single invocation, similar to `ksNew`. Up until now all keys had to be added with a new `ks.append_key(...)` statement.
With the macro you can do
```rust
let ks = keyset![
StringKey::new("user/test1").unwrap(),
StringKey::new("user/test2").unwrap(),
StringKey::new("user/test3").unwrap(),
];
``` …

Rust: Rewrite KDBError

---

.cirrus.yml
.restyled.yaml
doc/CODING.md
doc/CONTRACT.ini
doc/decisions/holes.md
doc/news/2014-12-02_0.8.10.md
doc/news/_preparation_next_release.md
doc/tutorials/highlevel.md
scripts/dev/fix-spelling
scripts/dev/reformat-markdown
scripts/docker/debian/sid/Dockerfile
scripts/sed
src/plugins/yamlcpp/CMakeLists.txt
src/tools/web/client/src/components/TreeItem/fields/SimpleTextField.jsx
src/tools/web/client/src/containers/ConnectedConfigurationPage.js
src/tools/web/client/src/containers/ConnectedCreateInstanceCard.js
src/tools/web/client/src/containers/ConnectedErrorSnackbar.js
src/tools/web/client/src/containers/ConnectedHomePage.js
src/tools/web/client/src/containers/ConnectedInstanceCard.js
src/tools/web/client/src/containers/ConnectedMenu.js
src/tools/web/client/src/containers/ConnectedTreeItem.js
src/tools/web/client/src/containers/ConnectedTreeSearch.js
src/tools/web/client/src/containers/ConnectedTreeView.js
src/tools/website-frontend/public/vendor/asciinema/asciinema-player.js
src/tools/website-frontend/resources/assets/js/config/http.js
tests/linkchecker.whitelist
tests/shell/check_spelling.sh
tests/shell/shell_recorder/tutorial_wrapper/CMakeLists.txt

This pull request should make sure that the Cirrus build jobs should finish successfully again. Hopefully I have time to fix the tests for YAML CPP on macOS properly in the future. As already stated in the commit messages of the PR, the tests work fine on my machine, but not on Cirrus CI.

Cirrus: Fix Build Problems

---

doc/TESTING.md
doc/news/_preparation_next_release.md

Testing documentation

---

doc/help/elektra-cmerge-strategy.md
doc/help/kdb-cmerge-config-files
doc/help/kdb-cmerge.md
doc/man/man1/kdb-cmerge.1
doc/man/man7/elektra-cmerge-strategy.7
doc/news/_preparation_next_release.md
doc/tutorials/cmerge.md
doc/tutorials/install-config-files.md

Merge docu

---

doc/help/kdb-editor.md
doc/help/kdb-export.md
doc/help/kdb-import.md
doc/man/man1/kdb-editor.1
doc/man/man1/kdb-export.1
doc/man/man1/kdb-import.1
doc/news/_preparation_next_release.md
src/tools/kdb/editor.cpp
src/tools/kdb/export.cpp
src/tools/kdb/import.cpp

Kdb import export provider

---

doc/help/kdb-list-tools.md
doc/man/man1/kdb-list-tools.1
doc/news/_preparation_next_release.md
scripts/dev/run_env
scripts/kdb/list-tools.in

tools: KDB_EXEC_PATH support

---

doc/news/_preparation_next_release.md
src/include/kdbmerge.h
src/libs/merge/kdbmerge.c
src/tools/kdb/cmerge.cpp

These are some fixes necessary for integration of the merge library into the tools

Base for tool integration

---

doc/news/_preparation_next_release.md
src/libs/elektra/keyset.c

Issue: https://github.com/ElektraInitiative/libelektra/issues/3072
- Add the "work in progress" label if you …

improve the documentation of ksAppendKey

---

doc/news/_preparation_next_release.md
src/libs/tools/include/helper/keyhelper.hpp
src/libs/tools/src/helper/keyhelper.cpp

Depends on #3234
Closes [this review](https://github.com/ElektraInitiative/libelektra/pull/3236#discussion_r347145639)

Helper for merge tools

---

.github/CONTRIBUTING.md
doc/GETSTARTED.md
doc/news/_preparation_next_release.md
src/plugins/yajl/README.md
src/tools/website-frontend/public/pages/main/website/home.html
src/tools/website-frontend/resources/structure.json.in

issue #2922

---

doc/news/_preparation_next_release.md
scripts/jenkins/Jenkinsfile

Updated xUnit plugin in Jenkinsfile.

---

doc/AUTHORS.md
doc/man/man7/elektra-plugins.7
doc/news/_preparation_next_release.md
src/plugins/README.md
src/plugins/cpptemplate/cpptemplate_delegate.cpp
src/plugins/kconfig/CMakeLists.txt
src/plugins/kconfig/README.md
src/plugins/kconfig/base.hpp
src/plugins/kconfig/file_utility.cpp
src/plugins/kconfig/file_utility.hpp
src/plugins/kconfig/kconfig.cpp
src/plugins/kconfig/kconfig.hpp
src/plugins/kconfig/kconfig/meta_example.h
src/plugins/kconfig/kconfig/meta_examplerc
src/plugins/kconfig/kconfig/simple_example.h
src/plugins/kconfig/kconfig/simple_examplerc
src/plugins/kconfig/kconfig_delegate.cpp
src/plugins/kconfig/kconfig_delegate.hpp
src/plugins/kconfig/kconfig_parser.cpp
src/plugins/kconfig/kconfig_parser.hpp
src/plugins/kconfig/kconfig_parser_exception.cpp
src/plugins/kconfig/kconfig_parser_exception.hpp
src/plugins/kconfig/testmod_kconfig.cpp

This has the same changes `https://github.com/ElektraInitiative/libelektra/pull/3249`, without the rebase problems.
I also changed the documentation mentions in the comments from the other PR.

KConfig Get

---

doc/news/_preparation_next_release.md
src/bindings/cpp/include/kdbexcept.hpp
src/tools/kdb/main.cpp
src/tools/kdb/mountbase.cpp

Kdb mount error message fix

---

doc/news/_preparation_next_release.md
src/tools/kdb/get.cpp
src/tools/kdb/mount.cpp

fixes #3162
(except for intercept bindings)
- Add the "work in progress" label if you do not want the PR to …

Remove kdbprivate.h from kdb get & mount

---

doc/news/2019-11-26_0.9.1.md
doc/tutorials/README.md

Release notes

---

doc/news/_preparation_next_release.md
doc/tutorials/validation.md

doc[validation]: remove header

---

doc/news/_preparation_next_release.md
scripts/jenkins/Jenkinsfile

Fix coveralls

---

doc/news/_preparation_next_release.md
src/tools/kdb/cache.hpp

Cache fix synopsis

---

doc/news/_preparation_next_release.md
src/plugins/yanlr/CMakeLists.txt

This pull request is based on PR #3342, since otherwise some build jobs would fail.

Yan LR: Support ANTLR 4.8

---

.restyled.yaml
.travis.yml
doc/news/2016-06-14_0.8.17.md
doc/news/_preparation_next_release.md
doc/tutorials/highlevel.md
examples/spec/lcdproc/LCDd.ini
src/tools/kdb/gen/highlevel/highlevel.cpp
tests/shell/gen/highlevel/externalspec.expected.h
tests/shell/gen/highlevel/externalwithdefaults.expected.h
tests/shell/gen/highlevel/nosetter.expected.h
tests/shell/gen/highlevel/simple.expected.h
tests/shell/gen/highlevel/struct.expected.h

This pull request also contains a news item about my finished thesis as suggested in PR #3346.

Various Minor Enhancements

---

.cirrus.yml
doc/news/_preparation_next_release.md

This pull request should fix the build problems of the Cirrus macOS build jobs.

Cirrus: Update D-Bus Startup Command on macOS

---

.cirrus.yml
.travis.yml
doc/news/_preparation_next_release.md

Update image and software versions.

CI improvements

---

doc/news/_preparation_next_release.md
doc/tutorials/storage-plugins.md
src/plugins/yamlcpp/README.md
src/plugins/yamlcpp/read.cpp
src/plugins/yamlcpp/write.cpp
src/plugins/yamlcpp/yamlcpp.cpp

This pull request is based on PR #3357. If you want a clean history of the additional changes, then please merge #3357 first.

YAML CPP: Set and Require Boolean Metadata

---

doc/news/_preparation_next_release.md
tests/linkchecker.whitelist

link checker: whitelist broken links

---

doc/news/_preparation_next_release.md
src/bindings/swig/common.i
src/bindings/swig/python/tests/test_kdb.py

Test kdbEnsure from swig/python bindings. …

python: test kdbEnsure

---

.cirrus.yml
.travis.yml
doc/news/_preparation_next_release.md
lgtm.yml
scripts/docker/debian/buster/Dockerfile
scripts/docker/debian/buster/doc.Dockerfile
scripts/docker/debian/buster/i386.Dockerfile
scripts/docker/debian/buster/minimal.Dockerfile
src/tools/kdb/complete.cpp
tests/kdb/testkdb_allplugins.cpp
tests/kdb/testkdb_conflict.cpp
tests/sanitizer.blacklist

Fix macOS builds

---

doc/news/_preparation_next_release.md
src/plugins/cache/README.md
src/plugins/cache/cache.c

cache: XDG compatibility

---

doc/news/_preparation_next_release.md
src/plugins/fcrypt/fcrypt.c

rename () accross file systems is not supported and causes failures.
If rename () fails, fcrypt tries to perform a manual copy.
See #3283 for full discussion.
Fixes #3283 .
Reviewers will …

fcrypt: try manual copy if rename () fails

---

.cirrus.yml
doc/news/_preparation_next_release.md

cirrus: enable fcrypt on fedora again #3283

---

doc/news/_preparation_next_release.md
src/tools/webd/package-lock.json
src/tools/webd/package.json
src/tools/webd/src/app.js
src/tools/webd/src/connector.js
src/tools/webd/src/routes/instances.js
src/tools/webd/src/routes/utils.js
src/tools/webd/src/serveClient.js
src/tools/webui/package-lock.json

tools: webd - remember elektrad sessions

---

doc/news/_preparation_next_release.md
scripts/docker/debian/sid/Dockerfile
src/plugins/crypto/gpgagent_teardown.h
tests/valgrind.suppression

Try to kill the gpg-agent if the shutdown of the agent should fail.
This is an attempt to resolve #2341 .
- …

crypto: add shut-down logic in testmod_crypto

---

.cirrus.yml
doc/news/_preparation_next_release.md
scripts/jenkins/Jenkinsfile

cirrus: install ruby 2.6

---

doc/news/_preparation_next_release.md
scripts/jenkins/Jenkinsfile

Jenkins: disable crypto on debian-unstable-full

---

doc/news/_preparation_next_release.md
src/tools/elektrad/main.go

tools: elektrad - log error if creation of kdb handle fails

---

doc/news/_preparation_next_release.md
scripts/jenkins/Jenkinsfile

Enabling building Bionic packages.

---

doc/news/_preparation_next_release.md
scripts/docker/debian/sid/Dockerfile

Add bison debug symbols to debug leaks in toml plugin.

debian sid: fix docker image

---

benchmarks/large.c
benchmarks/storage.c
doc/news/_preparation_next_release.md
scripts/cmake/ElektraCache.cmake
scripts/docker/fedora/31/Dockerfile
scripts/docker/fedora/32/Dockerfile
scripts/jenkins/Jenkinsfile
src/bindings/gsettings/elektrasettingsbackend.c
src/bindings/io/test/test_fd.c
src/bindings/io/test/test_idle.c
src/bindings/io/test/test_mix.c
src/bindings/io/test/test_timer.c
tests/cframework/tests.h
tests/valgrind.suppression

Adds Fedora 32 images to cirrus and jenkins.
Closes #3423.

cirrus, jenkins: upgrade/add fedora 32 images

---

.github/stale.yml
doc/news/_preparation_next_release.md

github: add probot to auto-close issues, closes #3398

---

doc/news/_preparation_next_release.md
scripts/jenkins/Jenkinsfile

Publishing packages for Bionic to community instead of a7.

---

doc/news/_preparation_next_release.md
scripts/jenkins/Jenkinsfile

Jenkinsfile method call corrected

---

doc/INSTALL.md
doc/news/_preparation_next_release.md

Documentation for Ubuntu Bionic Packages.

---

doc/news/_preparation_next_release.md
scripts/docker/fedora/31/Dockerfile
scripts/docker/fedora/32/Dockerfile
scripts/jenkins/Jenkinsfile

jenkins: add fedora 32 asan build

---

doc/news/_preparation_next_release.md
tests/linkchecker.whitelist

Removed a broken link from the link checker.

---

doc/news/_preparation_next_release.md
scripts/docker/website/backend/Dockerfile
scripts/jenkins/Jenkinsfile

website-backend: disable build

---

doc/news/_preparation_next_release.md
doc/tutorials/run_reformatting_script_with_docker.md

doc: Fixed old path for reformat script

---

doc/news/_preparation_next_release.md

suggested improvements of release notes

---

doc/news/2020-05-26_0.9.2.md
doc/news/_preparation_next_release.md
scripts/docker/alpine/3.10/release.Dockerfile
scripts/docker/alpine/3.11/Dockerfile
scripts/docker/alpine/3.11/release.Dockerfile
scripts/jenkins/Jenkinsfile

Docker: add alpine image with Elektra installed

---

doc/news/_preparation_next_release.md
scripts/jenkins/Jenkinsfile

Hack to resolve problem with cyclic dependency between `go-elektra` and `libelektra`.
- Add the "work in …

Jenkinsfile: temporarily disable stages to trigger build of new packages

---

.cirrus.yml
.travis.yml
doc/news/_preparation_next_release.md

CI updates

---

doc/news/_preparation_next_release.md
src/plugins/hosts/README.md

hosts: describe hierarchy and limitations

---

.restyled.yaml
doc/news/_preparation_next_release.md
scripts/dev/reformat-javascript
scripts/dev/reformat-markdown
scripts/dev/reformat-shell

Formatting: specify exact versions

---

.travis.yml
doc/news/_preparation_next_release.md

Try to fix the "No output has been received in the last 10m0s" errors.

travis: increase wait time and update Xcode version

---

doc/news/_preparation_next_release.md
scripts/jenkins/Jenkinsfile
tests/shell/CMakeLists.txt

CTest: increase test timeout for internal suite tests

---

doc/news/_preparation_next_release.md
scripts/docker/debian/buster/Dockerfile
scripts/jenkins/Jenkinsfile.release
scripts/release/release.sh

Automate release

---

doc/GOALS.md
doc/WHY.md
doc/help/elektra-glossary.md
doc/man/man7/elektra-glossary.7
doc/news/_preparation_next_release.md

Terminology

---

.cirrus.yml
.travis.yml
doc/news/_preparation_next_release.md

Fix Python 3.8 path

---

doc/news/_preparation_next_release.md
src/bindings/swig/lua/kdb.i
src/bindings/swig/lua/tests/test_key.lua
src/bindings/swig/lua/tests/test_keyset.lua

Closes #3480.
My approach to fixing #3480

SWIG/Lua: remove ipairs support, add our own iterator

---

doc/news/_preparation_next_release.md
scripts/cmake/Modules/FindLua.cmake

CMake: use Lua 5.4 when available.

---

doc/news/_preparation_next_release.md
scripts/docker/cirrus/fedora/Dockerfile
scripts/docker/fedora/33/Dockerfile
scripts/jenkins/Jenkinsfile
src/bindings/swig/lua/README.md
src/bindings/swig/python/README.md
src/plugins/path/path.c

Adds Fedora 33 images to our CI, drops Fedora 31.
Closes #3552.
Depends on #3550.

CI: add Fedora 33 images

---

doc/news/_preparation_next_release.md
src/libs/elektra/keyname.c
tests/ctest/test_keyname.c

keynames: fix combining dot-dot parts and escapes

---

doc/news/_preparation_next_release.md
src/libs/elektra/errors.c
tests/ctest/test_key.c

keynames: fix addWarning

---

.cirrus.yml
.github/workflows/macOS_gcc10.yml
.travis.yml
doc/news/_preparation_next_release.md
scripts/kdb/mount-list-all-files
src/bindings/swig/ruby/CMakeLists.txt
src/plugins/ruby/CMakeLists.txt
src/plugins/zeromqrecv/testmod_zeromqrecv.c
tests/shell/check_oclint.sh

Closes #3613.
First step towards #3603. …

travis: move macOS gcc10 build job to github actions

---

doc/news/_preparation_next_release.md
src/bindings/cpp/include/key.hpp
src/bindings/cpp/tests/testcpp_iter_name.cpp
src/tools/qt-gui/qml/EditKeyWindow.qml
src/tools/qt-gui/qml/KeyWindow.qml
src/tools/qt-gui/qml/NewKeyWindow.qml
src/tools/qt-gui/qml/TreeView.qml
src/tools/qt-gui/qml/main.qml
src/tools/qt-gui/src/confignode.cpp
src/tools/qt-gui/src/confignode.hpp
src/tools/qt-gui/src/guibackend.cpp
src/tools/qt-gui/src/guisettings.cpp
src/tools/qt-gui/src/newkeycommand.cpp
src/tools/qt-gui/src/treeviewmodel.cpp
src/tools/qt-gui/src/treeviewmodel.hpp

qtgui: update for keyname overhaul

---

doc/news/_preparation_next_release.md
scripts/cmake/ElektraCache.cmake
src/bindings/cpp/include/key.hpp
src/bindings/cpp/tests/testcpp_key.cpp
src/bindings/swig/ruby/kdb.i

Invalid name, fix #3593

---

doc/news/_preparation_next_release.md
src/tools/website/resources/grunt-tasks/grunt-copy-website-content.js
src/tools/website/resources/structure.json.in

website: fix markdown link detection and render KEYNAMES.md

---

.cirrus.yml
doc/news/_preparation_next_release.md

cirrus: fix failing freebsd tests

---

doc/news/_preparation_next_release.md
doc/tutorials/contributing-windows.md

Not much yet, but
- demonstrates that this is actually possible and
- could make contributing appealing by lowering the entrance barrier for
Windows users
Reviewers will usually check the …

Add Visual Studio 2019 tutorial

---

doc/news/_preparation_next_release.md
doc/tutorials/README.md

doc: fix order of tutorials

---

doc/news/_preparation_next_release.md
src/libs/tools/src/plugindatabase.cpp

tools: catch exception in loop

---

doc/BIGPICTURE.md
doc/INSTALL.md
doc/news/_preparation_next_release.md
examples/spec/battery.ini
examples/spec/highlevel.ini
src/plugins/spec/README.md

examples: fix spec

---

doc/news/_preparation_next_release.md
doc/tutorials/application-integration.md
doc/tutorials/validation.md
src/bindings/README.md

Docu fixes

---

doc/news/_preparation_next_release.md
doc/tutorials/java-kdb.md

Minor rewording for H0 of CM2021.

[CM H0] updated wording + improved markdown code example

---

doc/news/_preparation_next_release.md
scripts/jenkins/Jenkinsfile.daily

Unreferenced (removed) packages in aptly do not get fully removed, making it necessary to run a cleanup command.
If you are already Elektra …

jenkins: add cleanup of aptly db to daily job

---

doc/news/_preparation_next_release.md
doc/tutorials/contributing-windows.md

For doc fixes, spell checking, and similar none of these points below …

Wsl doc update

---

doc/news/_preparation_next_release.md
src/plugins/yanlr/README.md

Fix broken link in yanlr README

---

doc/news/_preparation_next_release.md
examples/spec/openicc.ini
src/plugins/spec/README.md

Fix spec plugin examples

---

doc/BUILDSERVER.md
doc/GIT.md
doc/news/_preparation_next_release.md

[CM H1] Update Buildserver Documentation

---

doc/news/_preparation_next_release.md
src/bindings/jna/libelektra5j/src/test/java/org/libelektra/AllTests.java
src/bindings/jna/libelektra5j/src/test/java/org/libelektra/KeyNameIteratorTest.java
src/bindings/jna/libelektra5j/src/test/java/org/libelektra/KeySetTest.java
src/bindings/jna/libelektra5j/src/test/java/org/libelektra/KeyTest.java
src/bindings/jna/libelektra5j/src/test/java/org/libelektra/plugin/ReturnTest.java

[CM H1] added two small jna tests

---

doc/INSTALL.md
doc/news/_preparation_next_release.md
src/plugins/augeas/README.md
src/plugins/crypto/README.md
src/plugins/curlget/README.md
src/plugins/dbus/README.md
src/plugins/jni/README.md
src/plugins/journald/README.md
src/plugins/lua/README.md
src/plugins/python/README.md
src/plugins/xerces/README.md
src/plugins/xmltool/README.md
src/plugins/yajl/README.md
src/plugins/yamlcpp/README.md
src/plugins/zeromqsend/README.md

doc: names of different components

---

doc/news/_preparation_next_release.md
doc/tutorials/python-kdb.md
src/bindings/swig/lua/kdb.i
src/bindings/swig/lua/tests/test_keyset.lua
src/bindings/swig/python/kdb.i
src/bindings/swig/python/tests/test_keyset.py

swig/python+lua: add support for ks.remove(key)

---

doc/news/_preparation_next_release.md
src/plugins/xerces/deserializer.cpp
src/plugins/xerces/serializer.cpp
src/plugins/xerces/testmod_xerces.c

[CM H2] xerces: store array length in metakey array

---

doc/COMPILE.md
doc/GIT.md
doc/news/_preparation_next_release.md
scripts/docker/legacy/README.md
scripts/sed

doc: add "syncing forks" info to doc/GIT.md

---

doc/COMPILE.md
doc/news/_preparation_next_release.md

[CM H1] Minor update on COMPILE.md

---

doc/help/kdb-set.md
doc/man/man1/kdb-set.1
doc/news/_preparation_next_release.md
doc/tutorials/arrays.md
doc/tutorials/storage-plugins.md
src/plugins/rename/README.md
src/plugins/shell/README.md
src/plugins/yamlcpp/README.md
src/tools/kdb/set.cpp
src/tools/kdb/set.hpp
tests/shell/check_merge.sh
tests/shell/check_spec.sh
tests/shell/shell_recorder/replay_tests/ls.epf
tests/shell/shell_recorder/replay_tests/ls.esr

[CM H2] Remove kdb set functionality that creates a null key

---

doc/news/_preparation_next_release.md
scripts/jenkins/Jenkinsfile
src/bindings/io/doc/CMakeLists.txt
src/bindings/io/ev/CMakeLists.txt
src/bindings/io/glib/CMakeLists.txt
src/bindings/io/uv/CMakeLists.txt
src/bindings/jna/CMakeLists.txt
src/bindings/rust/CMakeLists.txt
src/bindings/swig/lua/CMakeLists.txt
src/bindings/swig/python/CMakeLists.txt

Closes #3452.
This PR does following: …

[CM H2] disable tests when BUILD_TESTING is disabled

---

doc/news/_preparation_next_release.md
src/include/kdbhelper.h
src/libs/elektra/internal.c
src/libs/elektra/key.c
src/libs/elektra/keymeta.c
src/libs/elektra/keyname.c
src/libs/elektra/symbols.map
src/libs/opts/opts.c
src/plugins/simpleini/simpleini.c
src/plugins/zeromqrecv/subscribe.c
src/plugins/zeromqsend/testmod_zeromqsend.c
tests/ctest/test_internal.c

[CM H2] Refactoring: elektraStrnDup -> elektraMemDup

---

doc/news/_preparation_next_release.md
src/libs/elektra/keytest.c

Improve documentation of keytest.c with suggestions from API review

---

doc/news/_preparation_next_release.md
src/libs/elektra/keyvalue.c

Improve documentation of keyvalue.c with suggestions from API review

---

doc/api_review/core/kdbOpen.md
doc/news/_preparation_next_release.md
src/libs/elektra/kdb.c

Improve documentation of kdb.c with suggestions from API review

---

doc/news/_preparation_next_release.md
scripts/docker/webui/web/Dockerfile
src/tools/elektrad/CMakeLists.txt
src/tools/elektrad/benchmark_test.go
src/tools/elektrad/find_handler_test.go
src/tools/elektrad/go.mod
src/tools/elektrad/go.sum
src/tools/elektrad/handlepool.go
src/tools/elektrad/helper_test.go
src/tools/elektrad/kdb.go
src/tools/elektrad/kdb_handler.go
src/tools/elektrad/kdb_handler_test.go
src/tools/elektrad/meta_handler.go
src/tools/elektrad/meta_handler_test.go
src/tools/elektrad/move_handler.go
src/tools/elektrad/move_handler_test.go
src/tools/elektrad/router.go

Based on #3588 (huge thanks to @kodebach). Updates go-elektra and some modules and fixes keyDup.
Enable building of `elektrad` again.

elektrad: update

---

doc/news/_preparation_next_release.md
src/libs/elektra/keyset.c

Improve documentation of keyset.c with suggestions from API review

---

doc/api_review/core/keyCopyMeta.md
doc/news/_preparation_next_release.md
src/libs/elektra/keymeta.c

Improve documentation of keymeta.c with suggestions from API review

---

doc/news/_preparation_next_release.md
src/libs/elektra/key.c

Improve documentation of key.c with suggestions from API review

---

doc/api_review/core/keyAddName.md
doc/news/_preparation_next_release.md
src/libs/elektra/keyname.c

Improve documentation of keyname.c with suggestions from API review

---

doc/news/_preparation_next_release.md
src/libs/elektra/kdb.c

doc: fix #3799

---

doc/news/_preparation_next_release.md
scripts/docker/alpine/3.13/Dockerfile
scripts/docker/alpine/3.13/release.Dockerfile
scripts/docker/cirrus/fedora/Dockerfile
scripts/docker/fedora/34/Dockerfile
scripts/docker/fedora/34/release.Dockerfile
scripts/jenkins/Jenkinsfile
scripts/jenkins/Jenkinsfile.release

CI: add Fedora 34

---

.cirrus.yml
.github/workflows/macOS_gcc10.yml
doc/news/_preparation_next_release.md
src/plugins/jni/CMakeLists.txt

actions: enable jni plugin

---

doc/news/_preparation_next_release.md
src/plugins/noresolver/README.md

noresolver: improve docu

---

doc/news/_preparation_next_release.md
src/tools/kdb/gen/templates/collect.sh
src/tools/kdb/gen/templates/highlevel.c.mustache
src/tools/kdb/gen/templates/highlevel.commands.h.mustache
src/tools/kdb/gen/templates/highlevel.h.mustache
tests/shell/gen/highlevel/commands.expected.c
tests/shell/gen/highlevel/commands.expected.commands.h
tests/shell/gen/highlevel/commands.expected.h
tests/shell/gen/highlevel/empty.expected.c
tests/shell/gen/highlevel/empty.expected.h
tests/shell/gen/highlevel/enum.expected.c
tests/shell/gen/highlevel/enum.expected.h
tests/shell/gen/highlevel/externalspec.expected.c
tests/shell/gen/highlevel/externalspec.expected.h
tests/shell/gen/highlevel/externalwithdefaults.expected.c
tests/shell/gen/highlevel/externalwithdefaults.expected.h
tests/shell/gen/highlevel/nosetter.expected.c
tests/shell/gen/highlevel/nosetter.expected.h
tests/shell/gen/highlevel/notype.expected.c
tests/shell/gen/highlevel/notype.expected.h
tests/shell/gen/highlevel/simple.expected.c
tests/shell/gen/highlevel/simple.expected.h
tests/shell/gen/highlevel/struct.expected.c
tests/shell/gen/highlevel/struct.expected.h

[CM H2] cleanup copyright statements

---

.cirrus.yml
.github/workflows/macOS_gcc10.yml
doc/news/_preparation_next_release.md
src/tools/gen-gpg-testkey/gen-gpg-testkey.c

Fix 3806 testshell_markdown_tutorial_crypto: fails on macOS

---

doc/news/_preparation_next_release.md
doc/tutorials/plugins.md

doc: improve plugin tutorial

---

doc/INSTALL.md
doc/news/2014-07-28_0.8.7.md
doc/news/2017-03-18_lcdproc.md
doc/news/_preparation_next_release.md
scripts/cmake/ElektraPackaging.cmake
scripts/cmake/Modules/PackagingDebian.cmake
scripts/docker/debian/bullseye/Dockerfile
scripts/docker/debian/bullseye/release.Dockerfile
scripts/jenkins/Jenkinsfile
scripts/jenkins/Jenkinsfile.release
scripts/release/release.sh
tests/kdb/CMakeLists.txt

Create packages for Debian Bullseye

---

doc/news/_preparation_next_release.md
scripts/release/update-aptly-repo.sh

Aptly repositories will be automatically created if they do not exist during a package release.
Discussed in #3861.
If you are already Elektra …

Fix aptly repo creation

---

doc/news/2021-06-07_0.9.6.md
doc/news/_preparation_next_release.md
doc/todo/RELEASE.md
scripts/docker/alpine/3.13/release.Dockerfile

Releasenotes 0.9.6

---

doc/news/2021-06-07_0.9.6.md
doc/news/_preparation_next_release.md
doc/todo/NEWS.md

@mpranj: the release notes were already nearly perfect, thank you! The only real fix was JDK 9 instead of JDK 11 at one place.
If you are already …

doc: finalize release notes

---

doc/api_review/core/keyAddName.md
doc/api_review/core/keyGetBaseName.md
doc/api_review/core/keyGetBaseNameSize.md
doc/api_review/core/keyGetName.md
doc/api_review/core/keyGetNameSize.md
doc/api_review/core/keyGetNamespace.md
doc/api_review/core/keyGetUnescapedNameSize.md
doc/api_review/core/keyName.md
doc/api_review/core/keySetBaseName.md
doc/api_review/core/keySetName.md
doc/api_review/core/keySetNamespace.md
doc/api_review/core/keyUnescapedName.md
doc/news/_preparation_next_release.md
src/libs/elektra/keyname.c
tests/abi/testabi_key.c
tests/ctest/test_namespace.c

Add additional test cases for module keyname

---

doc/METADATA.ini
doc/man/man7/elektra-plugins.7
doc/news/_preparation_next_release.md
src/plugins/README.md
src/plugins/blacklist/CMakeLists.txt
src/plugins/blacklist/README.md
src/plugins/blacklist/blacklist.c
src/plugins/blacklist/blacklist.h
src/plugins/blacklist/testmod_blacklist.c

[CM H3] validation blacklist plugin

---

doc/news/_preparation_next_release.md
lgtm.yml
scripts/docker/alpine/3.13/release.Dockerfile
scripts/docker/arch/Dockerfile
scripts/docker/cirrus/fedora/Dockerfile
scripts/docker/debian/bullseye/Dockerfile
scripts/docker/debian/buster/Dockerfile
scripts/docker/debian/buster/i386.Dockerfile
scripts/docker/debian/buster/minimal.Dockerfile
scripts/docker/debian/sid/Dockerfile
scripts/docker/debian/sid/doc.Dockerfile
scripts/docker/debian/stretch/Dockerfile
scripts/docker/debian/stretch/i386.Dockerfile
scripts/docker/debian/stretch/minimal.Dockerfile
scripts/docker/fedora/31/Dockerfile
scripts/docker/fedora/32/Dockerfile
scripts/docker/fedora/33/Dockerfile
scripts/docker/fedora/34/Dockerfile
scripts/docker/jenkinsnode/Dockerfile
scripts/docker/ubuntu/bionic/Dockerfile
scripts/docker/ubuntu/focal/Dockerfile
scripts/docker/ubuntu/xenial/Dockerfile
scripts/docker/website/Dockerfile
scripts/docker/webui/base/Dockerfile
scripts/vagrant/ubuntu/artful32/Vagrantfile
tests/CMakeLists.txt

Update GoogleTest frameworks to v1.11.0. …

GoogleTest v1.11.0

---

doc/news/_preparation_next_release.md
src/plugins/python/python.cpp

python: fix format overflow

---

doc/news/_preparation_next_release.md
doc/tutorials/java-kdb.md
src/bindings/cpp/include/key.hpp

doc: small fixes

---

doc/news/_preparation_next_release.md
doc/tutorials/java-kdb.md
src/bindings/jna/libelektra/src/main/java/org/libelektra/Key.java
src/bindings/jna/libelektra/src/test/java/org/libelektra/KeyTest.java

#3874 removed Key::get*AndRelease convenience methods (from public api)

---

doc/news/_preparation_next_release.md
doc/todo/RELEASE.md
scripts/jenkins/Jenkinsfile
scripts/jenkins/Jenkinsfile.release
scripts/release/populate-release-notes.sh
scripts/release/release.sh

Closes #3897, closes #3900
This PR adds following:
- Deployment of the website during release
- More fail-save release pipeline and re-run of stages without any version conflict
- Automatic release notes population (hashsums, statistics and move to final name)
- Create diff of installed files
For docu fixes, …

Release pipeline improvements

---

doc/news/_preparation_next_release.md
scripts/jenkins/Jenkinsfile.release

Fixes an error that was introduced in #3899 where the wrong artifact path was used to copy packages from previous build stages.
If you are already …

release pipeline: fix invalid package artifact path

---

doc/METADATA.ini
doc/man/man7/elektra-plugins.7
doc/news/_preparation_next_release.md
src/plugins/README.md
src/plugins/email/CMakeLists.txt
src/plugins/email/README.md
src/plugins/email/email.c
src/plugins/email/email.h
src/plugins/email/test_email.h
src/plugins/email/testmod_email.c

[CM H3] introduce email validation plugin

---

doc/INSTALL.md
doc/news/_preparation_next_release.md

Changes the keyserver from keys.gnupg.net to keyserver.ubuntu.com as mentioned in #3918.
- Add the "work in …

doc: change gpg keyserver for receiving public gpg key for `apt`

---

doc/api_review/core/ksAppend.md
doc/api_review/core/ksAppendKey.md
doc/api_review/core/ksAtCursor.md
doc/api_review/core/ksCopy.md
doc/api_review/core/ksCurrent.md
doc/api_review/core/ksCut.md
doc/api_review/core/ksDel.md
doc/api_review/core/ksDup.md
doc/api_review/core/ksGetCursor.md
doc/api_review/core/ksGetSize.md
doc/api_review/core/ksHead.md
doc/api_review/core/ksLookup.md
doc/api_review/core/ksLookupByName.md
doc/api_review/core/ksNew.md
doc/api_review/core/ksNext.md
doc/api_review/core/ksPop.md
doc/api_review/core/ksRewind.md
doc/api_review/core/ksSetCursor.md
doc/api_review/core/ksTail.md
doc/api_review/core/ksVNew.md
doc/news/_preparation_next_release.md
tests/abi/testabi_ks.c

Add additional tests for module keyset

---

doc/news/_preparation_next_release.md
src/libs/elektra/kdb.c
src/libs/elektra/split.c
src/plugins/resolver/resolver.c

Fixes cache when using default backend. …

cache: fix default backend and initial parentKey

---

doc/news/_preparation_next_release.md
doc/todo/FUTURE
src/bindings/jna/libelektra/src/main/java/org/libelektra/Elektra.java
src/include/kdb.h.in
src/libs/elektra/keyset.c
src/libs/elektra/symbols.map
src/tools/elektrad/go.mod
src/tools/elektrad/go.sum
tests/abi/testabi_ks.c

Remove obsolete `ksNeedSync`

---

.cirrus.yml
.github/workflows/macOS.yml
.github/workflows/macOS_gcc10.yml
doc/news/_preparation_next_release.md

This PR migrates many macOS jobs to GitHub actions to speed up build time. (refs #3603)
- Add the "work in …

actions: add macOS job matrix

---

doc/AUTHORS.md
doc/news/_preparation_next_release.md
doc/todo/NEWS.md
src/plugins/mozprefs/README.md

authors: remove people without code

---

doc/news/_preparation_next_release.md
scripts/docker/alpine/3.14/release.Dockerfile
scripts/docker/debian/bullseye/release.Dockerfile
scripts/docker/debian/buster/release.Dockerfile
scripts/docker/fedora/33/release.Dockerfile
scripts/docker/fedora/34/release.Dockerfile
scripts/docker/ubuntu/bionic/release.Dockerfile
scripts/docker/ubuntu/focal/release.Dockerfile
scripts/docker/website/Dockerfile

docker: use tmpfs for `build` commands

---

doc/news/_preparation_next_release.md
doc/tutorials/java-kdb.md
src/bindings/jna/libelektra/src/main/java/org/libelektra/Elektra.java
src/bindings/jna/libelektra/src/main/java/org/libelektra/KDB.java
src/bindings/jna/libelektra/src/main/java/org/libelektra/Key.java
src/bindings/jna/libelektra/src/main/java/org/libelektra/KeySet.java
src/bindings/jna/libelektra/src/main/java/org/libelektra/KeySetIterator.java
src/bindings/jna/libelektra/src/main/java/org/libelektra/PluginLoader.java
src/bindings/jna/libelektra/src/test/java/org/libelektra/GOptsTest.java
src/bindings/jna/libelektra/src/test/java/org/libelektra/KDBTest.java
src/bindings/jna/libelektra/src/test/java/org/libelektra/KeySetTest.java
src/bindings/jna/libelektra/src/test/java/org/libelektra/KeyTest.java
src/libs/elektra/kdb.c

#3790 hid errorKey from KDB and refactored Key::createNameless

---

doc/news/_preparation_next_release.md
doc/tutorials/profiling.md
scripts/docker/fedora/33/release.Dockerfile
scripts/docker/fedora/34/release.Dockerfile
tests/linkchecker.whitelist

doc: fix broken links breaking build

---

doc/api_review/core/keyCopyAllMeta.md
doc/api_review/core/keyCopyMeta.md
doc/api_review/core/keyCurrentMeta.md
doc/api_review/core/keyGetMeta.md
doc/api_review/core/keyMeta.md
doc/api_review/core/keyNextMeta.md
doc/api_review/core/keyRewindMeta.md
doc/api_review/core/keySetMeta.md
doc/news/_preparation_next_release.md
src/libs/elektra/keymeta.c

doc: add pre/postconditions and invarians to module keymeta

---

doc/api_review/core/keyCmp.md
doc/api_review/core/keyIsBelow.md
doc/api_review/core/keyIsBinary.md
doc/api_review/core/keyIsDirectlyBelow.md
doc/api_review/core/keyIsString.md
doc/api_review/core/keyNeedSync.md
doc/news/_preparation_next_release.md
src/libs/elektra/keyset.c
src/libs/elektra/keytest.c

doc: add pre/postconditions and invariants to module keytest

---

doc/news/_preparation_next_release.md
src/tools/fuse/src/elektra_fuse/elektra_util.py

Commit 9b42852e5c91c61b14c58fba29d7c99af75849cb introduced a regression hindering binary data to be written to regular keys. This PR fixes said mistake.
Reviewers will usually check the …

FUSE: fix bug preventing binary writes

---

.cirrus.yml
.github/workflows/macOS.yml
.restyled.yaml
doc/CODING.md
doc/news/_preparation_next_release.md
scripts/dev/reformat-javascript
scripts/dev/reformat-markdown
scripts/docker/debian/bullseye/Dockerfile
scripts/docker/debian/buster/Dockerfile
scripts/docker/debian/sid/Dockerfile
scripts/docker/debian/stretch/Dockerfile
src/tools/website/Gruntfile.js
src/tools/website/public/vendor/asciinema/asciinema-player.js
src/tools/website/resources/assets/js/config/marked.js
src/tools/website/resources/grunt-tasks/grunt-copy-website-content.js
src/tools/webui/src/components/TreeItem/dialogs/AddDialog.jsx
src/tools/webui/src/components/TreeItem/dialogs/EditDialog.jsx
src/tools/webui/src/components/TreeItem/dialogs/SettingsDialog.jsx
src/tools/webui/src/components/TreeItem/index.js
tests/linkchecker.whitelist

Restyled updates

---

doc/news/_preparation_next_release.md
scripts/jenkins/Jenkinsfile

jenkinsfile: move basic checks to dedicated stage

---

doc/api_review/core/keyCmp.md
doc/api_review/core/keyIsBelow.md
doc/api_review/core/keyIsBinary.md
doc/api_review/core/keyIsDirectlyBelow.md
doc/api_review/core/keyIsString.md
doc/api_review/core/keyNeedSync.md
doc/news/_preparation_next_release.md
tests/abi/testabi_key.c
tests/abi/testabi_rel.c
tests/ctest/test_key.c

Add additional test cases for module keytest

---

doc/api_review/core/keyGetBinary.md
doc/api_review/core/keyGetString.md
doc/api_review/core/keyGetValueSize.md
doc/api_review/core/keySetBinary.md
doc/api_review/core/keySetString.md
doc/api_review/core/keyString.md
doc/api_review/core/keyValue.md
doc/news/_preparation_next_release.md
src/libs/elektra/keyvalue.c

doc: add pre/postconditions and invariants to module keyvalue

---

doc/news/2015-04-03_0.8.11.md
doc/news/2016-04-29_0.8.16.md
doc/news/2016-12-17_website_release.md
doc/news/_preparation_next_release.md

Fixes broken links mentioned in #4058 …

Fix broken links

---

doc/news/_preparation_next_release.md
src/libs/highlevel/elektra.c

I discovered a small bug introduced by #4063 .
For details please see commit message.
- Add the "work in …

Fix extraction of first warning in HL API.

---

doc/news/_preparation_next_release.md
scripts/docker/debian/bullseye/Dockerfile
scripts/docker/debian/buster/Dockerfile
scripts/docker/ubuntu/focal/Dockerfile

disable rust

---

doc/news/_preparation_next_release.md
scripts/docker/debian/bullseye/Dockerfile
scripts/docker/ubuntu/focal/Dockerfile

rust: try to reenable rust

---

doc/news/_preparation_next_release.md
scripts/link-checker
tests/linkchecker.whitelist

Cleanup tests/linkchecker.whitelist and fix off-by-1 bug of counter in the scripts/link-checker script
- Add …

[FLOSS H2] Cleanup tests/linkchecker.whitelist and fix off-by-1 bug of counter

---

doc/news/_preparation_next_release.md
src/tools/fuse/src/elektra_fuse/rootlevel_resolver.py

[FLOSS H2] fuse: stat path before opening it

---

doc/DESIGN.md
doc/news/_preparation_next_release.md

[FLOSS H2] doc: fix wording in DESIGN.md

---

doc/news/_preparation_next_release.md
scripts/docker/centos/stream8/Dockerfile
scripts/docker/debian/bullseye/Dockerfile
scripts/docker/debian/buster/Dockerfile
scripts/docker/debian/sid/Dockerfile
scripts/docker/debian/stretch/Dockerfile
scripts/docker/fedora/31/Dockerfile
scripts/docker/fedora/32/Dockerfile
scripts/docker/fedora/33/Dockerfile
scripts/docker/fedora/34/Dockerfile
scripts/docker/jenkinsnode/Dockerfile
scripts/docker/opensuse/15.3/Dockerfile
scripts/docker/ubuntu/bionic/Dockerfile
scripts/docker/ubuntu/focal/Dockerfile

As described in #4035, adding explicit lines to `.bashrc` may break the PATH of the container
and is rendered useless because of the `ENV` instruction, which preserves environment variables for all subsequent instructions:
https://docs.docker.com/engine/reference/builder/#env
Not only do we fix #4035, we also reduce the sizes of the images by removing a useless instruction
But we cannot accept PRs that do not fulfill the …

[FLOSS H2] scripts: fix overwriting PATH variable in Dockerfiles

---

doc/news/_preparation_next_release.md
tests/ctest/test_key.c

[FLOSS H2]
For this pull request I have tried to fix a ToDo in the `keyTest.c` file: I have added more test cases for the keyCopy function.
Should I remove the "FIXME?"
Reviewers will usually …

[FLOSS H2] Added more key copy tests

---

doc/news/_preparation_next_release.md
src/libs/elektra/keyname.c

[FLOSS H2] replace code in keyReplacePrefix with respective keyCopy call

---

doc/news/_preparation_next_release.md
src/bindings/intercept/env/tests/test_getenv.cpp

[FLOSS T1] Add printVersion tests for getenv

---

doc/news/_preparation_next_release.md
src/plugins/uname/uname.c

[FLOSS H2] reformat function call in uname.c to be more in-line with current code style

---

doc/COMPILE.md
doc/news/_preparation_next_release.md

[FLOSS H2] docs: Improve docs/COMPILE.md with clearer instructions

---

doc/GETSTARTED.md
doc/news/_preparation_next_release.md

[FLOSS H2] docs: Fix some typos and wording in docs/GETSTARTED.md

---

doc/news/_preparation_next_release.md
doc/tutorials/run_all_tests_with_docker.md

Podman is an open source, daemonless container engine and can be used as drop in replacement for docker. However, some things like volume mounts work a little bit different. I added to the [run all tests with docker tutorial](https://www.libelektra.org/tutorials/run-all-tests-with-docker) alternative instructions on how to run the container with podman.
Check relevant …

[FLOSS H2] Added documentation on how to run all tests with podman instead of docker

---

doc/man/man1/kdb-convert.1
doc/news/_preparation_next_release.md
doc/tutorials/python-kdb.md

Added a small tutorial for a debian buster container
- Add the "work in progress" label if you do not want …

[FLOSS T2] Doc: Added debian buster tutorial

---

doc/news/_preparation_next_release.md
examples/keyCopyExample.c

I have added a new example program to illustrate the usage of `keyCopy`.
- Add the "work in progress" label …

[FLOSS H2] New keyCopy example

---

doc/man/man1/kdb-convert.1
doc/news/_preparation_next_release.md
src/libs/elektra/kdb.c

[FLOSS H2] Core: Added else error to kdbc

---

doc/news/_preparation_next_release.md
src/bindings/cpp/tests/testcpp_key.cpp

[FLOSS T1] Add exception tests for key c++ bindings

---

doc/news/_preparation_next_release.md
doc/tutorials/namespaces.md

I fixed some small typos in the namespaces tutorial.
- Add the "work in progress" label if you do not want …

[FLOSS H2] Fixed some simple typos in the namespaces tutorial.

---

doc/news/_preparation_next_release.md
src/tools/website/resources/structure.json.in

Add some pages that were in the documentation but were missing in the libelektra website.
Closes #4098
- Add …

[FLOSS H3] Integrate missing pages into website

---

.cirrus.yml
doc/news/_preparation_next_release.md
scripts/dev/filename-checker
scripts/jenkins/Jenkinsfile
tests/filename.whitelist

This will fix #1615. I have created a shell script that check the file names of the whole repository. It is integrated in the Cirrus CI. I tried to make  comments and explain my thought process in the shell scrip. Suggestions on how to implement it more elegantly or robust are very welcome! 
- [s] Details of what you changed are in commit messages
Check relevant …

[FLOSS H3] File name checker for CI

---

doc/news/_preparation_next_release.md
src/libs/elektra/keymeta.c
tests/abi/testabi_meta.c

[FLOSS H3] Fix #3981

---

doc/API.md
doc/BIGPICTURE.md
doc/decisions/array.md
doc/decisions/base_name.md
doc/decisions/error_handling.md
doc/dev/algorithm.md
doc/dev/data-structures.md
doc/dev/plugins-framework.md
doc/help/elektra-bootstrapping.md
doc/help/kdb-meta-get.md
doc/man/man1/kdb-meta-get.1
doc/man/man7/elektra-bootstrapping.7
doc/markdownlinkconverter/README.md
doc/news/_preparation_next_release.md
doc/todo/NEWS.md
doc/tutorials/application-integration.md
doc/tutorials/mount.md
doc/tutorials/plugins.md
doc/tutorials/validation.md
scripts/sed
src/plugins/fcrypt/README.md
src/plugins/file/README.md
src/plugins/ni/README.md

Fix a bug and some overmatching problems in `scripts/sed` and update the documentation via execution of the `scripts/dev/fix-spelling` script
PS: I thought about whether I should add the [FLOSS H3] prefix to this PR, but if I get one or two extra points I won't complain about it. ;)
If not, it's also fine. …

[FLOSS H3] Fix some errors in sed-script & spelling errors in documentation

---

doc/news/_preparation_next_release.md
doc/tutorials/arrays.md

Some key creation commands were missing automatic verification in the "Arrays" (docs/tutorials/arrays.md) tutorial. This PR adds this verification
There was no teamwork in this task as I don't have a teammate.
(not in …

[FLOSS T2] docs: added verification to the "Arrays" tutorial

---

doc/CONTRACT.ini
doc/news/_preparation_next_release.md
examples/spec/cassandra.ini

As mentioned in #4060, `type=int` is deprecated and should be replaced everywhere. Some files slipped and this aims to fix them as well
Closes #4060 
Reviewers will usually check the …

[FLOSS H3] Replace type=int in ini files

---

doc/news/_preparation_next_release.md
src/libs/loader/doc.c
src/libs/meta/meta.c

With this PR we would like to improve core API documentation.
_Who did which parts of this task:_ 
We discussed areas where the documentation could be improved together as team. Then each team member picked on of the topics and created a PR.
_On which CI systems the tests run_
The same as in T1.
---
This is still work in progress: We want to improve some wording and layout of the API
But we cannot accept PRs that do not …

[T2 FLOSS] Improvements to the api doc

---

doc/news/_preparation_next_release.md
doc/tutorials/validation.md

Some key creation commands were missing automatic verification in the "Validation" (docs/tutorials/validation.md) tutorial. This PR adds this verification.
Additionally, an example with a failing command has been added.
There was no teamwork in this task as I don't have a teammate.
For docu fixes, spell …

[FLOSS T2] docs: added verification and expanded the "Validation" tutorial

---

doc/news/_preparation_next_release.md
src/plugins/quickdump/quickdump.c

quickdump: fix type-limits warning on arm32

---

doc/news/_preparation_next_release.md
scripts/sed

[FLOSS T2] JSON spelling

---

doc/news/_preparation_next_release.md
src/plugins/augeas/README.md
src/plugins/base64/README.md
src/plugins/crypto/README.md
src/plugins/desktop/README.md
src/plugins/error/README.md
src/plugins/fstab/README.md
src/plugins/gitresolver/README.md
src/plugins/iterate/README.md
src/plugins/logchange/README.md
src/plugins/passwd/README.md
src/plugins/python/README.md
tests/shell/shell_recorder/tutorial_wrapper/CMakeLists.txt

As the title suggests the idea of the PR is to enable the shell recorder tests for all plugins. For a lot of the plugins these tests already work as intended. However, some need still some work.
This fixes #1498 and closes #4200
need to be …

[FLOSS H3] enable all shell recorder

---

doc/news/_preparation_next_release.md
doc/tutorials/storage-plugins.md

[FLOSS T2] improve storage plugin tutorial by adding sections about ordering and comments

---

doc/GETSTARTED.md
doc/news/_preparation_next_release.md

[FLOSS H2] Small correction of the build path in the "Get Strarted" guide

---

doc/help/kdb-test.md
doc/man/man1/kdb-test.1
doc/news/_preparation_next_release.md
tests/shell/shell_recorder/tutorial_wrapper/CMakeLists.txt

[FLOSS T2] tests: add shell recorder tests to kdb-test.md

---

doc/news/_preparation_next_release.md
src/bindings/jna/hello/src/main/java/HelloElektra.java

[FLOSS H3] jna: extend HelloElektra #4093

---

doc/help/elektra-backends.md
doc/man/man7/elektra-backends.7

[FLOSS H2] doc: fix typo in man page elektra-backends 2

---

doc/man/man1/kdb-run-website.1
doc/news/_preparation_next_release.md
src/tools/website/README.md

expanded [webside readme](https://github.com/ElektraInitiative/libelektra/tree/master/src/tools/website) to clarify.
If you are already Elektra …

[FLOSS H2] Added external links and clarification to websideguide

---

doc/news/_preparation_next_release.md
scripts/keynames.py
src/libs/elektra/keyname.c

keyname: fix bug with colon in cascading name

---

doc/help/kdb-mount.md
doc/man/man1/kdb-mount.1
doc/news/_preparation_next_release.md
src/tools/kdb/cmdline.cpp
src/tools/kdb/mount.cpp
src/tools/kdb/mount.hpp

[FLOSS H3] Remove mountpoint names

---

doc/AUTHORS.md
doc/news/_preparation_next_release.md
doc/tutorials/contributing-clion.md

Fix small error in CLion tutorial: CMake options would create a directory named `~` in home directory

Correct a small issue in the CLion tutorial

---

CMakeLists.txt
doc/news/_preparation_next_release.md
scripts/kdb/CMakeLists.txt
src/plugins/process/README.md
tests/shell/external/CMakeLists.txt

scripts: fix exclusion of mount-java and tests

---

doc/README.md
doc/news/_preparation_next_release.md

[CM H0] readability improvement

---

doc/news/_preparation_next_release.md
doc/tutorials/code-generator.md

[CM H0] Enhance code-generator doc readability

---

doc/COMPILE.md
doc/help/kdb.md
doc/man/man1/kdb.1
doc/news/_preparation_next_release.md

[CM H0] doc: fix dead link and compile instructions

---

doc/CODING.md
doc/news/_preparation_next_release.md

[CM H0] improves readability of CODING.md

---

doc/news/_preparation_next_release.md
src/libs/tools/src/errors/errorFactory.cpp
src/libs/tools/tests/testtool_error.cpp

[CM H0] Libtools: Add tests for Error/Warning-Factory

---

doc/news/_preparation_next_release.md
tests/linkchecker.whitelist

Update the link list from the certificate section in `tests/linkchecker.whitelist`.

[CM H0] Fix certificate section

---

doc/README.md
doc/news/_preparation_next_release.md

[CM H0] Doc/readability improvment

---

.gitattributes
doc/news/_preparation_next_release.md
doc/tutorials/contributing-windows.md

Adds .gitattributes file and updates Windows tutorial

Gitattributes

---

doc/news/_preparation_next_release.md
src/bindings/jna/CMakeLists.txt
src/bindings/jna/build.gradle
src/bindings/jna/plugins/build.gradle

jna: auto-detect plugins in CMake via Gradle task

---

doc/news/_preparation_next_release.md
doc/tutorials/cascading.md
doc/tutorials/command-line-options.md

This T1-PR was done by me, Florian Lindner.

[CM T1] Fix errors in tutorials for Cascading Lookups and Command-line Options

---

doc/news/_preparation_next_release.md
src/bindings/jna/gradlew.bat
src/bindings/jna/hello/src/main/java/HelloElektra.java

doc/news: Added entry for jna example

[CM T1] jna: Added example which shows how to add a basename for a key.

---

doc/news/_preparation_next_release.md
src/bindings/jna/README.md

@bhampl improved the JNA documentation

[CM T1] jna: Improve JNA documentation

---

doc/GETSTARTED.md
doc/news/_preparation_next_release.md
tests/linkchecker.whitelist

This PR was done by Michael Langhammer, Florian Lindner did some formatting and rebased with current master.

[CM T1] doc: Overhauls the GETSTARTED.md by adding a brief kdb introduction

---

doc/news/_preparation_next_release.md
doc/tutorials/java-kdb.md

@Eiskasten added the example for the Java Stream API in the Java binding tutorial.

[CM T1] doc: Add stream api in java binding

---

doc/news/_preparation_next_release.md
doc/tutorials/java-kdb.md

@bhampl fixed the documentation and searched for occurrences of the mistake @Eiskasten.
We did not find any further mentions of `KDB.KDBException` in the documentation.

[CM T1] doc: Fix wrong KDBException in java tutorial

---

doc/news/_preparation_next_release.md
src/bindings/swig/python/tests/test_keyset.py

[CM T1] python binding: added unit tests for len, reversed, head and tail methods to keySet tests

---

doc/news/_preparation_next_release.md
src/bindings/jna/plugins/sorted/README.md
src/bindings/jna/plugins/sorted/src/main/java/org/libelektra/plugin/SortedContract.java
src/bindings/jna/plugins/sorted/src/main/java/org/libelektra/plugin/SortedMetadata.java
src/bindings/jna/plugins/sorted/src/main/java/org/libelektra/plugin/SortedPlugin.java
src/bindings/jna/plugins/sorted/src/test/java/org/libelektra/plugin/SortedPluginTest.java
src/bindings/jna/plugins/sorted/src/test/java/org/libelektra/plugin/TestData.java
src/bindings/jna/settings.gradle

[CM T2] Java Sorted Plugin

---

doc/news/_preparation_next_release.md
src/bindings/swig/python/examples/example_key.py

[CM T3] python: fullname property in docs

---

doc/dev/README.md
doc/dev/iterators.md
doc/news/_preparation_next_release.md
tests/linkchecker.whitelist

[CM P0] Replace internal iterators

---

.idea/codeStyles/Project.xml
doc/news/_preparation_next_release.md
src/plugins/length/README.md
src/plugins/length/length.c
src/plugins/length/test_length.h

[CM T3] plugin/length: warnings are now added when performing kdb get

---

doc/dev/data-structures.md
doc/dev/iterators.md
doc/news/_preparation_next_release.md
tests/linkchecker.whitelist

[CM Project Followup] Updates iterator documentation

---

doc/news/_preparation_next_release.md
doc/tutorials/specification.md

[CM T1] tutorial: add cleanup section to the specification tutorial

---

doc/news/_preparation_next_release.md
src/bindings/jna/hello-kotlin/src/main/kotlin/HelloElektra.kt
src/bindings/jna/libelektra-kotlin/README.md
src/bindings/jna/libelektra-kotlin/src/main/kotlin/org/libelektra/dsl/KeyDSL.kt
src/bindings/jna/libelektra-kotlin/src/main/kotlin/org/libelektra/dsl/KeySetDSL.kt
src/bindings/jna/libelektra-kotlin/src/main/kotlin/org/libelektra/keyExt/SetExt.kt
src/bindings/jna/libelektra-kotlin/src/main/kotlin/org/libelektra/keyExt/Util.kt
src/bindings/jna/libelektra-kotlin/src/main/kotlin/org/libelektra/keySetExt/Util.kt
src/bindings/jna/libelektra-kotlin/src/main/kotlin/org/libelektra/keySetExt/serialformat/KeySetEncoder.kt
src/bindings/jna/libelektra-kotlin/src/test/kotlin/org/libelektra/key/SetKeyTest.kt
src/bindings/jna/libelektra-kotlin/src/test/kotlin/org/libelektra/key/UtilTest.kt
src/bindings/jna/libelektra-kotlin/src/test/kotlin/org/libelektra/keySet/KeySetEncodeDecodeTest.kt
src/bindings/jna/libelektra-kotlin/src/test/kotlin/org/libelektra/keySet/KeySetSerializationTest.kt
src/bindings/jna/libelektra-kotlin/src/test/kotlin/org/libelektra/keySet/UtilTest.kt

Fixes according to #4368 
Also includes new find functions on KeySets

[CM T3] Kotlin binding refinement: null values, restructure, find methods

---

.github/dependabot.yml
doc/news/_preparation_next_release.md

[CM T3] dependabot: add dependabot.yml [fixes #4277]

---

doc/news/_preparation_next_release.md
src/bindings/cpp/include/kdbcontext.hpp
src/bindings/cpp/include/kdbvalue.hpp
src/bindings/intercept/env/tests/test_fork.cpp
src/libs/elektra/kdb.c
src/libs/elektra/keyset.c
src/libs/elektra/keyvalue.c
src/libs/elektra/mount.c
src/libs/elektra/plugin.c
src/libs/elektra/split.c
src/libs/elektra/trie.c
src/plugins/curlget/curlget.c
src/tools/qt-gui/src/treeviewmodel.cpp

[CM T3] removed mentions of VERBOSE and HAVE_STDIO_H

---

doc/news/_preparation_next_release.md
src/bindings/swig/ruby/kdb.i
src/plugins/date/testmod_date.c

Fixes #4392
Also fixes a bug in the tests of the date plugin

Fixes for Alpine Linux builds

---

doc/man/README.md
doc/news/_preparation_next_release.md
doc/todo/NEWS.md

Hopefully Last Fixes for Release

---

doc/news/_preparation_next_release.md
src/libs/opts/opts.c
tests/ctest/test_opts.c

Prevent `argString` from being freed if it was not actually changed. And add modify `test_help` in `test_opts` to trigger the "free(): invalid pointer" error.

close #4434: opts: fix possible 'invalid pointer' error

---

doc/news/_preparation_next_release.md
src/plugins/csvstorage/csvstorage.c

This is partly based on #4341, but is superiour because we do not remove the whole check. The argument `colNames` might still be `NULL` so we should really keep the fallback.

csvstorage: remove superfluous if-conditions that fail the build on Debian Unstable

---

.cirrus.yml
doc/news/_preparation_next_release.md

Update FreeBSD images to 13.1 and 12.3 and update packages before builds.

cirrus: update FreeBSD images to 13.1 and 12.3 and update packages

---

doc/news/_preparation_next_release.md
doc/todo/TESTING
scripts/docker/cirrus/fedora/Dockerfile
scripts/docker/fedora/36/Dockerfile
scripts/docker/fedora/36/abi.Dockerfile
scripts/docker/fedora/36/package.Dockerfile
scripts/docker/fedora/36/release.Dockerfile
scripts/jenkins/Jenkinsfile
scripts/jenkins/Jenkinsfile.release
src/bindings/cpp/include/key.hpp
src/plugins/ruby/CMakeLists.txt
src/tools/kdb/gen/highlevel/common.hpp
src/tools/kdb/gen/mustache.hpp

Adds Fedora 36 images and builds.
Closes #3885.

docker: add Fedora 36

---

.github/PULL_REQUEST_TEMPLATE.md
.github/stale.yml
LICENSE.md
doc/contrib/documentation.md
doc/decisions/elektra_prefix.md
doc/decisions/private_api.md
doc/dev/architecture.md
doc/dev/data-structures.md
doc/help/elektra-glossary.md
doc/man/man7/elektra-glossary.7
doc/news/_preparation_next_release.md
scripts/dev/reformat-all
scripts/dev/run_checkshell.in
src/bindings/template/README.md
src/libs/template/README.md
src/plugins/csvstorage/csvstorage.c
src/plugins/lua/CMakeLists.txt
src/plugins/template/README.md
src/plugins/type/testmod_type.c
src/tools/fuse/README.md
src/tools/kdb/gen/highlevel/highlevel.cpp
src/tools/template/README.md
src/tools/website/resources/structure.json.in

updates for upcoming release

---

doc/news/_preparation_next_release.md
doc/todo/NEWS.md

news: finish release notes

---

doc/news/_preparation_next_release.md
src/tools/website/package-lock.json

website: update deps

---

src/plugins/resolver/testmod_resolver.c

[FLOSS H3] testmod_resolver fixes for new Backend

---

doc/news/_preparation_next_release.md
scripts/docker/debian/sid/Dockerfile

Update pcre packagename from debian sid

---

doc/Doxyfile
doc/news/2015-09-17_0.8.13.md
doc/news/2015-11-19_0.8.14.md
doc/news/_preparation_next_release.md
src/bindings/intercept/env/src/getenv.cpp
src/bindings/intercept/env/tests/test_getenv.cpp
src/libs/getenv/README.md
src/plugins/desktop/README.md

fix getenv

---

doc/news/_preparation_next_release.md
scripts/jenkins/Jenkinsfile

jenkins improvements

---

doc/news/_preparation_next_release.md
src/tools/kdb/find.cpp

[FLOSS H2/H3] Fix SIGSEGV in kdb find

---

doc/news/_preparation_next_release.md
src/libs/pluginprocess/tests/CMakeLists.txt

Newer versions of CMake require source files to be specified including the file extension.
https://cmake.org/cmake/help/latest/policy/CMP0115.html
Fixes #4522

[FLOSS H3] CMake: Fix warning for CMP0115

---

doc/COMPILE.md
doc/news/_preparation_next_release.md

[FLOSS H2] Documentation: Improve page for compilation

---

doc/news/_preparation_next_release.md
src/bindings/intercept/fs/intercept.c

fix intercept/fs

---

.github/workflows/macOS.yml
doc/news/_preparation_next_release.md

This PR introduces a new job in the elektra GitHub actions pipeline. The new cancel job assures that current actions are cancelled if there a newer actions on the same branch.

ci: add cancellation job to github action

---

doc/news/_preparation_next_release.md
src/plugins/logchange/logchange.c

logchange: add notification-send hooks to contract

---

.github/PULL_REQUEST_TEMPLATE.md
doc/decisions/EXPLANATIONS.md
doc/decisions/README.md
doc/decisions/TEMPLATE.md
doc/decisions/decision_process.md
doc/decisions/man_pages.md
doc/decisions/manpages.md
doc/news/_preparation_next_release.md

decisions: decide process, improve manpages

---

doc/news/_preparation_next_release.md
src/bindings/README.md

* Fixes broken link (#4525)
* Improves discoverability on website
Closes #4525

[FLOSS H2] Documentation: Bindings

---

.github/CONTRIBUTING.md
doc/news/_preparation_next_release.md

[FLOSS H2] documentation: fix some minor mistakes in CONTRIBUTING.md

---

doc/news/_preparation_next_release.md
doc/tutorials/run_all_tests_with_docker.md

The link now goes to the relevant Podman documentation (as opposed to being a link to the general website hosting the Podman documentation).

[FLOSS H2] Documentation: Improve external link

---

doc/news/_preparation_next_release.md
src/tools/elektrad/package-lock.json

[FLOSS H3] Delete leftover package-lock.json

---

doc/news/_preparation_next_release.md
doc/tutorials/command-line-options.md

Fix the internal links to the section "Manually Generating the Help Message" in the page <https://www.libelektra.org/tutorials/command-line-options>. Note that this style of adding the HTML anchor in the Markdown file is already used within the same document.

[FLOSS H2] Documentation: Fix internal link

---

doc/INSTALL.md
doc/news/_preparation_next_release.md

- Update Link from  AUR package to , partially fixing #4539
- Add notice to link, that the package is hosted in the AUR and not in the Arch Linux package repository
- Add instructions how to manually install the package from AUR
- [ x References to issues, e.g. `close #X`, are in the commit messages.

[FLOSS H2] Add Installation instructions for Arch

---

doc/help/elektra-granularity.md
doc/man/man7/elektra-granularity.7
doc/news/_preparation_next_release.md

[FLOSS H2] Fix grammar for elektra-granularity.md

---

doc/dev/hooks.md
doc/news/_preparation_next_release.md

[FLOSS H2] Fix typo in doc/dev/hooks.md

---

doc/news/_preparation_next_release.md
doc/tutorials/highlevel.md

[FLOSS H2] Improve readability of doc/tutorials/highlevel.md

---

doc/GETSTARTED.md
doc/news/_preparation_next_release.md

relevant issue https://github.com/ElektraInitiative/libelektra/issues/4508

doc: Update Getstarted with links to documentation

---

doc/dev/error-categorization.md
doc/dev/error-handling.md
doc/dev/error-message.md
doc/news/_preparation_next_release.md

[FLOSS H2] Rephrase sections in doc/dev/error-*

---

doc/GETSTARTED.md
doc/news/_preparation_next_release.md

Remove 'Don't Panic" note from Git
When you have not panicked at "Unix-based OS" or "command line interface" you probably won't when reading Git, as it is pretty standard now.
But we should probably add a note at make/cmake or C ;)

[FLOSS H2] doc: remove "Don't panic" from Git

---

doc/news/_preparation_next_release.md
scripts/docker/alpine/3.16/Dockerfile
scripts/docker/alpine/3.16/release.Dockerfile
scripts/docker/centos/stream8/Dockerfile
scripts/docker/cirrus/fedora/Dockerfile
scripts/docker/debian/bullseye/Dockerfile
scripts/docker/debian/buster/Dockerfile
scripts/docker/debian/sid/Dockerfile
scripts/docker/fedora/31/Dockerfile
scripts/docker/fedora/32/Dockerfile
scripts/docker/fedora/33/Dockerfile
scripts/docker/fedora/34/Dockerfile
scripts/docker/fedora/35/Dockerfile
scripts/docker/fedora/36/Dockerfile
scripts/docker/fedora/37/Dockerfile
scripts/docker/fedora/37/abi.Dockerfile
scripts/docker/fedora/37/package.Dockerfile
scripts/docker/fedora/37/release.Dockerfile
scripts/docker/jenkinsnode/Dockerfile
scripts/docker/opensuse/15.3/Dockerfile
scripts/docker/ubuntu/bionic/Dockerfile
scripts/docker/ubuntu/focal/Dockerfile
scripts/jenkins/Jenkinsfile
scripts/jenkins/Jenkinsfile.release
src/bindings/jna/gradle/wrapper/gradle-wrapper.properties

Fedora 37 and CI updates

---

doc/news/_preparation_next_release.md
src/libs/io/io.c

[FLOSS H2] io file flag check

---

README.md
doc/news/_preparation_next_release.md

[FLOSS T1] Fixed Coverage Badge Link

---

doc/news/_preparation_next_release.md
doc/tutorials/mount.md
scripts/sed

[FLOSS H2] Reinstate Mounting tutorial

---

doc/news/_preparation_next_release.md
src/plugins/uname/README.md
src/plugins/uname/uname.c

[FLOSS H2] Add uname error handling

---

doc/news/_preparation_next_release.md
tests/shell/shell_recorder/shell_recorder.sh

The shell recorder was not parsing warning correctly after the error code format has changed. This PR addresses this issue.

[FLOSS T1] fix: shell recorder warnings parsing

---

doc/news/_preparation_next_release.md
src/bindings/jna/README.md

I've explicitly added the problems I ran into while trying to compile JNA, to make life easier for people who might encounter the same problems in the future

[FLOSS H2] jna: Update compilation instructions in readme.md

---

doc/VISION.md
doc/news/_preparation_next_release.md

[FLOSS H2] Fix outdated ansible example in vision.md

---

doc/news/_preparation_next_release.md
tests/shell/shell_recorder/mathcheck.esr
tests/shell/shell_recorder/selftest.esr

Some shell recorder were failing (only on manual execution see https://github.com/ElektraInitiative/libelektra/issues/4702)
This PR fixes / extends some of them:
Regarding profiletest.esr and listtest.esr - these also fail but i am not sure what they are intended to test.

[FLOSS T1] shellrecorder: fix/extends two shell recorder checks

---

doc/decisions/0_drafts/readonly_keynames.md
doc/news/_preparation_next_release.md

[decision] Read-only key names

---

doc/news/_preparation_next_release.md
scripts/docker/debian/bullseye/Dockerfile
scripts/docker/debian/buster/Dockerfile
scripts/docker/debian/sid/Dockerfile

As discussed in #4497 shellcheck should be integrated into the standard workflow.
I have added shellcheck to the list of dependencies in the Debian Docker containers. I have verified that shellcheck is available in the repository of the corresponding releases.

[FLOSS T1] Add shellcheck to Debian containers

---

doc/INSTALL.md
doc/news/_preparation_next_release.md

Use of back ticks to mark `package names` and  `global variable names` in [INSTALL.md](https://github.com/ElektraInitiative/libelektra/blob/master/doc/INSTALL.md)
For package names, this was already done in Line 119 with `base_devel` and `git`
(first line should have `module: short statement` syntax) -> I learned about this convention too late, not consistently done

[FLOSS H2] doc: Use of `Code` blocks on package and variable names in INSTALL.md

---

doc/CMakeLists.txt
doc/Doxyfile
doc/news/_preparation_next_release.md

* Removal of `LATEX_CMD_NAME`: Not needed because `USE_PDFLATEX` is set.
* Move inclusion of custom sty file to Doxygen instead of CMake.
Closes #4533

[FLOSS H3] Doxygen: Update Doxyfile and CMake configuration

---

doc/markdownlinkconverter/README.md
doc/news/_preparation_next_release.md

[FLOSS H3] Linkchecker/doc

---

doc/man/man7/elektra-glossary.7
doc/news/_preparation_next_release.md
doc/usecases/kdb/UC_modify_config.md
doc/usecases/kdb/UC_uptodate_config.md
doc/usecases/kdb/UC_validate_config.md

close issue #4752
The following files in [doc/usecases/kdb/](https://github.com/ElektraInitiative/libelektra/tree/master/doc/usecases/kdb) were renamed, but links to them in other files were not updated:
- UC_load_config.md -> UC_get_config.md
- UC_store_config.md -> UC_set_config.md
This PR fixes the affected links in the following files:
- UC_modify_config.md
- UC_uptodate_config.md
- UC_validate_config.md

Documentation: Fix broken links in kdb use cases

---

doc/news/_preparation_next_release.md
doc/todo/NEWS.md
doc/usecases/template.md

improve use cases template

---

doc/news/_preparation_next_release.md
src/tools/website/resources/structure.json.in

Removing the `TESTING.md` from the documentation menu on the website, as it is also available in the menu developer and therefore duplicated
I worked together with @stefnotch on this (pair programming)

[FLOSS T2] Remove duplicated `TESTING.md` link from website

---

doc/INSTALL.md
doc/news/_preparation_next_release.md

I updated the documentation explaining how to create a package on Fedora.

[FLOSS T2] Documentation: Update packaging instructions for Fedora

---

doc/KEYNAMES.md
doc/contrib/copy_on_write.md
doc/contrib/documentation.md
doc/decisions/0_drafts/change_tracking.md
doc/decisions/0_drafts/plugin_contract_function.md
doc/decisions/2_in_progress/iterators.md
doc/decisions/3_decided/header_include.md
doc/decisions/3_decided/iterating_name_parts.md
doc/dev/error-handling.md
doc/dev/iterators.md
doc/news/_preparation_next_release.md
doc/tutorials/command-line-options.md
doc/tutorials/highlevel-bindings.md
doc/tutorials/notifications.md

This PR fixes various spelling errors.

[FLOSS T2] docs: fix spelling errors

---

doc/news/_preparation_next_release.md
src/plugins/csvstorage/csvstorage.c
src/plugins/csvstorage/testmod_csvstorage.c

[FLOSS H3] csvstorage: fix silent failure on meta-key insertion

---

doc/news/_preparation_next_release.md
scripts/build/run_check_release_notes
scripts/dev/copy-template
scripts/dev/untidy-source
src/bindings/jna/CMakeLists.txt
tests/shell/check_bashisms.sh
tests/shell/check_kdb_internal_check.sh
tests/shell/include_common.sh.in
tests/shell/shell_recorder/tutorial_wrapper/markdown_shell_recorder.sh

@0x6178656c noticed, that the function `egrep`, that is deprecated since 2007, is still being used.
Due to recent changes in GNU 3.8, the usage `egrep` prints a warning.
This was also mentioned in their [release note](https://lists.gnu.org/archive/html/info-gnu/2022-09/msg00001.html)
I fixed the issue, by replacing `egrep` by `grep -E`

[FLOSS T1] Replace deprecated egrep

---

doc/news/_preparation_next_release.md
scripts/docker/debian/bullseye/Dockerfile
src/bindings/rust/elektra-sys/Cargo.toml.in
src/bindings/rust/elektra/Cargo.toml.in
src/bindings/rust/example/Cargo.toml.in

rust: fix "feature `resolver` is required" error

---

doc/news/_preparation_next_release.md
doc/tutorials/install-webui.md

Teampartner: @Eiskasten
I rephrased, restructured and updated the outdated paths of the install-webui.md tutorial.
The tutorial sites are validated and built by the Jenkins CI.

[FLOSS T2] Update doc/tutorials/install-webui.md

---

doc/man/man7/elektra-libs.7
doc/news/_preparation_next_release.md

Only changed the date from December to July, as suggested by the CI.

doc: update manpage to fix CI error on master

---

doc/news/_preparation_next_release.md
scripts/docker/README.md

Fixes #4570 - by replacing the specific (no-more-existent image tag) with `latest`

[FLOSS T3] Update tag in scripts/docker/README.md

---

doc/CODING.md
doc/news/_preparation_next_release.md
scripts/dev/disable-pre-commit-hook
scripts/dev/enable-pre-commit-hook
scripts/dev/pre-commit-check-formatting
scripts/dev/reformat-c

We've discovered there is pre-commit-hook script available within the repository. We tried to make the script more accessible, by providing scripts to enable/disable the pre-commit hook and adding a mention to the documentation.
I mostly focused on writing and testing the scripts while @Dynamichost96 wrote additional documentation, and applied fixes to the existing reformatting scripts

[FLOSS T3] scripts: Add scripts to setup pre-commit-hook script

---

doc/news/_preparation_next_release.md
src/bindings/jna/plugins/whitelist/src/main/java/org/libelektra/plugin/WhitelistPlugin.java

Fixes #4001
Add new validation warnings on get. This is useful, as keys could be changed on disk, causing them to be stored in an invalid state.
I haven't added tests for this functionality, as I don't know how I could bypass the validation during set, such that I could even test this automatically.

[FLOSS H3] jna: whitelist plugin: add validation check on get

---

doc/contrib/README.md
doc/news/_preparation_next_release.md
doc/tutorials/README.md
tests/shell/CMakeLists.txt
tests/shell/check_doc.sh

[FLOSS H3] docs: extend check_doc.sh

---

doc/man/man1/kdb-run-website.1
doc/news/2014-07-28_0.8.7.md
doc/news/_preparation_next_release.md
doc/tutorials/language-bindings.md
src/tools/website/README.md

In parts of the documentation and website the dollar sign (e.g. for variables) was used outside of code blocks and therefore resulted in markdown rendering it as LaTeX.
Done in pair programming with @stefnotch 

[FLOSS T2] Fix LaTeX rendering

---

.github/CONTRIBUTING.md
doc/news/_preparation_next_release.md

Elektra is quite a big project and can be a bit overwhelming at first, if you want to contribute. We added some ideas, on what can be done to contribute and guide them to supporting documentation. We chose these categories based on what we think are the easiest ways to get started with contributing, as well as how good preexisting documentation is.
We worked on this PR in tandem

[FLOSS T3] docs: Improve CONTRIBUTING Documentation

---

doc/news/_preparation_next_release.md
doc/tutorials/run_all_tests_with_docker.md
tests/shell/shell_recorder/tutorial_wrapper/CMakeLists.txt

Additionally, we've updated the tutorial a bit, and removed redundant podman steps and added a notice on the top, that podman can be used instead of docker. 
We've manually disabled validations within the CI pipeline, as it would be very long, resource intensive, and I'm not sure if we even have access to the docker command within the environment.
If anyone has an idea how we could sensibly automate the validation of this tutorial, please let me know.
For now, reviews, if the manual validation of this script succeeds (`./build/tests/shell/shell_recorder/tutorial_wrapper/markdown_shell_recorder.sh doc/tutorials/run_all_tests_with_docker.md`) are greatly appreciated!
We worked on this issue entirely in pair …

[FLOSS T2] Add validation to run_all_tests_with_docker tutorial

---

doc/news/_preparation_next_release.md
doc/tutorials/plugins.md

Teampartner: @deoknats861 
I wrote this tutorial

[FLOSS T3] Add plugin memleak tutorial

---

doc/CODING.md
doc/doxygen/README.md
doc/news/_preparation_next_release.md

Teampartner: @Eiskasten
As starting with Doxygen can be quite overwhelming, I wanted to reduce this entry barrier by writing a README file that states information about the process in Elektra. There is also a section about Mermaid JS which I added in an earlier PR to the project (but was not documented until now).

[FLOSS T3] Add README for contributing in Doxygen

---

doc/api_blueprints/snippet-sharing.apib
doc/news/_preparation_next_release.md
doc/tutorials/validation.md
doc/usecases/snippet_sharing/UC_authenticate.md
doc/usecases/snippet_sharing/UC_reset_password.md
doc/usecases/snippet_sharing/distinction_use_cases.md
src/libs/meta/meta.c

During my work on #4742 I noticed some gender specific language.
@Bujuhu put forward the idea to test for this automatically. I don't think this is feasible.
I looked for "he/his" and replaced all occurrences where there was no disjunction with "she/her".

[FLOSS T3] Documentation: Improve use of gender

---

doc/news/_preparation_next_release.md
doc/tutorials/arrays.md

fixes #4250
We worked on this issue entirely in pair
The automatic validation of the tutorial is executed in jenkins

[FLOSS T2] tutorial: update array tutorial

---

.cirrus.yml
.github/workflows/macOS.yml
doc/news/_preparation_next_release.md

macOS: CI fixes

---

doc/news/_preparation_next_release.md
tests/valgrind.suppression

Should fix failing Jenkins builds on master.

xfconf: make valgrind suppressions more flexible to lib updates

---

doc/Git.md
doc/news/_preparation_next_release.md

We looked at, which parts of the git flow we struggled with during our contribution to libelektra and tried to add them to the existing GIT.md guide
We worked together on this document

[FLOSS T3] docs: Improve Git Documentation

---

doc/news/_preparation_next_release.md
src/plugins/mini/README.md
src/plugins/mini/mini.c
src/plugins/mini/testmod_mini.c

[FLOSS H3] mini: fix silent failure on meta-key insertion

---

CODE_OF_CONDUCT.md
doc/AUTHORS.md
doc/CODING.md
doc/COMPILE.md
doc/INSTALL.md
doc/README.md
doc/SECURITY.md
doc/TESTING.md
doc/VERSION.md
doc/WHO.md
doc/decisions/0b_rejected/elektra_web_pubsub.md
doc/decisions/3_decided/library_split.md
doc/decisions/5_implemented/error_codes.md
doc/decisions/5_implemented/rest_api_documentation.md
doc/man/man1/kdb-run-website.1
doc/news/_preparation_next_release.md
doc/todo/OPTIMIZE
doc/tutorials/highlevel-bindings.md
doc/tutorials/profiling.md
doc/tutorials/python-kdb.md
src/tools/website/README.md
src/tools/website/public/vendor/asciinema/asciinema-player.js
src/tools/website/resources/assets/skin/base/fonts/font-awesome/font-awesome.less
src/tools/website/resources/assets/skin/base/fonts/font-awesome/mixins.less
src/tools/website/resources/assets/skin/base/util/space.less
src/tools/webui/README.md
src/tools/webui/src/components/ErrorSnackbar.jsx
tests/kdb/testkdb_highlevel.cpp
tests/linkchecker.whitelist
tests/shell/check_formatting.sh

[FLOSS H3] links: Replace tons of http with https

---

doc/news/_preparation_next_release.md
scripts/link-checker

[FLOSS H3] Only let http links pass if whitelisted

---

doc/news/_preparation_next_release.md
src/plugins/network/README.md
src/plugins/network/network.c

[FLOSS H2] Implement network retries

---

doc/news/_preparation_next_release.md
src/plugins/desktop/CMakeLists.txt
src/plugins/desktop/testmod_desktop.c

Teampartner: @deoknats861
I have found the missing tests using the link were the coverages are listed: https://doc.libelektra.org/coverage/master/debian-bullseye-full/
These tests should run on every CI system which includes the plugin tests and does not exclude limited, unfinished or concept plugins or the desktop plugin explicitly.

[FLOSS T1] desktop: implement unit tests

---

doc/news/_preparation_next_release.md
scripts/dev/run_all.in
scripts/dev/run_checkshell.in
scripts/dev/run_memcheck.in
scripts/dev/run_nocheckshell.in
scripts/dev/run_nokdbtests.in
scripts/jenkins/Jenkinsfile
src/libs/tools/src/plugindatabase.cpp
tests/kdb/testkdb_allplugins.cpp
tests/valgrind.suppression

Attempts to fix #4671
Also fixes #4548 

Rerun failed

---

doc/news/_preparation_next_release.md
doc/todo/TESTING
src/bindings/erl_nif/elixir/CMakeLists.txt
src/bindings/intercept/env/tests/CMakeLists.txt

tests: Add `memleak` labels to failing tests

---

doc/news/_preparation_next_release.md

doc: release notes draft

---

doc/decisions/0_drafts/metakey_semantics.md
doc/news/_preparation_next_release.md

[decisions] metakey semantics

---

doc/decisions/0_drafts/transformations.md
doc/decisions/transformations.md
doc/help/elektra-glossary.md
doc/man/man7/elektra-glossary.7
doc/news/_preparation_next_release.md

[decisions] Transformations

---

.cirrus.yml
.github/workflows/macOS.yml
doc/decisions/0_drafts/transformations.md
doc/news/_preparation_next_release.md
scripts/dev/ci_run_tests.sh

ci: autorerun testmod_dbus tests on macOS

---

doc/news/_preparation_next_release.md
src/bindings/jna/java-library.gradle

This seems to fix #4844 for me, at least locally.

bindings/jna: update gradle file to make build work again

---

.cirrus.yml
.github/workflows/macOS.yml
doc/news/_preparation_next_release.md

macOS: fix dbus service name

---

doc/news/_preparation_next_release.md
src/plugins/backend/CMakeLists.txt

backend: add plugin to packaging components

---

doc/news/_preparation_next_release.md
scripts/jenkins/Jenkinsfile

jenkins: disable parallel tests

---

.github/CONTRIBUTING.md
.github/ISSUE_TEMPLATE.md
.github/PULL_REQUEST_TEMPLATE.md
doc/news/_preparation_next_release.md

doc: .github rework

---

doc/news/_preparation_next_release.md
scripts/docker/ubuntu/kinetic/Dockerfile
scripts/docker/ubuntu/kinetic/package.Dockerfile
scripts/docker/ubuntu/kinetic/release.Dockerfile
scripts/jenkins/Jenkinsfile
scripts/jenkins/Jenkinsfile.release

Ubuntu: add Kinetic Kudu (22.10) builds

---

doc/news/_preparation_next_release.md
src/plugins/hosts/README.md

set correct error code in hosts readme

---

doc/AUTHORS.md
doc/news/_preparation_next_release.md
scripts/cmake/Modules/LibAddMacros.cmake
src/libs/merge/README.md
src/plugins/dbus/README.md
src/plugins/internalnotification/README.md
src/plugins/logchange/README.md

doc: Maintainership for atmaxinger

---

.cirrus.yml
doc/news/_preparation_next_release.md
scripts/docker/centos/stream8/Dockerfile
scripts/docker/debian/bullseye/release.Dockerfile
scripts/docker/debian/buster/release.Dockerfile
scripts/docker/opensuse/15.3/release.Dockerfile
scripts/jenkins/Jenkinsfile
src/plugins/timeofday/README.md
src/plugins/timeofday/timeofday.c
src/plugins/timeofday/timeofday.h
src/plugins/tracer/tracer.c
src/plugins/tracer/tracer.h
src/plugins/xfconf/README.md
tests/shell/check_kdb_internal_check.sh

kdb plugin-check

---

doc/AUTHORS.md
doc/news/_preparation_next_release.md

add Stefan Hanreich to AUTHORS.md

---

doc/COMPILE.md
doc/news/_preparation_next_release.md
doc/tutorials/install-webui.md

Adapt and remove outdated docs COMPILE.md, install-webui.md

---

doc/AUTHORS.md
doc/man/man1/kdb-run-elektrad.1
doc/news/_preparation_next_release.md
doc/tutorials/install-webui.md
src/plugins/spec/README.md
src/tools/elektrad/README.md

add myself to authors.md

---

doc/news/_preparation_next_release.md
scripts/docker/centos/stream8/Dockerfile

docker: install DNF config-manager plugin

---

doc/COMPILE.md
doc/news/_preparation_next_release.md

Added missing dependency in COMPILE.md for APT-based systems

---

.cirrus.yml
.github/workflows/macOS.yml
doc/news/_preparation_next_release.md

Remove deprecated `d-bus` (#4900)

---

.cirrus.yml
doc/news/_preparation_next_release.md

FreeBSD 12.3 is EOL, this PR just pushes it to the latest 12.4 release.

ci: Push freebsd 12 to 12.4

---

doc/news/_preparation_next_release.md
src/tools/elektrad/helper_test.go
src/tools/elektrad/kdb_handler.go
src/tools/elektrad/kdb_handler_test.go
src/tools/elektrad/router.go
src/tools/webd/src/connector.js
src/tools/webd/src/routes/instances.js

`Webd` & `elektrad` new request for bulk creation for configurations (kdb set)

---

doc/news/_preparation_next_release.md
src/plugins/spec/README.md
src/plugins/spec/spec.c
src/plugins/spec/spec.h
src/plugins/spec/testmod_spec.c

Remove info meta key

---

doc/decisions/4_decided/elektra_malloc.md
doc/decisions/4_decided/elektra_prefix.md
doc/decisions/4_decided/key_below.md
doc/decisions/4_decided/private_api.md
doc/decisions/5_partially_implemented/decision_process.md
doc/news/_preparation_next_release.md

doc: minor fixes in decisions

---

doc/news/_preparation_next_release.md
src/bindings/go-elektra/README.md
src/bindings/go-elektra/go.mod
src/bindings/go-elektra/kdb/benchmark_test.go
src/bindings/go-elektra/kdb/kdb_test.go
src/bindings/go-elektra/kdb/key_test.go
src/bindings/go-elektra/kdb/keyset_test.go
src/tools/elektrad/benchmark_test.go
src/tools/elektrad/find_handler.go
src/tools/elektrad/go.mod
src/tools/elektrad/handlepool.go
src/tools/elektrad/helper_test.go
src/tools/elektrad/kdb.go
src/tools/elektrad/kdb_handler.go
src/tools/elektrad/meta_handler.go
src/tools/elektrad/middleware.go
src/tools/elektrad/move_handler.go

Rename module name go-elektra

---

doc/news/_preparation_next_release.md
src/bindings/go-elektra/README.md
src/bindings/go-elektra/go.mod
src/bindings/go-elektra/kdb/benchmark_test.go
src/bindings/go-elektra/kdb/kdb_test.go
src/bindings/go-elektra/kdb/key_test.go
src/bindings/go-elektra/kdb/keyset_test.go
src/tools/elektrad/benchmark_test.go
src/tools/elektrad/find_handler.go
src/tools/elektrad/go.mod
src/tools/elektrad/handlepool.go
src/tools/elektrad/helper_test.go
src/tools/elektrad/kdb.go
src/tools/elektrad/kdb_handler.go
src/tools/elektrad/meta_handler.go
src/tools/elektrad/middleware.go
src/tools/elektrad/move_handler.go

Fix wrong `go get` path in README and change module name for `go-elektra`

---

doc/news/_preparation_next_release.md
scripts/jenkins/Jenkinsfile.release
scripts/release/populate-release-notes.sh
scripts/release/release.sh

Fix version release pipeline

---

doc/news/_preparation_next_release.md
doc/todo/RELEASE.md

Remove wikipedia from release todos `doc/todo/RELEASE.md` 

---

doc/news/_preparation_next_release.md
scripts/release/populate-release-notes.sh
scripts/release/release.sh

fix: get git version tag also when v prefix is present

---

doc/news/_preparation_next_release.md
scripts/jenkins/Jenkinsfile.release
scripts/make-source-package.in

fix: use correct tag in make source package script

---

doc/news/_preparation_next_release.md
scripts/release/populate-release-notes.sh
scripts/release/release.sh

Fix release stats script

---

doc/news/_preparation_next_release.md
tests/linkchecker.whitelist

fix: whitelist link for linkchecker

---

doc/news/2023-05-23_0.10.0.md
doc/news/_preparation_next_release.md
doc/todo/NEWS.md
scripts/release/populate-release-notes.sh

Adapt docs

---

doc/news/_preparation_next_release.md
doc/usecases/integration/UC_developer.md
doc/usecases/integration/UC_end_user.md

Adds two use-cases for end-user and developer integration of libelektra.

Integration use-cases

---

doc/news/_preparation_next_release.md
src/plugins/toml/write.c

plugins/toml: correctly report error for unsupported meta key

---

doc/news/_preparation_next_release.md
src/plugins/spec/spec.c
src/plugins/spec/testmod_spec.c

fix: remove metakeys from array keys correctly (#4961)

---

doc/news/_preparation_next_release.md
doc/todo/RELEASE.md

doc: add git bundle and tags to release docu

---

doc/news/_preparation_next_release.md
doc/usecases/bindings/README.md
doc/usecases/bindings/UC_drop_in_application.md
doc/usecases/bindings/UC_existing_application.md
doc/usecases/bindings/UC_new_application.md

[Use Cases] Add use cases for bindings

---

doc/news/_preparation_next_release.md
doc/usecases/core/UC_key_base_name.md
doc/usecases/core/UC_key_clear.md
doc/usecases/core/UC_key_copy.md
doc/usecases/core/UC_key_lock.md
doc/usecases/core/UC_key_ref.md

[Use Cases] add additional use cases for Key in libelektra-core

---

doc/news/_preparation_next_release.md
scripts/jenkins/Jenkinsfile

ci: disable openwrt until we have found a new maintainer for it

---

doc/news/_preparation_next_release.md
scripts/docker/fedora/31/Dockerfile
scripts/docker/fedora/32/Dockerfile
scripts/docker/fedora/33/Dockerfile
scripts/docker/fedora/34/Dockerfile
scripts/docker/fedora/35/Dockerfile
scripts/docker/fedora/36/Dockerfile
scripts/docker/fedora/37/Dockerfile

Adding the option install_weak_deps=False reduces the image size of these fedora docker images #4637

Reduce fedora image size
